/*
 * File: app/model/modelAsset.js
 *
 * This file was generated by Sencha Architect version 4.3.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damProspect.model.modelAsset', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],


    fields: [
        {
            name: 'created_at'
        },
        {
            name: 'created_by'
        },
        {
            name: 'id_asset'
        },
        {
            name: 'mime_type'
        },
        {
            name: 'original_filename'
        },
        {
            name: 'size_bytes'
        },
        {
            name: 'file_extension'
        },
        {
            name: 'file_size'
        },
        {
            name: 'file_type'
        }
    ]

});