/*
 * File: app/view/contMain.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('basicUserAccess.view.contMain', {
    extend: 'Ext.Container',
    alias: 'widget.contMain',

    mixins: [
        'Ext.mixin.Responsive'
    ],
    requires: [
        'basicUserAccess.view.contMainViewModel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.field.Select',
        'Ext.dataview.DataView',
        'Ext.XTemplate'
    ],

    config: {
        responsiveConfig: 'responsiveConfig: {\n    \'width < 800\': {\n        layoutMode: \'mobile\' \n    },\n    \'width >= 800\': {\n        layoutMode: \'desktop\'\n    }\n}'
    },

    viewModel: {
        type: 'contmain'
    },
    id: 'contMain',
    itemId: 'contMain',
    fullscreen: true,
    layout: 'hbox',
    defaultListenerScope: true,

    listeners: {
        resize: 'onContMainResize',
        beforeshow: 'onContMainBeforeShow'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            id: 'contPanel',
            itemId: 'contPanel',
            layout: 'hbox',
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    id: 'contConfig',
                    itemId: 'contConfig',
                    layout: 'card',
                    items: [
                        {
                            xtype: 'toolbar',
                            id: 'toolbarMain',
                            itemId: 'toolbarMain',
                            docked: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btnCreate',
                                    itemId: 'btnCreate',
                                    ui: 'confirm',
                                    tooltip: 'Guardar colecciones',
                                    iconCls: 'fas fa-plus',
                                    text: 'Guardar',
                                    listeners: {
                                        tap: 'onBtnCreateTap'
                                    }
                                },
                                {
                                    xtype: 'spacer'
                                },
                                {
                                    xtype: 'selectfield',
                                    id: 'cboUser',
                                    itemId: 'cboUser',
                                    margin: '0 8 0 0',
                                    label: 'Usuario',
                                    displayField: 'label',
                                    store: 'storeUser',
                                    valueField: 'id_user',
                                    listeners: {
                                        change: 'onCboUserChange'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            id: 'contListConfig',
                            itemId: 'contListConfig',
                            scrollable: true,
                            items: [
                                {
                                    xtype: 'container',
                                    id: 'contHeaderConfig',
                                    itemId: 'contHeaderConfig',
                                    html: '<div class="resource-row header-style">     <div class="conf-col-code">CÓDIGO</div>     <div class="conf-col-desc">DESCRIPCIÓN</div>     <div class="col-actions">ACCIONES</div> </div>'
                                },
                                {
                                    xtype: 'dataview',
                                    id: 'dataViewConfig',
                                    itemId: 'dataViewConfig',
                                    itemTpl: [
                                        '<div class="resource-row selectable-row {[values.selected ? \'is-selected\' : \'\']} {[values.is_active ? \'\' : \'user-inactive\']}">',
                                        '',
                                        '    <div class="tree-col-code">',
                                        '        <div class="text-bold">Colección</div>',
                                        '        <div class="sub-text">Id: {id_collection}</div>',
                                        '    </div>',
                                        '',
                                        '    <div class="tree-col-desc">',
                                        '        <div class="main-text text-bold">',
                                        '            {name}',
                                        '        </div>',
                                        '        <div class="sub-text">',
                                        '            <span class="status-dot {[values.is_active ? \'active\' : \'inactive\']}"></span>',
                                        '            <tpl if="values.is_active">',
                                        '                Activa',
                                        '            <tpl else>',
                                        '                Inactiva',
                                        '            </tpl>',
                                        '',
                                        '            <tpl if="values.selected">',
                                        '                <span class="selection-label"> • Asignada</span>',
                                        '            <tpl else>',
                                        '                <span class="selection-label"> • Disponible</span>',
                                        '            </tpl>',
                                        '        </div>',
                                        '    </div>',
                                        '',
                                        '    <div class="col-actions">',
                                        '        <div class="select-pill {[values.selected ? \'selected\' : \'unselected\']}">',
                                        '            <tpl if="values.selected">',
                                        '                <i class="x-fa fas fa-check"></i>',
                                        '            <tpl else>',
                                        '                <i class="x-fa far fa-circle"></i>',
                                        '            </tpl>',
                                        '        </div>',
                                        '    </div>',
                                        '',
                                        '</div>'
                                    ],
                                    store: 'storeCollection',
                                    listeners: {
                                        childtap: 'onDataViewConfigChildtap'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onContMainResize: function(element, info, eOpts) {
        console.log('>>>resizswse');
        console.log(element);

        console.log('>>>info');
        console.log(info);


        let width = info;

        // 1. Log para depurar
            console.log('El ancho actual es:', width);

            // 2. Lógica condicional
            // Importante: Verifica el layout actual para no forzarlo mil veces si no ha cambiado
            var currentLayout = this.getLayout().type;

            if (width < 1000 /*&& currentLayout !== 'vbox'*/) {
                console.log('-> Cambiando a Modo Móvil');
                this.setLayout('hbox');
            }
            else if (width >= 1000 /*&& currentLayout !== 'hbox'*/) {
                console.log('-> Cambiando a Modo Escritorio');
                this.setLayout('vbox');
            }

    },

    onBtnCreateTap: function(button, e, eOpts) {
        var userId = jsTerian.readElementValue('cboUser');

        if (!userId) {
            //jsDam.toast({ type:'success', title:'Éxito', message: 'Éxito' });
            Ext.Msg.alert('Validación', 'Debes seleccionar un usuario');
            return;
        }

        appLocal.saveUserCollections(userId);
    },

    onCboUserChange: function(selectfield, newValue, oldValue, eOpts) {
        if (!newValue) {
            return;
        }

        appLocal.getUserCollections(newValue);
    },

    onDataViewConfigChildtap: function(dataview, location, eOpts) {
        var btn = location.event.getTarget('.action-btn');
        var record = location.record;

        if (!record) {
            return;
        }

        if (btn) {
            var action = btn.getAttribute('data-action');
            location.event.stopEvent();

            switch (action) {
                case 'toggle-select':
                    record.set('selected', !record.get('selected'));
                    break;

                default:
                    console.log('Evento no definido');
            }

            return;
        }

        // Si se toca fuera del botón, también alterna selección
        record.set('selected', !record.get('selected'));
    },

    onContMainBeforeShow: function(component, eOpts) {
        jsTerian.loadStore('storeUser');
        jsTerian.loadStore('storeRole');
    },

    buildCollectionsPayload: function() {
        var store = Ext.getStore('storeCollection');
        var collectionIds = [];

        if (!store) {
            return {
                collection_ids: []
            };
        }

        store.each(function (rec) {
            if (rec.get('selected')) {
                collectionIds.push(rec.get('id_collection'));
            }
        });

        return {
            collection_ids: collectionIds
        };
    }

});