/*
 * File: app/store/storeAsset.js
 *
 * This file was generated by Sencha Architect version 4.3.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damProspect.store.storeAsset', {
    extend: 'Ext.data.Store',

    requires: [
        'damProspect.model.modelAsset'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeAsset',
            model: 'damProspect.model.modelAsset',
            listeners: {
                load: {
                    fn: me.onStoreLoad
                }
            }
        }, cfg)]);
    },

    onStoreLoad: function(store, records, successful, operation, eOpts) {
        console.log('cargadop');



        console.log('store - records >>>',records);


    }

});