/*
 * File: app/view/contMain.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('basicConfig.view.contMain', {
    extend: 'Ext.Container',
    alias: 'widget.contMain',

    mixins: [
        'Ext.mixin.Responsive'
    ],
    requires: [
        'basicConfig.view.contMainViewModel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.form.Panel',
        'Ext.field.ComboBox'
    ],

    config: {
        responsiveConfig: 'responsiveConfig: {\n    \'width < 800\': {\n        layoutMode: \'mobile\' \n    },\n    \'width >= 800\': {\n        layoutMode: \'desktop\'\n    }\n}'
    },

    viewModel: {
        type: 'contmain'
    },
    id: 'contMain',
    itemId: 'contMain',
    fullscreen: true,
    layout: 'hbox',
    defaultListenerScope: true,

    listeners: {
        resize: 'onContMainResize',
        beforeshow: 'onContMainBeforeShow'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            id: 'contPanel',
            itemId: 'contPanel',
            layout: 'hbox',
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    id: 'contConfig',
                    itemId: 'contConfig',
                    layout: 'card',
                    items: [
                        {
                            xtype: 'toolbar',
                            id: 'toolbarMain',
                            itemId: 'toolbarMain',
                            docked: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btnCreate',
                                    itemId: 'btnCreate',
                                    ui: 'confirm',
                                    iconCls: 'fas fa-plus',
                                    text: 'Agregar',
                                    listeners: {
                                        tap: 'onBtnCreateTap'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {

                                    },
                                    id: 'btnDelete',
                                    itemId: 'btnDelete',
                                    ui: 'decline',
                                    iconCls: 'fas fa-trash',
                                    text: 'Eliminar'
                                },
                                {
                                    xtype: 'spacer'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnLoad',
                                    itemId: 'btnLoad',
                                    text: 'MyButton1',
                                    listeners: {
                                        tap: 'onBtnLoadTap'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            id: 'contListConfig',
                            itemId: 'contListConfig',
                            scrollable: true,
                            items: [
                                {
                                    xtype: 'container',
                                    id: 'contHeaderConfig',
                                    itemId: 'contHeaderConfig',
                                    html: '<div class="resource-row header-style">     <div class="col-code">CÓDIGO</div>     <div class="col-desc">DESCRIPCIÓN</div>     <div class="col-actions">ACCIONES</div> </div>'
                                },
                                {
                                    xtype: 'dataview',
                                    id: 'dataViewConfig',
                                    itemId: 'dataViewConfig',
                                    itemTpl: [
                                        '<div class="resource-row {[values.is_active ? \'\' : \'config-inactive\']}"',
                                        '     style="{[',
                                        '            values.is_active',
                                        '            ? \'display:flex; align-items:center; gap:10px; padding:20px 14px; border-left:4px solid #28a745; background:rgba(40,167,69,0.06);\'',
                                        '            : \'display:flex; align-items:center; gap:10px; padding:20px 14px; border-left:4px solid #d9534f; background:rgba(217,83,79,0.06); opacity:0.75;\'',
                                        '            ]}">',
                                        '',
                                        '    <!-- CÓDIGO (angosto) -->',
                                        '    <div class="col-code" style="flex:0 0 88px;">',
                                        '        <div class="text-bold"',
                                        '             style="{[values.is_active ? \'color:#1f7a3a; font-size:14px; line-height:18px;\' : \'color:#d9534f; font-size:14px; line-height:18px;\']}">',
                                        '            {cod_configuration}',
                                        '        </div>',
                                        '        <div class="role-badge" style="margin-top:10px; font-size:20px;">',
                                        '            Id: {id_configuration}',
                                        '        </div>',
                                        '    </div>',
                                        '',
                                        '    <!-- DESCRIPCIÓN (que se estire y ocupe TODO) -->',
                                        '    <div class="col-desc" style="flex:1 1 auto; min-width:0;">',
                                        '        <div class="main-text" style="font-size:30px; line-height:20px; font-weight:600;">',
                                        '            <span class="status-dot {[values.is_active ? \'active\' : \'inactive\']}"',
                                        '                  style="{[values.is_active ? \'background:#28a745;\' : \'background:#d9534f;\']}"></span>',
                                        '            {name}',
                                        '            <span style="{[',
                                        '                         values.is_active',
                                        '                         ? \'margin-left:10px; color:#1f7a3a; font-weight:700; font-size:12px;\'',
                                        '                         : \'margin-left:10px; color:#d9534f; font-weight:700; font-size:12px;\'',
                                        '                         ]}">',
                                        '                {[values.is_active ? \'ACTIVO\' : \'INACTIVO\']}',
                                        '            </span>',
                                        '        </div>',
                                        '',
                                        '        <div class="sub-text" style="margin-top:10px; font-size:24px; line-height:20px;">',
                                        '            <i class="x-fa fas fa-align-left tiny-icon"></i> {description}',
                                        '        </div>',
                                        '    </div>',
                                        '',
                                        '    <!-- ACCIONES (fijo y compacto para no robar ancho) -->',
                                        '    <div class="col-actions" style="flex:0 0 180px; display:flex; justify-content:flex-end; gap:14px;">',
                                        '        <div class="action-btn view" data-action="view" title="Ver Detalles"',
                                        '             style="width:52px; height:52px; border-radius:26px; display:flex; align-items:center; justify-content:center; background:rgba(0,0,0,0.06);">',
                                        '            <i class="x-fa fas fa-eye" style="font-size:26px;"></i>',
                                        '        </div>',
                                        '',
                                        '        <div class="action-btn edit" data-action="edit" title="Editar Configuración"',
                                        '             style="width:52px; height:52px; border-radius:26px; display:flex; align-items:center; justify-content:center; background:rgba(0,0,0,0.06);">',
                                        '            <i class="x-fa fas fa-pen" style="font-size:26px;"></i>',
                                        '        </div>',
                                        '',
                                        '        <div class="action-btn delete" data-action="delete" title="{[values.is_active ? \'Desactivar\' : \'Activar\']}"',
                                        '             style="width:52px; height:52px; border-radius:26px; display:flex; align-items:center; justify-content:center; background:rgba(0,0,0,0.06);">',
                                        '            <i class="x-fa {[values.is_active ? \'fas fa-ban\' : \'fas fa-check\']}" style="font-size:26px;"></i>',
                                        '        </div>',
                                        '    </div>',
                                        '</div>'
                                    ],
                                    store: 'storeConfig',
                                    listeners: {
                                        childtap: 'onDataViewConfigChildtap'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'formpanel',
                            isCreate: true,
                            id: 'formConfig',
                            itemId: 'formConfig',
                            title: 'Configuración',
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'ftCfgCode',
                                    itemId: 'ftCfgCode',
                                    margin: 8,
                                    modelValidation: false,
                                    label: 'Código'
                                },
                                {
                                    xtype: 'combobox',
                                    id: 'cboCfgActive',
                                    itemId: 'cboCfgActive',
                                    margin: 8,
                                    label: 'Estado',
                                    editable: false,
                                    store: {
                                        fields: [
                                            'text',
                                            'value'
                                        ],
                                        data: [
                                            {
                                                text: 'Activo',
                                                value: true
                                            },
                                            {
                                                text: 'Inactivo',
                                                value: false
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'ftCfgName',
                                    itemId: 'ftCfgName',
                                    margin: 8,
                                    label: 'Nombre'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'ftCfgDesc',
                                    itemId: 'ftCfgDesc',
                                    margin: 8,
                                    label: 'Descripción'
                                },
                                {
                                    xtype: 'toolbar',
                                    itemId: 'mytoolbar1',
                                    docked: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnConfirm',
                                            itemId: 'btnConfirm',
                                            ui: 'confirm',
                                            text: 'Confirmar',
                                            listeners: {
                                                tap: 'onBtnConfirmTap'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnCreateParam',
                                            itemId: 'btnCreateParam',
                                            ui: 'confirm',
                                            iconCls: 'fas fa-plus',
                                            text: 'Agregar',
                                            listeners: {
                                                tap: 'onBtnCreateTap1'
                                            }
                                        },
                                        {
                                            xtype: 'spacer'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnCancel',
                                            itemId: 'btnCancel',
                                            ui: 'decline',
                                            text: 'Cancelar',
                                            listeners: {
                                                tap: 'onBtnCancelTap'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    id: 'contListParam',
                                    itemId: 'contListParam',
                                    scrollable: true,
                                    items: [
                                        {
                                            xtype: 'container',
                                            id: 'contHeaderParam',
                                            itemId: 'contHeaderParam',
                                            html: '<div class="resource-row header-style">     <div class="col-code">CÓDIGO</div>     <div class="col-desc">DESCRIPCIÓN</div>     <div class="col-actions">ACCIONES</div> </div>'
                                        },
                                        {
                                            xtype: 'dataview',
                                            id: 'dataViewParam',
                                            itemId: 'dataViewParam',
                                            itemTpl: [
                                                '<div class="resource-row {[values.is_active ? \'\' : \'config-inactive\']}"',
                                                '     style="{[',
                                                '            values.is_active',
                                                '            ? \'display:flex; align-items:center; gap:10px; padding:20px 14px; border-left:4px solid #28a745; background:rgba(40,167,69,0.06);\'',
                                                '            : \'display:flex; align-items:center; gap:10px; padding:20px 14px; border-left:4px solid #d9534f; background:rgba(217,83,79,0.06); opacity:0.75;\'',
                                                '            ]}">',
                                                '',
                                                '    <!-- CÓDIGO (angosto) -->',
                                                '    <div class="col-code" style="flex:0 0 88px;">',
                                                '        <div class="text-bold"',
                                                '             style="{[values.is_active ? \'color:#1f7a3a; font-size:14px; line-height:18px;\' : \'color:#d9534f; font-size:14px; line-height:18px;\']}">',
                                                '            {cod_parameter}',
                                                '        </div>',
                                                '        <div class="role-badge" style="margin-top:10px; font-size:20px;">',
                                                '            Id: {id_parameter}',
                                                '        </div>',
                                                '    </div>',
                                                '',
                                                '    <!-- DESCRIPCIÓN (que se estire y ocupe TODO) -->',
                                                '    <div class="col-desc" style="flex:1 1 auto; min-width:0;">',
                                                '        <div class="main-text" style="font-size:30px; line-height:20px; font-weight:600;">',
                                                '            <span class="status-dot {[values.is_active ? \'active\' : \'inactive\']}"',
                                                '                  style="{[values.is_active ? \'background:#28a745;\' : \'background:#d9534f;\']}"></span>',
                                                '            {description}',
                                                '            <span style="{[',
                                                '                         values.is_active',
                                                '                         ? \'margin-left:10px; color:#1f7a3a; font-weight:700; font-size:12px;\'',
                                                '                         : \'margin-left:10px; color:#d9534f; font-weight:700; font-size:12px;\'',
                                                '                         ]}">',
                                                '                {[values.is_active ? \'ACTIVO\' : \'INACTIVO\']}',
                                                '            </span>',
                                                '        </div>',
                                                '',
                                                '        <div class="sub-text" style="margin-top:10px; font-size:24px; line-height:20px;">',
                                                '            <i class="x-fa fas fa-align-left tiny-icon"></i> {value}',
                                                '        </div>',
                                                '    </div>',
                                                '',
                                                '    <!-- ACCIONES (fijo y compacto para no robar ancho) -->',
                                                '    <div class="col-actions" style="flex:0 0 180px; display:flex; justify-content:flex-end; gap:14px;">',
                                                '        <div class="action-btn view" data-action="view" title="Ver Detalles"',
                                                '             style="width:52px; height:52px; border-radius:26px; display:flex; align-items:center; justify-content:center; background:rgba(0,0,0,0.06);">',
                                                '            <i class="x-fa fas fa-eye" style="font-size:26px;"></i>',
                                                '        </div>',
                                                '',
                                                '        <div class="action-btn edit" data-action="edit" title="Editar Configuración"',
                                                '             style="width:52px; height:52px; border-radius:26px; display:flex; align-items:center; justify-content:center; background:rgba(0,0,0,0.06);">',
                                                '            <i class="x-fa fas fa-pen" style="font-size:26px;"></i>',
                                                '        </div>',
                                                '',
                                                '        <div class="action-btn delete" data-action="delete" title="{[values.is_active ? \'Desactivar\' : \'Activar\']}"',
                                                '             style="width:52px; height:52px; border-radius:26px; display:flex; align-items:center; justify-content:center; background:rgba(0,0,0,0.06);">',
                                                '            <i class="x-fa {[values.is_active ? \'fas fa-ban\' : \'fas fa-check\']}" style="font-size:26px;"></i>',
                                                '        </div>',
                                                '    </div>',
                                                '</div>'
                                            ],
                                            store: 'storeParam',
                                            listeners: {
                                                childtap: 'onDataViewParamChildtap'
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'formpanel',
                            isCreate: true,
                            id: 'formParam',
                            itemId: 'formParam',
                            title: 'Parámetros',
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'ftParamCode',
                                    itemId: 'ftParamCode',
                                    margin: 8,
                                    modelValidation: false,
                                    label: 'Código'
                                },
                                {
                                    xtype: 'combobox',
                                    id: 'cboParamActive',
                                    itemId: 'cboParamActive',
                                    margin: 8,
                                    label: 'Estado',
                                    editable: false,
                                    store: {
                                        fields: [
                                            'text',
                                            'value'
                                        ],
                                        data: [
                                            {
                                                text: 'Activo',
                                                value: true
                                            },
                                            {
                                                text: 'Inactivo',
                                                value: false
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'ftParamValue',
                                    itemId: 'ftParamValue',
                                    margin: 8,
                                    label: 'Valor'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'ftParamDesc',
                                    itemId: 'ftParamDesc',
                                    margin: 8,
                                    label: 'Descripción'
                                },
                                {
                                    xtype: 'toolbar',
                                    itemId: 'mytoolbar1',
                                    docked: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnConfirm1',
                                            itemId: 'btnConfirm',
                                            ui: 'confirm',
                                            text: 'Confirmar',
                                            listeners: {
                                                tap: 'onBtnConfirmTap1'
                                            }
                                        },
                                        {
                                            xtype: 'spacer'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnCancel1',
                                            itemId: 'btnCancel',
                                            ui: 'decline',
                                            text: 'Cancelar',
                                            listeners: {
                                                tap: 'onBtnCancelTap1'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onContMainResize: function(element, info, eOpts) {
        console.log('>>>resizswse');
        console.log(element);

        console.log('>>>info');
        console.log(info);


        let width = info;

        // 1. Log para depurar
            console.log('El ancho actual es:', width);

            // 2. Lógica condicional
            // Importante: Verifica el layout actual para no forzarlo mil veces si no ha cambiado
            var currentLayout = this.getLayout().type;

            if (width < 1000 /*&& currentLayout !== 'vbox'*/) {
                console.log('-> Cambiando a Modo Móvil');
                this.setLayout('hbox');
            }
            else if (width >= 1000 /*&& currentLayout !== 'hbox'*/) {
                console.log('-> Cambiando a Modo Escritorio');
                this.setLayout('vbox');
            }

    },

    onBtnCreateTap: function(button, e, eOpts) {
        /*
        // Buscas el contenedor padre
        var contUser    = Ext.getCmp('contUser'); // Asegúrate de tener reference='contResource'
        var toolbarMain = Ext.getCmp('toolbarMain');

        // Cambias a la vista del formulario (que es el item 1)
        // La animación 'slide' hará que parezca que entras a una nueva página
        contUser.setActiveItem(1);
        toolbarMain.hide();
        */
        var form = Ext.getCmp("formConfig");
        form.isCreate = true;

        this.showForm();
    },

    onBtnLoadTap: function(button, e, eOpts) {
        Ext.getStore('storeUser').load();
    },

    onDataViewConfigChildtap: function(dataview, location, eOpts) {
        // 1. Detectar si el toque fue en un botón de acción
        // Buscamos la clase '.action-btn' en el elemento tocado o sus padres
        var btn = location.event.getTarget('.action-btn');

        if (btn) {
            // 2. Extraer la acción y el registro
            var action = btn.getAttribute('data-action');
            var record = location.record.data;

            // Detenemos la propagación para que no seleccione la fila al tocar el botón
            location.event.stopEvent();

            // 3. Switch Maestro de Acciones
            switch (action) {
                case 'view':
                    console.warn('Tap: view');
                    var form = Ext.getCmp("formConfig");
                    form.isCreate = false;
                    form.configRecord = record;
                    this.showForm();
                    break;

                case 'edit':
                    console.warn('Tap: view');
                    var form = Ext.getCmp("formConfig");
                    form.isCreate = false;
                    form.configRecord = record;
                    this.showForm();
                    break;

                case 'download':
                    console.warn('Tap: download');
                    this.downloadFile(record);
                    break;

                case 'email':
                    console.warn('Tap: email');
                    this.sendByEmail(record);
                    break;

                case 'whatsapp':
                    console.warn('Tap: whatsapp');
                    this.sendToWhatsApp(record);
                    break;

                case 'attach':
                    console.warn('Tap: attach');
                    this.copyLinkToClipboard(record);
                    break;

                case 'delete':
                    Ext.Msg.show({
                        title: 'Eliminar Registro',
                        message: '¿Realmente deseas eliminar este registro? Esta acción no se puede deshacer.',
                        width: 300, // Opcional
                        closable: false,
                        icon: Ext.Msg.QUESTION,
                        buttons: [
                            {
                                text: 'No',
                                itemId: 'no'
                            },
                            {
                                text: 'Sí, borrar',
                                itemId: 'yes',
                                ui: 'action-decline' // En Modern, esto suele poner el botón en rojo
                            }
                        ],
                        fn: function (buttonId) {
                            if (buttonId === 'yes') {

                                var idConfig = record.id_configuration;
                                appLocal.deleteConfig(idConfig);

                                console.log('Registro eliminado');
                            }
                        }
                    });
                    break;

                default:
                    console.log('Evento no definido');
            }
        }
    },

    onBtnConfirmTap: function(button, e, eOpts) {
        var contMain = Ext.getCmp('contMain');

        var payload = contMain.buildConfigPayload();

        console.info(payload);
        appLocal.saveConfig(payload);
    },

    onBtnCreateTap1: function(button, e, eOpts) {
        /*
        // Buscas el contenedor padre
        var contUser    = Ext.getCmp('contUser'); // Asegúrate de tener reference='contResource'
        var toolbarMain = Ext.getCmp('toolbarMain');

        // Cambias a la vista del formulario (que es el item 1)
        // La animación 'slide' hará que parezca que entras a una nueva página
        contUser.setActiveItem(1);
        toolbarMain.hide();
        */
        var form = Ext.getCmp("formParam");
        form.isCreate = true;

        this.showFormParam();
    },

    onBtnCancelTap: function(button, e, eOpts) {
        var contConfig  = Ext.getCmp('contConfig');
        var toolbarMain = Ext.getCmp('toolbarMain');

        contConfig.setActiveItem(0);
        toolbarMain.show();

        this.cleanConfigForm();
    },

    onDataViewParamChildtap: function(dataview, location, eOpts) {
        // 1. Detectar si el toque fue en un botón de acción
        // Buscamos la clase '.action-btn' en el elemento tocado o sus padres
        var btn = location.event.getTarget('.action-btn');

        if (btn) {
            // 2. Extraer la acción y el registro
            var action = btn.getAttribute('data-action');
            var record = location.record.data;

            // Detenemos la propagación para que no seleccione la fila al tocar el botón
            location.event.stopEvent();

            // 3. Switch Maestro de Acciones
            switch (action) {
                case 'view':
                    console.warn('Tap: view');
                    var form = Ext.getCmp("formParam");
                    form.isCreate = false;
                    form.paramRecord = record;
                    this.showFormParam();
                    break;

                case 'edit':
                    console.warn('Tap: view');
                    var form = Ext.getCmp("formParam");
                    form.isCreate = false;
                    form.paramRecord = record;
                    this.showFormParam();
                    break;

                case 'download':
                    console.warn('Tap: download');
                    this.downloadFile(record);
                    break;

                case 'email':
                    console.warn('Tap: email');
                    this.sendByEmail(record);
                    break;

                case 'whatsapp':
                    console.warn('Tap: whatsapp');
                    this.sendToWhatsApp(record);
                    break;

                case 'attach':
                    console.warn('Tap: attach');
                    this.copyLinkToClipboard(record);
                    break;

                case 'delete':
                    Ext.Msg.show({
                        title: 'Eliminar Registro',
                        message: '¿Realmente deseas eliminar este registro? Esta acción no se puede deshacer.',
                        width: 300, // Opcional
                        closable: false,
                        icon: Ext.Msg.QUESTION,
                        buttons: [
                            {
                                text: 'No',
                                itemId: 'no'
                            },
                            {
                                text: 'Sí, borrar',
                                itemId: 'yes',
                                ui: 'action-decline' // En Modern, esto suele poner el botón en rojo
                            }
                        ],
                        fn: function (buttonId) {
                            if (buttonId === 'yes') {

                                var idParam = record.id_parameter;
                                appLocal.deleteParam(idParam);

                                console.log('Registro eliminado');
                            }
                        }
                    });
                    break;

                default:
                    console.log('Evento no definido');
            }
        }
    },

    onBtnConfirmTap1: function(button, e, eOpts) {
        var contMain = Ext.getCmp('contMain');

        var payload = contMain.buildParamPayload();

        console.info(payload);
        appLocal.saveParam(payload);
    },

    onBtnCancelTap1: function(button, e, eOpts) {
        var contConfig  = Ext.getCmp('contConfig');
        var toolbarMain = Ext.getCmp('toolbarMain');

        contConfig.setActiveItem(1);
        toolbarMain.show();

        //this.cleanConfigForm();
    },

    onContMainBeforeShow: function(component, eOpts) {
        jsTerian.loadStore('storeUser');
        jsTerian.loadStore('storeRole');
    },

    buildConfigPayload: function() {
        var form     = Ext.getCmp('formConfig');
        var record   = form.configRecord;
        var isCreate = form.isCreate;

        var id_configuration = record ? record.id_configuration : null;

        const payload = {
            id_configuration : id_configuration,
            cod_configuration: jsTerian.readElementValue("ftCfgCode"),
            name             : jsTerian.readElementValue("ftCfgName"),
            description      : jsTerian.readElementValue("ftCfgDesc"),
            is_active        : jsTerian.readElementValue("cboCfgActive")
        };

        // Validaciones
        if (!payload.cod_configuration || String(payload.cod_configuration).trim() === '') {
            jsTerian.toastAlert("El código es obligatorio.", "error");
            return null;
        }

        if (!payload.name || String(payload.name).trim() === '') {
            jsTerian.toastAlert("El nombre es obligatorio.", "error");
            return null;
        }

        // Normalizar
        payload.cod_configuration = String(payload.cod_configuration).trim().toUpperCase();
        payload.name = String(payload.name).trim();

        if (payload.description !== null && payload.description !== undefined) {
            payload.description = String(payload.description).trim();
        }

        // Create / Update
        if (isCreate) {
            delete payload.id_configuration;
        } else {
            if (!payload.id_configuration) {
                jsTerian.toastAlert("No se puede actualizar: falta id_configuration.", "error");
                return null;
            }

            if (!payload.description || payload.description === '') {
                delete payload.description;
            }
        }

        return payload;
    },

    buildParamPayload: function() {
        var form = Ext.getCmp('formParam');
        var record = form.paramRecord;
        var isCreate = form.isCreate;

        var id_conf_parameter = record ? record.id_conf_parameter : null;

        // OJO: id_configuration normalmente viene “fijo” porque estás editando parámetros dentro de una configuración.
        // Puedes leerlo del form o del record.
        // Si tu form lo tiene guardado: form.id_configuration
        var id_configuration = (record && record.id_configuration) ? record.id_configuration : form.id_configuration;

        const payload = {
          id_conf_parameter: id_conf_parameter,
          id_configuration : id_configuration,
          cod_parameter    : jsTerian.readElementValue("ftParamCode"),
          description      : jsTerian.readElementValue("ftParamDesc"),
          value            : jsTerian.readElementValue("ftParamValue"),
          is_active        : jsTerian.readElementValue("cboParamActive"),
        };

        // Validaciones mínimas
        if (!payload.id_configuration) {
          jsTerian.toastAlert("Falta id_configuration (no se puede guardar el parámetro).", "error");
          return null;
        }

        if (!payload.cod_parameter || String(payload.cod_parameter).trim() === '') {
          jsTerian.toastAlert("El código del parámetro es obligatorio.", "error");
          return null;
        }

        if (!payload.value || String(payload.value).trim() === '') {
          jsTerian.toastAlert("El valor es obligatorio.", "error");
          return null;
        }

        // Normalizar
        payload.cod_parameter = String(payload.cod_parameter).trim().toUpperCase();
        payload.value = String(payload.value).trim();

        if (payload.description !== null && payload.description !== undefined) {
          payload.description = String(payload.description).trim();
        }

        // (Opcional) Si para CFG_APP quieres asegurar que la ruta empiece con "/"
        if (payload.value && payload.value[0] !== '/') {
          payload.value = '/' + payload.value;
        }

        // Create / Update
        if (isCreate) {
          delete payload.id_conf_parameter;

        } else {
          if (!payload.id_conf_parameter) {
            jsTerian.toastAlert("No se puede actualizar: falta id_conf_parameter.", "error");
            return null;
          }

          // si description viene vacía, no la mandes (para no sobreescribir con vacío)
          if (payload.description === '') delete payload.description;
        }

        return payload;
    },

    showConfig: function(record) {
        const mapping = {
          ftCfgCode   : record.cod_configuration,
          ftCfgName   : record.name,
          ftCfgDesc   : record.description,
          cboCfgActive: record.is_active
          // Auditoría?
        };

        Ext.Object.each(mapping, function(field, value){
          jsTerian.assignElementValue(field, value);
        });
    },

    showParam: function(record) {
        // record
        const mapping = {
          ftParamCode   : record.cod_parameter,
          ftParamDesc   : record.description,
          ftParamValue  : record.value,
          cboParamActive: record.is_active
          // Auditoría no por ahora
        };

        Ext.Object.each(mapping, function(field, value){
          jsTerian.assignElementValue(field, value);
        });
    },

    showForm: function() {
        var contConfig  = Ext.getCmp('contConfig');
        var toolbarMain = Ext.getCmp('toolbarMain');

        contConfig.setActiveItem(1);
        toolbarMain.hide();

        // Obtener el form y la propiedad isCreate
        var form     = Ext.getCmp("formConfig");
        var isCreate = form.isCreate;
        var record   = form.configRecord;

        if (isCreate) {
            console.log('create');
        } else {
            console.log('update');

            // Cargar el store
            jsTerian.loadStore('storeParam',record.id_configuration);

            // Mostrar los datos del record de config
            this.showConfig(record);
        }
    },

    showFormParam: function() {
        var contConfig  = Ext.getCmp('contConfig');
        var toolbarMain = Ext.getCmp('toolbarMain');

        contConfig.setActiveItem(2);
        toolbarMain.hide();

        // Obtener el form y la propiedad isCreate
        var form     = Ext.getCmp("formParam");
        var isCreate = form.isCreate;
        var record   = form.paramRecord;

        if (isCreate) {
            console.log('create');
        } else {
            console.log('update');

            // Cargar el store
            //jsTerian.loadStore('storeParam',record.id_configuration);

            // Mostrar los datos del record de config
            this.showParam(record);
        }
    },

    showDataView: function() {
        var contUser    = Ext.getCmp('contUser');
        var toolbarMain = Ext.getCmp('toolbarMain');

        contUser.setActiveItem(0);
        toolbarMain.show();
    },

    cleanConfigForm: function() {
        try {
            const mapping = {
                ftCfgCode   : '',
                ftCfgName   : '',
                ftCfgDesc   : '',
                cboCfgActive: true
            };

            Ext.Object.each(mapping, function (field, value) {
                jsTerian.assignElementValue(field, value);
            });

            // Limpiar el store
            var storeParam = Ext.getStore('storeParam');
            if (storeParam) storeParam.removeAll();

        } finally {
            var form = Ext.getCmp("formConfig");
            form.isCreate = true;
            form.configRecord = null;
        }
    },

    cleanParamForm: function() {
        try {
            const mapping = {
              ftParamCode   : '',
              ftParamDesc   : '',
              ftParamValue  : '',
              cboParamActive: true
            };

            Ext.Object.each(mapping, function (field, value) {
              jsTerian.assignElementValue(field, value);
            });

          } finally {
            var form = Ext.getCmp("formParameter");
            form.isCreate = true;
            form.paramRecord = null;
          }
    }

});