/*
 * File: app/view/contMain.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('basicConfig.view.contMain', {
    extend: 'Ext.Container',
    alias: 'widget.contMain',

    mixins: [
        'Ext.mixin.Responsive'
    ],
    requires: [
        'basicConfig.view.contMainViewModel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.SegmentedButton',
        'Ext.Spacer',
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.form.Panel',
        'Ext.Label',
        'Ext.field.ComboBox',
        'Ext.field.TextArea'
    ],

    config: {
        responsiveConfig: 'responsiveConfig: {\n    \'width < 800\': {\n        layoutMode: \'mobile\' \n    },\n    \'width >= 800\': {\n        layoutMode: \'desktop\'\n    }\n}'
    },

    viewModel: {
        type: 'contmain'
    },
    id: 'contMain',
    itemId: 'contMain',
    fullscreen: true,
    layout: 'hbox',
    defaultListenerScope: true,

    listeners: {
        resize: 'onContMainResize',
        beforeshow: 'onContMainBeforeShow'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            id: 'contPanel',
            itemId: 'contPanel',
            layout: 'hbox',
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    id: 'contConfig',
                    itemId: 'contConfig',
                    layout: 'card',
                    items: [
                        {
                            xtype: 'toolbar',
                            id: 'toolbarMain',
                            itemId: 'toolbarMain',
                            docked: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btnCreate',
                                    itemId: 'btnCreate',
                                    ui: 'confirm',
                                    iconCls: 'fas fa-plus',
                                    text: 'Agregar',
                                    listeners: {
                                        tap: 'onBtnCreateTap'
                                    }
                                },
                                {
                                    xtype: 'segmentedbutton',
                                    id: 'segBtnConfig',
                                    itemId: 'segBtnConfig',
                                    width: 200,
                                    defaults: {
                                        flex: '1'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnConfigActive',
                                            itemId: 'btnConfigActive',
                                            ui: 'action round',
                                            iconCls: 'fas fa-check-circle',
                                            pressed: true,
                                            text: 'Activos',
                                            value: 'false'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnConfigDelete',
                                            itemId: 'btnConfigDelete',
                                            ui: 'action round',
                                            iconCls: 'fas fa-database',
                                            text: 'Todos',
                                            value: 'true'
                                        }
                                    ],
                                    listeners: {
                                        toggle: 'onSegBtnConfigToggle'
                                    }
                                },
                                {
                                    xtype: 'spacer'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            id: 'contListConfig',
                            itemId: 'contListConfig',
                            scrollable: true,
                            items: [
                                {
                                    xtype: 'container',
                                    id: 'contHeaderConfig',
                                    itemId: 'contHeaderConfig',
                                    html: '<div class="resource-row header-style">     <div class="conf-col-main">CÓDIGO / DESCRIPCIÓN</div>     <div class="col-actions">ACCIONES</div> </div>'
                                },
                                {
                                    xtype: 'dataview',
                                    id: 'dataViewConfig',
                                    itemId: 'dataViewConfig',
                                    itemTpl: [
                                        '<div class="resource-row {[values.is_active ? \'\' : \'user-inactive\']}">',
                                        '',
                                        '  <!-- COLUMNA PRINCIPAL: CÓDIGO + NOMBRE + DESCRIPCIÓN -->',
                                        '  <div class="conf-col-main">',
                                        '    <div class="main-text">',
                                        '      <strong>{cod_configuration}</strong>',
                                        '      <span class="status-inline">',
                                        '        <span class="status-dot {[values.is_active ? \'active\' : \'inactive\']}"></span>',
                                        '        <tpl if="values.is_active">',
                                        '          Activo',
                                        '        <tpl else>',
                                        '          Inactivo',
                                        '        </tpl>',
                                        '      </span>',
                                        '    </div>',
                                        '',
                                        '    <div class="sub-text">',
                                        '      <strong>{name}</strong>',
                                        '    </div>',
                                        '',
                                        '    <div class="sub-text secondary-text">',
                                        '      {description}',
                                        '    </div>',
                                        '  </div>',
                                        '',
                                        '  <!-- ACCIONES -->',
                                        '  <div class="col-actions">',
                                        '    <div class="action-btn view" data-action="view" title="Ver detalles">',
                                        '      <i class="x-fa fas fa-plus"></i>',
                                        '    </div>',
                                        '',
                                        '    <tpl if="values.is_active">',
                                        '      <div class="action-btn deactivate" data-action="deactivate" title="Desactivar">',
                                        '        <i class="x-fa fas fa-ban"></i>',
                                        '      </div>',
                                        '    <tpl else>',
                                        '      <div class="action-btn activate" data-action="activate" title="Activar">',
                                        '        <i class="x-fa fas fa-check"></i>',
                                        '      </div>',
                                        '    </tpl>',
                                        '',
                                        '    <div class="action-btn delete" data-action="delete" title="Eliminar">',
                                        '      <i class="x-fa fas fa-trash"></i>',
                                        '    </div>',
                                        '  </div>',
                                        '',
                                        '</div>'
                                    ],
                                    store: 'storeConfig',
                                    listeners: {
                                        childtap: 'onDataViewConfigChildtap'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'formpanel',
                            isCreate: true,
                            id: 'formConfig',
                            itemId: 'formConfig',
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'cfg-form-title',
                                    id: 'lblCfgTitle',
                                    itemId: 'lblCfgTitle'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'ftCfgCode',
                                    itemId: 'ftCfgCode',
                                    margin: 8,
                                    modelValidation: false,
                                    label: 'Código'
                                },
                                {
                                    xtype: 'combobox',
                                    id: 'cboCfgActive',
                                    itemId: 'cboCfgActive',
                                    margin: 8,
                                    label: 'Estado',
                                    value: true,
                                    editable: false,
                                    store: {
                                        fields: [
                                            'text',
                                            'value'
                                        ],
                                        data: [
                                            {
                                                text: 'Activo',
                                                value: true
                                            },
                                            {
                                                text: 'Inactivo',
                                                value: false
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'ftCfgName',
                                    itemId: 'ftCfgName',
                                    margin: 8,
                                    label: 'Nombre'
                                },
                                {
                                    xtype: 'textareafield',
                                    id: 'ftCfgDesc',
                                    itemId: 'ftCfgDesc',
                                    margin: 8,
                                    label: 'Descripción'
                                },
                                {
                                    xtype: 'toolbar',
                                    id: 'toolbarCfg',
                                    itemId: 'toolbarCfg',
                                    docked: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnConfirm',
                                            itemId: 'btnConfirm',
                                            ui: 'confirm',
                                            iconCls: 'fas fa-check',
                                            text: 'Confirmar',
                                            listeners: {
                                                tap: 'onBtnConfirmTap'
                                            }
                                        },
                                        {
                                            xtype: 'spacer'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnCancel',
                                            itemId: 'btnCancel',
                                            ui: 'decline',
                                            iconCls: 'fas fa-ban',
                                            text: 'Cancelar',
                                            listeners: {
                                                tap: 'onBtnCancelTap'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    id: 'toolbarParam',
                                    itemId: 'toolbarParam',
                                    docked: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnCreateParam',
                                            itemId: 'btnCreateParam',
                                            ui: 'confirm',
                                            iconCls: 'fas fa-plus',
                                            text: 'Agregar',
                                            listeners: {
                                                tap: 'onBtnCreateTap1'
                                            }
                                        },
                                        {
                                            xtype: 'spacer'
                                        },
                                        {
                                            xtype: 'segmentedbutton',
                                            id: 'segBtnParam',
                                            itemId: 'segBtnParam',
                                            width: 200,
                                            defaults: {
                                                flex: '1'
                                            },
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    id: 'btnParamActive',
                                                    itemId: 'btnParamActive',
                                                    ui: 'action round',
                                                    iconCls: 'fas fa-check-circle',
                                                    pressed: true,
                                                    text: 'Activos',
                                                    value: 'false'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'btnParamDelete',
                                                    itemId: 'btnParamDelete',
                                                    ui: 'action round',
                                                    iconCls: 'fas fa-database',
                                                    text: 'Todos',
                                                    value: 'true'
                                                }
                                            ],
                                            listeners: {
                                                toggle: 'onSegBtnParamToggle'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    id: 'contListParam',
                                    itemId: 'contListParam',
                                    scrollable: true,
                                    items: [
                                        {
                                            xtype: 'container',
                                            id: 'contHeaderParam',
                                            itemId: 'contHeaderParam',
                                            html: '<div class="resource-row header-style">     <div class="conf-col-main">PARÁMETRO</div>     <div class="col-actions">ACCIONES</div> </div>'
                                        },
                                        {
                                            xtype: 'dataview',
                                            id: 'dataViewParam',
                                            itemId: 'dataViewParam',
                                            itemTpl: [
                                                '<div class="resource-row {[values.is_active ? \'\' : \'user-inactive\']}">',
                                                '',
                                                '    <div class="conf-col-main">',
                                                '        <div class="main-text">',
                                                '            <strong>{cod_parameter}</strong>',
                                                '            <span class="status-inline">',
                                                '                <span class="status-dot {[values.is_active ? \'active\' : \'inactive\']}"></span>',
                                                '                <tpl if="values.is_active">',
                                                '                    Activo',
                                                '                <tpl else>',
                                                '                    Inactivo',
                                                '                </tpl>',
                                                '            </span>',
                                                '        </div>',
                                                '',
                                                '        <div class="sub-text">',
                                                '            <strong>{description}</strong>',
                                                '        </div>',
                                                '',
                                                '        <div class="sub-text secondary-text">',
                                                '            {value}',
                                                '        </div>',
                                                '    </div>',
                                                '',
                                                '    <div class="col-actions">',
                                                '        <div class="action-btn view" data-action="view" title="Ver detalles">',
                                                '            <i class="x-fa fas fa-eye"></i>',
                                                '        </div>',
                                                '',
                                                '        <tpl if="values.is_active">',
                                                '            <div class="action-btn deactivate" data-action="deactivate" title="Desactivar">',
                                                '                <i class="x-fa fas fa-ban"></i>',
                                                '            </div>',
                                                '        <tpl else>',
                                                '            <div class="action-btn activate" data-action="activate" title="Activar">',
                                                '                <i class="x-fa fas fa-check"></i>',
                                                '            </div>',
                                                '        </tpl>',
                                                '',
                                                '        <div class="action-btn delete" data-action="delete" title="Eliminar">',
                                                '            <i class="x-fa fas fa-trash"></i>',
                                                '        </div>',
                                                '    </div>',
                                                '',
                                                '</div>'
                                            ],
                                            store: 'storeParam',
                                            listeners: {
                                                childtap: 'onDataViewParamChildtap'
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'formpanel',
                            isCreate: true,
                            id: 'formParam',
                            itemId: 'formParam',
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'cfg-form-title',
                                    id: 'lblParamTitle',
                                    itemId: 'lblParamTitle'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'ftParamCode',
                                    itemId: 'ftParamCode',
                                    margin: 8,
                                    modelValidation: false,
                                    label: 'Código'
                                },
                                {
                                    xtype: 'combobox',
                                    id: 'cboParamActive',
                                    itemId: 'cboParamActive',
                                    margin: 8,
                                    label: 'Estado',
                                    value: true,
                                    editable: false,
                                    store: {
                                        fields: [
                                            'text',
                                            'value'
                                        ],
                                        data: [
                                            {
                                                text: 'Activo',
                                                value: true
                                            },
                                            {
                                                text: 'Inactivo',
                                                value: false
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'ftParamValue',
                                    itemId: 'ftParamValue',
                                    margin: 8,
                                    label: 'Valor'
                                },
                                {
                                    xtype: 'textareafield',
                                    id: 'ftParamDesc',
                                    itemId: 'ftParamDesc',
                                    margin: 8,
                                    label: 'Descripción'
                                },
                                {
                                    xtype: 'toolbar',
                                    itemId: 'mytoolbar1',
                                    docked: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnConfirm1',
                                            itemId: 'btnConfirm',
                                            ui: 'confirm',
                                            iconCls: 'fas fa-check',
                                            text: 'Confirmar',
                                            listeners: {
                                                tap: 'onBtnConfirmTap1'
                                            }
                                        },
                                        {
                                            xtype: 'spacer'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnCancel1',
                                            itemId: 'btnCancel',
                                            ui: 'decline',
                                            iconCls: 'fas fa-ban',
                                            text: 'Cancelar',
                                            listeners: {
                                                tap: 'onBtnCancelTap1'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onContMainResize: function(element, info, eOpts) {
        console.log('>>>resizswse');
        console.log(element);

        console.log('>>>info');
        console.log(info);


        let width = info;

        // 1. Log para depurar
            console.log('El ancho actual es:', width);

            // 2. Lógica condicional
            // Importante: Verifica el layout actual para no forzarlo mil veces si no ha cambiado
            var currentLayout = this.getLayout().type;

            if (width < 1000 /*&& currentLayout !== 'vbox'*/) {
                console.log('-> Cambiando a Modo Móvil');
                this.setLayout('hbox');
            }
            else if (width >= 1000 /*&& currentLayout !== 'hbox'*/) {
                console.log('-> Cambiando a Modo Escritorio');
                this.setLayout('vbox');
            }

    },

    onBtnCreateTap: function(button, e, eOpts) {
        /*
        // Buscas el contenedor padre
        var contUser    = Ext.getCmp('contUser'); // Asegúrate de tener reference='contResource'
        var toolbarMain = Ext.getCmp('toolbarMain');

        // Cambias a la vista del formulario (que es el item 1)
        // La animación 'slide' hará que parezca que entras a una nueva página
        contUser.setActiveItem(1);
        toolbarMain.hide();
        */
        var form = Ext.getCmp("formConfig");
        form.isCreate = true;

        this.showForm();
    },

    onSegBtnConfigToggle: function(segmentedbutton, button, isPressed, eOpts) {
        if (!isPressed) return;

        const includeDeleted = (button.getItemId && button.getItemId() === 'btnConfigDelete') || (button.itemId === 'btnConfigDelete');

        // Obtener el store
        const storeConfig = Ext.getStore('storeConfig');

        // Set extra param
        const proxy = storeConfig.getProxy();
        proxy.setExtraParam('show_inactive', includeDeleted ? 'true' : 'false');

        // Regresar a página 1 cuando hay paging
        //if (storeConfig.currentPage) {
           // storeConfig.currentPage = 1;
        //}

        // Recargar
        storeConfig.currentPage = 1;
        storeConfig.load();
    },

    onDataViewConfigChildtap: function(dataview, location, eOpts) {
        // 1. Detectar si el toque fue en un botón de acción
        // Buscamos la clase '.action-btn' en el elemento tocado o sus padres
        var btn = location.event.getTarget('.action-btn');

        if (btn) {
            // 2. Extraer la acción y el registro
            var action = btn.getAttribute('data-action');
            var record = location.record.data;

            // Detenemos la propagación para que no seleccione la fila al tocar el botón
            location.event.stopEvent();

            // 3. Switch Maestro de Acciones
            switch (action) {
                case 'view':
                    console.warn('Tap: view');
                    var form = Ext.getCmp("formConfig");
                    form.isCreate = false;
                    form.configRecord = record;
                    this.showForm();
                    break;

                case 'edit':
                    console.warn('Tap: view');
                    var form = Ext.getCmp("formConfig");
                    form.isCreate = false;
                    form.configRecord = record;
                    this.showForm();
                    break;

                case 'download':
                    console.warn('Tap: download');
                    this.downloadFile(record);
                    break;

                case 'activate':
                    Ext.Msg.show({
                            title: 'Activar  Registro',
                            message: '¿Deseas activar  este registro?',
                            width: 300,
                            closable: false,
                            icon: Ext.Msg.QUESTION,
                            buttons: [
                                { text: 'No', itemId: 'no' },
                                { text: 'Sí, activar', itemId: 'yes', ui: 'action-decline' }
                            ],
                            fn: function (buttonId) {
                                if (buttonId === 'yes') {

                                    var payload = {
                                        id_configuration : record.id_configuration,
                                        is_active        : true
                                    };

                                    appLocal.saveConfig(payload, false);

                                    console.log('Registro desactivado');
                                }
                            }
                        });
                        break;

                case 'deactivate':
                    Ext.Msg.show({
                            title: 'Desactivar Registro',
                            message: '¿Deseas desactivar este registro?',
                            width: 300,
                            closable: false,
                            icon: Ext.Msg.QUESTION,
                            buttons: [
                                { text: 'No', itemId: 'no' },
                                { text: 'Sí, desactivar', itemId: 'yes', ui: 'action-decline' }
                            ],
                            fn: function (buttonId) {
                                if (buttonId === 'yes') {

                                    var payload = {
                                        id_configuration : record.id_configuration,
                                        is_active        : false
                                    };

                                    appLocal.saveConfig(payload, false);

                                    console.log('Registro desactivado');
                                }
                            }
                        });
                        break;

                case 'restore':
                    Ext.Msg.show({
                        title: 'Restaurar Registro',
                        message: '¿Realmente deseas restaurar este registro? Esta acción podría provocar algún error.',
                        width: 300, // Opcional
                        closable: false,
                        icon: Ext.Msg.QUESTION,
                        buttons: [
                            {
                                text: 'No',
                                itemId: 'no'
                            },
                            {
                                text: 'Sí, restaurar',
                                itemId: 'yes',
                                ui: 'action-decline'
                            }
                        ],
                        fn: function (buttonId) {
                            if (buttonId === 'yes') {

                                var idConfig = record.id_configuration;
                                appLocal.restoreConfig(idConfig);

                                console.log('Registro restaurado');
                            }
                        }
                    });
                    break;

                case 'delete':
                    Ext.Msg.show({
                        title: 'Eliminar Registro',
                        message: '¿Realmente deseas eliminar este registro? Esta acción no se puede deshacer.',
                        width: 300,
                        closable: false,
                        icon: Ext.Msg.QUESTION,
                        buttons: [
                            {
                                text: 'No',
                                itemId: 'no'
                            },
                            {
                                text: 'Sí, borrar',
                                itemId: 'yes',
                                ui: 'action-decline'
                            }
                        ],
                        fn: function (buttonId) {
                            if (buttonId === 'yes') {

                                var idConfig = record.id_configuration;
                                appLocal.deleteConfig(idConfig);

                                console.log('Registro eliminado');
                            }
                        }
                    });
                    break;

                default:
                    console.log('Evento no definido');
            }
        }
    },

    onBtnConfirmTap: function(button, e, eOpts) {
        var contMain = Ext.getCmp('contMain');

        var payload = contMain.buildConfigPayload();

        console.info(payload);
        appLocal.saveConfig(payload);
    },

    onBtnCancelTap: function(button, e, eOpts) {
        var contConfig  = Ext.getCmp('contConfig');
        var toolbarMain = Ext.getCmp('toolbarMain');

        contConfig.setActiveItem(0);
        toolbarMain.show();

        this.cleanConfigForm();
    },

    onBtnCreateTap1: function(button, e, eOpts) {
        /*
        // Buscas el contenedor padre
        var contUser    = Ext.getCmp('contUser'); // Asegúrate de tener reference='contResource'
        var toolbarMain = Ext.getCmp('toolbarMain');

        // Cambias a la vista del formulario (que es el item 1)
        // La animación 'slide' hará que parezca que entras a una nueva página
        contUser.setActiveItem(1);
        toolbarMain.hide();
        */
        var form = Ext.getCmp("formParam");
        form.isCreate = true;

        this.showFormParam();
    },

    onSegBtnParamToggle: function(segmentedbutton, button, isPressed, eOpts) {
        if (!isPressed) return;

        const includeDeleted = (button.getItemId && button.getItemId() === 'btnParamDelete') || (button.itemId === 'btnParamDelete');

        console.log('includeDeleted:', includeDeleted);

        // Obtener el store
        const storeConfig = Ext.getStore('storeParam');

        // Set extra param
        const proxy = storeConfig.getProxy();
        proxy.setExtraParam('show_inactive', includeDeleted ? 'true' : 'false');

        // Regresar a página 1 cuando hay paging
        //if (storeConfig.currentPage) {
        // storeConfig.currentPage = 1;
        //}

        // Recargar
        storeConfig.currentPage = 1;
        storeConfig.load();
    },

    onDataViewParamChildtap: function(dataview, location, eOpts) {
        // 1. Detectar si el toque fue en un botón de acción
        // Buscamos la clase '.action-btn' en el elemento tocado o sus padres
        var btn = location.event.getTarget('.action-btn');

        if (btn) {
            // 2. Extraer la acción y el registro
            var action = btn.getAttribute('data-action');
            var record = location.record.data;

            // Detenemos la propagación para que no seleccione la fila al tocar el botón
            location.event.stopEvent();

            // 3. Switch Maestro de Acciones
            switch (action) {
                case 'view':
                    console.warn('Tap: view');
                    var form = Ext.getCmp("formParam");
                    form.isCreate = false;
                    form.paramRecord = record;
                    this.showFormParam();
                    break;

                case 'edit':
                    console.warn('Tap: view');
                    var form = Ext.getCmp("formParam");
                    form.isCreate = false;
                    form.paramRecord = record;
                    this.showFormParam();
                    break;

                case 'download':
                    console.warn('Tap: download');
                    this.downloadFile(record);
                    break;

                case 'activate':
                    Ext.Msg.show({
                            title: 'Activar  Registro',
                            message: '¿Deseas activar  este registro?',
                            width: 300,
                            closable: false,
                            icon: Ext.Msg.QUESTION,
                            buttons: [
                                { text: 'No', itemId: 'no' },
                                { text: 'Sí, activar', itemId: 'yes', ui: 'action-decline' }
                            ],
                            fn: function (buttonId) {
                                if (buttonId === 'yes') {

                                    var payload = {
                                        id_conf_parameter : record.id_conf_parameter,
                                        is_active         : true
                                    };

                                    appLocal.saveParam(payload, false);

                                    console.log('Registro desactivado');
                                }
                            }
                        });
                        break;

                case 'deactivate':
                    Ext.Msg.show({
                            title: 'Desactivar Registro',
                            message: '¿Deseas desactivar este registro?',
                            width: 300,
                            closable: false,
                            icon: Ext.Msg.QUESTION,
                            buttons: [
                                { text: 'No', itemId: 'no' },
                                { text: 'Sí, desactivar', itemId: 'yes', ui: 'action-decline' }
                            ],
                            fn: function (buttonId) {
                                if (buttonId === 'yes') {

                                    var payload = {
                                        id_conf_parameter : record.id_conf_parameter,
                                        is_active         : false
                                    };

                                    appLocal.saveParam(payload, false);

                                    console.log('Registro desactivado');
                                }
                            }
                        });
                        break;

                case 'restore':
                    Ext.Msg.show({
                        title: 'Restaurar Registro',
                        message: '¿Realmente deseas restaurar este registro? Esta acción podría provocar algún error.',
                        width: 300, // Opcional
                        closable: false,
                        icon: Ext.Msg.QUESTION,
                        buttons: [
                            {
                                text: 'No',
                                itemId: 'no'
                            },
                            {
                                text: 'Sí, restaurar',
                                itemId: 'yes',
                                ui: 'action-decline'
                            }
                        ],
                        fn: function (buttonId) {
                            if (buttonId === 'yes') {

                                var idParam = record.id_conf_parameter;
                                appLocal.restoreParam(idParam);

                                console.log('Registro restaurado');
                            }
                        }
                    });
                    break;

                case 'delete':
                    Ext.Msg.show({
                        title: 'Eliminar Registro',
                        message: '¿Realmente deseas eliminar este registro? Esta acción no se puede deshacer.',
                        width: 300,
                        closable: false,
                        icon: Ext.Msg.QUESTION,
                        buttons: [
                            {
                                text: 'No',
                                itemId: 'no'
                            },
                            {
                                text: 'Sí, borrar',
                                itemId: 'yes',
                                ui: 'action-decline'
                            }
                        ],
                        fn: function (buttonId) {
                            if (buttonId === 'yes') {

                                var idParam = record.id_conf_parameter;
                                appLocal.deleteParam(idParam);

                                console.log('Registro eliminado');
                            }
                        }
                    });
                    break;

                default:
                    console.log('Evento no definido');
            }
        }
    },

    onBtnConfirmTap1: function(button, e, eOpts) {
        var contMain = Ext.getCmp('contMain');

        var payload = contMain.buildParamPayload();

        console.info(payload);
        appLocal.saveParam(payload);
    },

    onBtnCancelTap1: function(button, e, eOpts) {
        var contConfig     = Ext.getCmp('contConfig');
        var toolbarMain    = Ext.getCmp('toolbarMain');
        var btnCreateParam = Ext.getCmp('btnCreateParam');

        contConfig.setActiveItem(1);
        btnCreateParam.show();
        //toolbarMain.show();

        this.cleanParamForm();
    },

    onContMainBeforeShow: function(component, eOpts) {
        jsTerian.loadStore('storeUser');
        jsTerian.loadStore('storeRole');
    },

    buildConfigPayload: function() {
        var form     = Ext.getCmp('formConfig');
        var record   = form.configRecord;
        var isCreate = form.isCreate;

        var id_configuration = record ? record.id_configuration : null;

        const payload = {
            id_configuration : id_configuration,
            cod_configuration: jsTerian.readElementValue("ftCfgCode"),
            name             : jsTerian.readElementValue("ftCfgName"),
            description      : jsTerian.readElementValue("ftCfgDesc"),
            is_active        : jsTerian.readElementValue("cboCfgActive")
        };

        // Validaciones
        if (!payload.cod_configuration || String(payload.cod_configuration).trim() === '') {
            jsTerian.toastAlert("El código es obligatorio.", "error");
            return null;
        }

        if (!payload.name || String(payload.name).trim() === '') {
            jsTerian.toastAlert("El nombre es obligatorio.", "error");
            return null;
        }

        // Normalizar
        payload.cod_configuration = String(payload.cod_configuration).trim().toUpperCase();
        payload.name = String(payload.name).trim();

        if (payload.description !== null && payload.description !== undefined) {
            payload.description = String(payload.description).trim();
        }

        // Create / Update
        if (isCreate) {
            delete payload.id_configuration;
        } else {
            if (!payload.id_configuration) {
                jsTerian.toastAlert("No se puede actualizar: falta id_configuration.", "error");
                return null;
            }

            if (!payload.description || payload.description === '') {
                delete payload.description;
            }
        }

        return payload;
    },

    buildParamPayload: function() {
        // Form Config
        var form = Ext.getCmp('formConfig');
        var configRecord = form.configRecord;

        // Form Param
        var form = Ext.getCmp('formParam');
        var record = form.paramRecord;
        var isCreate = form.isCreate;

        var id_conf_parameter = record ? record.id_conf_parameter : null;

        var id_configuration = (configRecord && configRecord.id_configuration) ? configRecord.id_configuration : configRecord.id_configuration;

        const payload = {
          id_conf_parameter: id_conf_parameter,
          id_configuration : id_configuration,
          cod_parameter    : jsTerian.readElementValue("ftParamCode"),
          description      : jsTerian.readElementValue("ftParamDesc"),
          value            : jsTerian.readElementValue("ftParamValue"),
          is_active        : jsTerian.readElementValue("cboParamActive"),
        };

        // Validaciones mínimas
        if (!payload.id_configuration) {
          jsTerian.toastAlert("Falta id_configuration (no se puede guardar el parámetro).", "error");
          return null;
        }

        if (!payload.cod_parameter || String(payload.cod_parameter).trim() === '') {
          jsTerian.toastAlert("El código del parámetro es obligatorio.", "error");
          return null;
        }

        if (!payload.value || String(payload.value).trim() === '') {
          jsTerian.toastAlert("El valor es obligatorio.", "error");
          return null;
        }

        // Normalizar
        payload.cod_parameter = String(payload.cod_parameter).trim().toUpperCase();
        payload.value = String(payload.value).trim();

        if (payload.description !== null && payload.description !== undefined) {
          payload.description = String(payload.description).trim();
        }

        // Create / Update
        if (isCreate) {
          delete payload.id_conf_parameter;

        } else {
          if (!payload.id_conf_parameter) {
            jsTerian.toastAlert("No se puede actualizar: falta id_conf_parameter.", "error");
            return null;
          }

          // Si description viene vacía, no se manda
          if (payload.description === '') delete payload.description;
        }

        return payload;
    },

    showConfig: function(record) {
        const mapping = {
          ftCfgCode   : record.cod_configuration,
          ftCfgName   : record.name,
          ftCfgDesc   : record.description,
          cboCfgActive: record.is_active
          // Auditoría?
        };

        Ext.Object.each(mapping, function(field, value){
          jsTerian.assignElementValue(field, value);
        });
    },

    showParam: function(record) {
        // record
        const mapping = {
          ftParamCode   : record.cod_parameter,
          ftParamDesc   : record.description,
          ftParamValue  : record.value,
          cboParamActive: record.is_active
          // Auditoría no por ahora
        };

        Ext.Object.each(mapping, function(field, value){
          jsTerian.assignElementValue(field, value);
        });
    },

    showForm: function() {
        var contConfig     = Ext.getCmp('contConfig');
        var toolbarMain    = Ext.getCmp('toolbarMain');
        var toolbarCfg     = Ext.getCmp('toolbarCfg');
        var toolbarParam   = Ext.getCmp('toolbarParam');
        var segmentBtn     = Ext.getCmp('segBtnParam');
        var btnCreateParam = Ext.getCmp('btnCreateParam');
        var lblCfgTitle    = Ext.getCmp('lblCfgTitle');
        var contListParam  = Ext.getCmp('contListParam');

        contConfig.setActiveItem(1);
        toolbarMain.hide();

        // Obtener el form y la propiedad isCreate
        var form     = Ext.getCmp("formConfig");
        var isCreate = form.isCreate;
        var record   = form.configRecord;

        if (isCreate) {
            console.log('create');
            segmentBtn.hide();
            btnCreateParam.hide();
            toolbarParam.hide();
            contListParam.hide();

            if (lblCfgTitle) lblCfgTitle.setHtml('Crear configuración');

        } else {
            console.log('update');
            btnCreateParam.show();
            segmentBtn.show();
            toolbarParam.show();
            contListParam.show();

            if (lblCfgTitle) lblCfgTitle.setHtml('Editar configuración');

            // Cargar el store
            jsTerian.loadStore('storeParam',record.id_configuration);

            // Mostrar los datos del record de config
            this.showConfig(record);
        }
    },

    showFormParam: function() {
        var contConfig     = Ext.getCmp('contConfig');
        var toolbarMain    = Ext.getCmp('toolbarMain');
        var segmentBtn     = Ext.getCmp('segBtnParam');
        var btnCreateParam = Ext.getCmp('btnCreateParam');
        var lblParamTitle  = Ext.getCmp('lblParamTitle');

        contConfig.setActiveItem(2);
        toolbarMain.hide();
        btnCreateParam.show();

        // Obtener el form y la propiedad isCreate
        var form     = Ext.getCmp("formParam");
        var isCreate = form.isCreate;
        var record   = form.paramRecord;

        if (isCreate) {
            console.log('create');
            segmentBtn.hide();

            if (lblParamTitle) lblParamTitle.setHtml('Crear parámetro');

        } else {
            console.log('update');

            if (lblParamTitle) lblParamTitle.setHtml('Editar parámetro');

            // Cargar el store
            //jsTerian.loadStore('storeParam',record.id_configuration);

            // Mostrar los datos del record de config
            this.showParam(record);
        }
    },

    showDataView: function() {
        var contUser    = Ext.getCmp('contUser');
        var toolbarMain = Ext.getCmp('toolbarMain');

        contUser.setActiveItem(0);
        toolbarMain.show();
    },

    cleanConfigForm: function() {
        try {
            const mapping = {
                ftCfgCode   : '',
                ftCfgName   : '',
                ftCfgDesc   : '',
                cboCfgActive: true
            };

            Ext.Object.each(mapping, function (field, value) {
                jsTerian.assignElementValue(field, value);
            });

            // Limpiar el store
            var storeParam = Ext.getStore('storeParam');
            if (storeParam) storeParam.removeAll();

        } finally {
            var form = Ext.getCmp("formConfig");
            form.isCreate = true;
            form.configRecord = null;

            // Volver a mostar la segmentación de botones
            var segmentBtn = Ext.getCmp('segBtnConfig');
            segmentBtn.show();
        }
    },

    cleanParamForm: function() {
        try {
            const mapping = {
                ftParamCode   : '',
                ftParamDesc   : '',
                ftParamValue  : '',
                cboParamActive: true
            };

            Ext.Object.each(mapping, function (field, value) {
                jsTerian.assignElementValue(field, value);
            });

        } finally {
            var form = Ext.getCmp("formParam");
            form.isCreate = true;
            form.paramRecord = null;

            // Volver a mostar la segmentación de botones
            var segmentBtn = Ext.getCmp('segBtnParam');
            segmentBtn.show();
        }
    }

});