/*
 * File: app/model/modelContent.js
 *
 * This file was generated by Sencha Architect version 4.3.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damWorkspace.model.modelContent', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],


    fields: [
        {
            name: 'deleted_at'
        },
        {
            name: 'download_url'
        },
        {
            name: 'has_children'
        },
        {
            name: 'has_image'
        },
        {
            name: 'id'
        },
        {
            name: 'is_active'
        },
        {
            name: 'node_type'
        },
        {
            name: 'parent_id'
        },
        {
            name: 'parent_name'
        },
        {
            name: 'preview_url'
        },
        {
            name: 'text'
        },
        {
            name: 'thumbnail_url'
        }
    ]

});