/*
 * File: app/view/contMain.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damCollection.view.contMain', {
    extend: 'Ext.Container',
    alias: 'widget.contMain',

    mixins: [
        'Ext.mixin.Responsive'
    ],
    requires: [
        'damCollection.view.contMainViewModel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.field.ComboBox',
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.form.Panel',
        'Ext.form.FieldSet'
    ],

    config: {
        responsiveConfig: 'responsiveConfig: {\n    \'width < 800\': {\n        layoutMode: \'mobile\' \n    },\n    \'width >= 800\': {\n        layoutMode: \'desktop\'\n    }\n}'
    },

    viewModel: {
        type: 'contmain'
    },
    id: 'contMain',
    itemId: 'contMain',
    fullscreen: true,
    layout: 'hbox',
    defaultListenerScope: true,

    listeners: {
        resize: 'onContMainResize',
        beforeshow: 'onContMainBeforeShow'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            id: 'contPanel',
            itemId: 'contPanel',
            layout: 'hbox',
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    id: 'contNode',
                    itemId: 'contNode',
                    layout: 'card',
                    items: [
                        {
                            xtype: 'toolbar',
                            id: 'toolbarMain',
                            itemId: 'toolbarMain',
                            docked: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btnCreate',
                                    itemId: 'btnCreate',
                                    ui: 'confirm',
                                    iconCls: 'fas fa-plus',
                                    text: 'Agregar',
                                    listeners: {
                                        tap: 'onBtnCreateTap'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {

                                    },
                                    id: 'btnDelete',
                                    itemId: 'btnDelete',
                                    ui: 'decline',
                                    iconCls: 'fas fa-trash',
                                    text: 'Eliminar'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnGoBack',
                                    itemId: 'btnGoBack',
                                    ui: 'action',
                                    iconCls: 'fas fa-backward',
                                    text: 'Regresar',
                                    listeners: {
                                        tap: 'onBtnGoBackTap'
                                    }
                                },
                                {
                                    xtype: 'spacer'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            id: 'contListUser',
                            itemId: 'contListUser',
                            scrollable: true,
                            items: [
                                {
                                    xtype: 'container',
                                    id: 'formView',
                                    itemId: 'formView',
                                    margin: '5 5 8 5',
                                    layout: 'hbox',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            id: 'ftType',
                                            itemId: 'ftType',
                                            margin: 5,
                                            label: 'Tipo',
                                            labelWidth: 70
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 2,
                                            id: 'ftName',
                                            itemId: 'ftName',
                                            margin: 5,
                                            label: 'Nombre',
                                            labelWidth: 70
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            id: 'cboIsActive',
                                            itemId: 'cboIsActive',
                                            margin: 5,
                                            label: 'Estado',
                                            labelWidth: 70,
                                            editable: false,
                                            store: {
                                                fields: [
                                                    'text',
                                                    'value'
                                                ],
                                                data: [
                                                    {
                                                        text: 'Activo',
                                                        value: true
                                                    },
                                                    {
                                                        text: 'Inactivo',
                                                        value: false
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    id: 'contHeaderUser',
                                    itemId: 'contHeaderUser',
                                    html: '<div class="resource-row header-style">     <div class="col-code">CÓDIGO</div>     <div class="col-desc">DESCRIPCIÓN</div>     <div class="col-actions">ACCIONES</div> </div>'
                                },
                                {
                                    xtype: 'dataview',
                                    id: 'dataViewUser',
                                    itemId: 'dataViewUser',
                                    emptyText: 'Este elemento no tiene hijos asignados',
                                    itemTpl: [
                                        '<div class="resource-row {[values.is_active ? \'\' : \'user-inactive\']}">',
                                        '',
                                        '    <div class="col-desc">',
                                        '        <div class="main-text">',
                                        '            <span class="status-dot {[values.is_active ? \'active\' : \'inactive\']}"></span>',
                                        '            <span class="text-bold">{text}</span>',
                                        '',
                                        '            <tpl if="values.has_children">',
                                        '                <span class="role-badge" style="margin-left:8px;">Tiene hijos</span>',
                                        '            </tpl>',
                                        '        </div>',
                                        '',
                                        '        <div class="sub-text">',
                                        '            <tpl if="values.node_type === \'tab\'">',
                                        '                {[values.short_description || \'—\']}',
                                        '                <tpl if="values.sort_order">',
                                        '                    <br><span class="role-badge">Posición: {sort_order}</span>',
                                        '                </tpl>',
                                        '                <tpl if="values.id_asset_type">',
                                        '                    <span class="role-badge">Tipo Carpeta: {asset_type_name}</span>',
                                        '                </tpl>',
                                        '            </tpl>',
                                        '',
                                        '            <tpl if="values.node_type === \'resource\'">',
                                        '                {[values.description || \'—\']}',
                                        '            </tpl>',
                                        '',
                                        '            <tpl if="values.node_type === \'collection\'">',
                                        '                {[values.description || \'—\']}',
                                        '            </tpl>',
                                        '        </div>',
                                        '    </div>',
                                        '    ',
                                        '    <div class="col-code">',
                                        '        <div class="text-bold">#{node_type}</div>',
                                        '        <div class="role-badge">Padre: {[values.parent_name || values.parent_id || \'—\']}</div>',
                                        '',
                                        '        <tpl if="values.node_type === \'resource\'">',
                                        '            <div class="role-badge">Code: {[values.code || \'—\']}</div>',
                                        '        </tpl>',
                                        '',
                                        '        <tpl if="values.node_type === \'tab\'">',
                                        '            <div class="role-badge">Tab: {[values.tab_code || \'—\']}</div>',
                                        '        </tpl>',
                                        '',
                                        '        <tpl if="values.node_type === \'collection\'">',
                                        '            <div class="role-badge">Id: {[values.id_collection || \'—\']}</div>',
                                        '        </tpl>',
                                        '    </div>',
                                        '',
                                        '    <div class="col-actions">',
                                        '        <div class="action-btn view" data-action="view" title="Ver Detalles">',
                                        '            <i class="x-fa fas fa-eye"></i>',
                                        '        </div>',
                                        '',
                                        '        <div class="action-btn edit" data-action="edit" title="Editar Usuario">',
                                        '            <i class="x-fa fas fa-pen"></i>',
                                        '        </div>',
                                        '',
                                        '        <div class="action-btn delete" data-action="delete" title="Desactivar/Borrar">',
                                        '            <i class="x-fa fas fa-trash"></i>',
                                        '        </div>',
                                        '    </div>',
                                        '</div>'
                                    ],
                                    store: 'storeNode',
                                    listeners: {
                                        childtap: 'onDataViewUserChildtap'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'formpanel',
                            isCreate: true,
                            id: 'formNode',
                            itemId: 'formNode',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: '<b>Contexto</b>',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'ftParentName',
                                            itemId: 'ftParentName',
                                            margin: 8,
                                            label: 'Padre',
                                            editable: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'ftParentId',
                                            itemId: 'ftParentId',
                                            margin: 8,
                                            label: 'Padre Id',
                                            editable: false
                                        },
                                        {
                                            xtype: 'selectfield',
                                            id: 'cboNodeType',
                                            itemId: 'cboNodeType',
                                            margin: 8,
                                            label: 'Tipo Nodo',
                                            listeners: {
                                                change: 'onCboNodeTypeChange'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    id: 'fsCollection',
                                    itemId: 'fsCollection',
                                    title: '<b>Datos Generales - Colección</b>',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'ftColName',
                                            itemId: 'ftColName',
                                            margin: 8,
                                            label: 'Nombre'
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'ftColDesc',
                                            itemId: 'ftColDesc',
                                            margin: 8,
                                            label: 'Descripcion'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    id: 'fsResource',
                                    itemId: 'fsResource',
                                    title: '<b>Datos Generales - Recurso</b>',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'ftResCode',
                                            itemId: 'ftResCode',
                                            margin: 8,
                                            label: 'Code Resource'
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'ftResDesc',
                                            itemId: 'ftResDesc',
                                            margin: 8,
                                            label: 'Desc Corta'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    id: 'fsTab',
                                    itemId: 'fsTab',
                                    title: '<b>Datos Generales  - Pestaña</b>',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'ftTabName',
                                            itemId: 'ftTabName',
                                            margin: 8,
                                            label: 'Nombre'
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'ftTabCode',
                                            itemId: 'ftTabCode',
                                            margin: 8,
                                            label: 'Código'
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'ftTabShortDesc',
                                            itemId: 'ftTabShortDesc',
                                            margin: 8,
                                            label: 'Desc Corta'
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'ftTabSortOrder',
                                            itemId: 'ftTabSortOrder',
                                            margin: 8,
                                            label: 'Orden'
                                        },
                                        {
                                            xtype: 'selectfield',
                                            id: 'cboTabAssetType',
                                            itemId: 'cboTabAssetType',
                                            margin: 8,
                                            label: 'Tipo Archivo',
                                            store: {
                                                fields: [
                                                    'text',
                                                    'value'
                                                ],
                                                data: [
                                                    {
                                                        text: 'Imágenes',
                                                        value: 'IMAGE'
                                                    },
                                                    {
                                                        text: 'Videos',
                                                        value: 'VIDEO'
                                                    },
                                                    {
                                                        text: 'Documentos',
                                                        value: 'DOC'
                                                    },
                                                    {
                                                        text: 'Otros',
                                                        value: 'ANY'
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    title: '<b>Estado</b>',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'cboAdmIsActive',
                                            itemId: 'cboAdmIsActive',
                                            margin: 8,
                                            label: 'Estado'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    itemId: 'mytoolbar1',
                                    docked: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnConfirm',
                                            itemId: 'btnConfirm',
                                            ui: 'confirm',
                                            text: 'Confirmar',
                                            listeners: {
                                                tap: 'onBtnConfirmTap'
                                            }
                                        },
                                        {
                                            xtype: 'spacer'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnCancel',
                                            itemId: 'btnCancel',
                                            ui: 'decline',
                                            text: 'Cancelar',
                                            listeners: {
                                                tap: 'onBtnCancelTap'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onContMainResize: function(element, info, eOpts) {
        console.log('>>>resizswse');
        console.log(element);

        console.log('>>>info');
        console.log(info);


        let width = info;

        // 1. Log para depurar
            console.log('El ancho actual es:', width);

            // 2. Lógica condicional
            // Importante: Verifica el layout actual para no forzarlo mil veces si no ha cambiado
            var currentLayout = this.getLayout().type;

            if (width < 1000 /*&& currentLayout !== 'vbox'*/) {
                console.log('-> Cambiando a Modo Móvil');
                this.setLayout('hbox');
            }
            else if (width >= 1000 /*&& currentLayout !== 'hbox'*/) {
                console.log('-> Cambiando a Modo Escritorio');
                this.setLayout('vbox');
            }

    },

    onBtnCreateTap: function(button, e, eOpts) {
        /*
        // Buscas el contenedor padre
        var contUser    = Ext.getCmp('contUser'); // Asegúrate de tener reference='contResource'
        var toolbarMain = Ext.getCmp('toolbarMain');

        // Cambias a la vista del formulario (que es el item 1)
        // La animación 'slide' hará que parezca que entras a una nueva página
        contUser.setActiveItem(1);
        toolbarMain.hide();
        */
        var form = Ext.getCmp("formRecord");
        //form.isCreate = true;

        this.showForm('create', null);
    },

    onBtnGoBackTap: function(button, e, eOpts) {
        appLocal.goBackTree('storeNode');
        console.log('treeState:', appLocal.treeState);
        console.log('treeNav:', appLocal.treeNav);
    },

    onDataViewUserChildtap: function(dataview, location, eOpts) {
        // 1. Detectar si el toque fue en un botón de acción
            // Buscamos la clase '.action-btn' en el elemento tocado o sus padres
            var btn = location.event.getTarget('.action-btn');

            if (btn) {
                // 2. Extraer la acción y el registro
                var action = btn.getAttribute('data-action');
                //var record = location.record.data;
                //const data = record.getData ? record.getData() : record;
                var record = location.record;
                var data   = record ? (record.getData ? record.getData() : record) : null;


                // Detenemos la propagación para que no seleccione la fila al tocar el botón
                location.event.stopEvent();

                // 3. Switch Maestro de Acciones
                switch (action) {
                    case 'view':
                        // Obtener el record
                        //const data = record.getData ? record.getData() : record;
                        const canNavigate = (data.node_type === 'collection' || data.node_type === 'resource'); //&& data.has_children;

                        // Sino se puede navergar lanzar una alerta
                        if (!canNavigate) {

                            Ext.toast({
                                timeout: 2500,
                                cls: 'toast-clean',
                                message: `
                                    <div style="
                                    background:#FFF3CD;
                                    color:#856404;
                                    padding:10px 12px;
                                    border-radius:14px;
                                    font-weight:600;
                                    ">
                                    ⚠️ Esta pestaña no tiene contenido navegable
                                    </div>
                                    `
                            });
                            return;
                        }

                        // Guardar el record en el formView
                        var form = Ext.getCmp("formView");
                        form.nodeRecord = record;

                        // Lanzar la función para pintar la información
                        this.showFormView(record);
                        break;

                    case 'edit':
                        console.warn('Tap: view');
                        //var data = record.getData ? record.getData() : record;

                        // Mostrar form en modo EDIT (porque estás viendo info del nodo)
                        this.showForm('edit', record);

                        // Si en edit también quieres navegar (sin importar has_children), déjalo así:
                        if (data.node_type === 'collection' || data.node_type === 'resource') {
                            var nodeId = data.id || data.node_id || data._id;
                            if (nodeId) {
                                //appLocal.loadTreeChildren('storeNode', nodeId, { pushHistory: true });
                            }
                        }
                        break;

                    case 'delete':
                        Ext.Msg.show({
                            title: 'Eliminar Registro',
                            message: '¿Realmente deseas eliminar este registro? Esta acción no se puede deshacer.',
                            width: 300, // Opcional
                            closable: false,
                            icon: Ext.Msg.QUESTION,
                            buttons: [
                                {
                                    text: 'No',
                                    itemId: 'no'
                                },
                                {
                                    text: 'Sí, borrar',
                                    itemId: 'yes',
                                    ui: 'action-decline' // En Modern, esto suele poner el botón en rojo
                                }
                            ],
                            fn: function (buttonId) {
                                if (buttonId === 'yes') {

                                    var idUser = record.id_user;
                                    appLocal.deleteUser(idUser);

                                    console.log('Registro eliminado');
                                }
                            }
                        });
                        break;

                    default:
                        console.log('Evento no definido');
                }
            }
    },

    onCboNodeTypeChange: function(selectfield, newValue, oldValue, eOpts) {
        var contMain =  Ext.getCmp('contMain');
        var form = Ext.getCmp('formNode');
        this.configureNodeForm(form, newValue, 'create', { parentId: form.parentId });
        this.clearNodeForm(form, { keepType: true, keepActive: true });
    },

    onBtnConfirmTap: function(button, e, eOpts) {
        var form = Ext.getCmp('formNode');

        var payload = this.buildPayload(form);

        var err = this.validateCreatePayload(payload);
        if (err) {
            Ext.toast(err);
            return;
        }

        appLocal.saveNode();

        return;
    },

    onBtnCancelTap: function(button, e, eOpts) {
        var contNode    = Ext.getCmp('contNode');
        var toolbarMain = Ext.getCmp('toolbarMain');

        contNode.setActiveItem(0);
        toolbarMain.show();

        //this.cleanForm();
    },

    onContMainBeforeShow: function(component, eOpts) {
        jsTerian.loadStore('storeUser');
        jsTerian.loadStore('storeRole');
    },

    buildPayload: function() {
        // Obtener los valores del contexto
        var nodeType = (jsTerian.readElementValue('cboNodeType') || '').trim();

        if (!nodeType) {
            nodeType = (jsTerian.readElementValue('hfNodeTypeSelected') || '').trim();
        }
        // Nodo actual
        var parentId = (jsTerian.readElementValue('ftParentId') || '').trim();
        if (!parentId) parentId = appLocal.getCurrentNodeId();

        var data = {};

        if (nodeType === 'collection') {
            data.name = (jsTerian.readElementValue('ftColName') || '').trim();
            var desc = (jsTerian.readElementValue('ftColDesc') || '').trim();
            data.description = desc ? desc : null;
        }

        if (nodeType === 'resource') {
            data.code = (jsTerian.readElementValue('ftResCode') || '').trim();
            data.description = (jsTerian.readElementValue('ftResDesc') || '').trim();
        }

        if (nodeType === 'tab') {
            data.name = (jsTerian.readElementValue('ftTabName') || '').trim();
            data.tab_code = (jsTerian.readElementValue('ftTabCode') || '').trim();
            var shortDesc = (jsTerian.readElementValue('ftTabShortDesc') || '').trim();
            data.short_description = shortDesc ? shortDesc : null;
            var sortOrderRaw = jsTerian.readElementValue('ftTabSortOrder');
            var sortOrder = parseInt(sortOrderRaw, 10); data.sort_order = isNaN(sortOrder) ? 1 : sortOrder;
            data.asset_type_code = (jsTerian.readElementValue('cboTabAssetType') || '').trim();
        }

        return {
            node_type: nodeType,
            parent_id: parentId,
            data: data
        };
    },

    validateCreatePayload: function(payload) {
        // Funcion test: sirve para validar que el payload venga completo
        var t = payload.node_type;
        var d = payload.data || {};

        if (t === 'collection' && !d.name) return 'Falta nombre de colección';
        if (t === 'resource' && (!d.code || !d.description)) return 'Falta code o descripción del recurso';
        if (t === 'tab' && (!d.name || !d.tab_code || !d.asset_type_code)) return 'Falta name/tab_code/asset_type_code';
        if (!payload.parent_id) return 'No se detectó el nodo padre';

        return null;
    },

    configureNodeForm: function(form, nodeType, mode, ctx) {
        const fsCollection = form.down('#fsCollection');
        const fsResource   = form.down('#fsResource');
        const fsTab        = form.down('#fsTab');
        const cboNodeType  = form.down('#cboNodeType');

        // Modo
        form.isCreate = (mode === 'create');

        // Tipo visible: en create se puede elegir; en edit solo se muestra (disabled)
        if (cboNodeType) {
            cboNodeType.setHidden(false);
            cboNodeType.setDisabled(mode !== 'create');
            cboNodeType.setValue(nodeType);
        }

        // Mostrar solo la sección correspondiente
        if (fsCollection) fsCollection.setHidden(nodeType !== 'collection');
        if (fsResource)   fsResource.setHidden(nodeType !== 'resource');
        if (fsTab)        fsTab.setHidden(nodeType !== 'tab');

        // Nombre del padre)
        if (ctx && ctx.parent_name) {
            const ft = form.down('#ftParentName');
            if (ft) ft.setValue(ctx.parent_name);
        }

        // Limpiar secciones
        const resetGroup = function(group) {
            if (!group) return;
            group.items.each(function(f){
                if (f && f.reset) f.reset();
            });
        };

        if (nodeType !== 'collection') resetGroup(fsCollection);
        if (nodeType !== 'resource')   resetGroup(fsResource);
        if (nodeType !== 'tab')        resetGroup(fsTab);
    },

    showForm: function(mode, record) {
        // Referencia a la ventana
        var me = this;

        // Obtener componentes
        var contNode    = Ext.getCmp('contNode');
        var toolbarMain = Ext.getCmp('toolbarMain');
        var form        = Ext.getCmp('formNode');

        // Cambiar la vista
        contNode.setActiveItem(1);
        toolbarMain.hide();

        // Normalizar record
        var data = record ? (record.getData ? record.getData() : record) : null;

        // Guardar estado en el form
        form.isCreate  = (mode === 'create');
        form.nodeRecord = data || null;

        // Contexto, nodo actual del arbol (padre)
        var parentId = appLocal.getCurrentNodeId();
        form.parentId = parentId;

        // Mostrar el padre
        form.down('#ftParentId').setValue(parentId);
        var ftParent = form.down('#ftParentName');
        if (ftParent) {
            ftParent.setValue(appLocal.getCurrentBreadcrumb({ sep: ' / ' }));
        }

        // Editar registro
        if (mode === 'edit' && data) {
            var nodeType = data.node_type;

            var cboType = form.down('#cboNodeType');
            if (cboType) {
                // Store mínimo para que el combo pueda mostrar el texto en EDIT
                cboType.setStore({
                    fields: ['text', 'value'],
                    data: [{
                        text : (nodeType === 'collection' ? 'Colección'
                              : nodeType === 'resource'   ? 'Recurso'
                              : 'Pestaña'),
                        value: nodeType
                    }]
                });

                // Asegura que se vea y que NO se pueda cambiar
                cboType.setHidden(false);
                cboType.setDisabled(true);

                // Setea el value (ya con store, sí mostrará el display)
                cboType.setValue(nodeType);
            }

            // Configurar form y deja visible el tipo de nodo (bloqueado)
            this.configureNodeForm(form, nodeType, 'edit', {
                parent_name: appLocal.getCurrentBreadcrumb({ sep: ' / ' })
            });

            // Llenar campos del record
            this.fillNodeForm(form, data);

            return;
        }

        // Crear registro

        // Obtener los tipos permitidos usando al padre actual
        var allowed = appLocal.getCreateOptions(parentId);
        if (!allowed || allowed.length === 0) {
            console.log('Aquí no puedes crear hijos');
            return;
        }

        // Cargar las opciones en el select
        var cboType = form.down('#cboNodeType');
        if (cboType) {
            cboType.setHidden(false);
            cboType.setDisabled(false);

            // Cargar store
            cboType.setStore({
                fields: ['text', 'value'],
                data: allowed.map(function(v){
                    if (typeof v === 'string') {
                        return {
                            text: (v === 'collection' ? 'Colección' : v === 'resource' ? 'Recurso' : 'Pestaña'),
                            value: v
                        };
                    }
                    return v;
                })
            });

            // Seleccionar el primero por default, suspender eventos para no hacer un ciclo
            cboType.suspendEvents(false);
            cboType.setValue(allowed[0].value || allowed[0]);
            cboType.resumeEvents();

            // Listener change: cambia la seccion visible y limpia los campos
            if (!cboType._hasNodeTypeListener) {
                cboType.on('change', function(field, newVal) {

                    me.configureNodeForm(form, newVal, 'create', {
                        parent_name: appLocal.getCurrentBreadcrumb({ sep: ' / ' })
                    });
                    me.clearNodeForm({ keepType: true, keepActive: true });
                });

                cboType._hasNodeTypeListener = true;
            }
        }

        // Tipo inicial
        var nodeType = cboType ? cboType.getValue() : (allowed[0].value || allowed[0]);

        // Configurar form y limpiar campos
        me.configureNodeForm(form, nodeType, 'create', {
            parent_name: appLocal.getCurrentBreadcrumb({ sep: ' / ' })
        });

        me.clearNodeForm({ keepType: true, keepActive: true });
    },

    showDataView: function() {
        var contUser    = Ext.getCmp('contUser');
        var toolbarMain = Ext.getCmp('toolbarMain');

        contUser.setActiveItem(0);
        toolbarMain.show();
    },

    cleanForm: function() {
        try {
            // Proceso para mapear los datos
            const mapping = {
                cboNodeType   : '',
                ftColName     : '',
                ftColDesc     : '',
                ftResCode     : '',
                ftResDesc     : '',
                ftTabName     : '',
                ftTabCode     : '',
                ftTabShortDesc: '',
                ftTabSortOrder   : '',
                cboTabAssetType  : '',
                cboAdmIsActive: '',
            };
            Ext.Object.each(mapping, function(field, value){
                jsTerian.assignElementValue(field, value);
            });

            // Punto para cargar el store
        }
        finally {
            //var form = Ext.getCmp("formUser");
            //form.isCreate = true;
        }
    },

    showFormView: function(record) {
        // Obtener el record
        const data = record.getData ? record.getData() : record;

        // Cache del nodo abierto
        appLocal.nodeCache = appLocal.nodeCache || {};
        var nodeId = data.id || data.node_id || data._id;
        appLocal.nodeCache[nodeId] = data;

        // Llenar el form con el nodo seleccionado
        this.fillForm(data);

        // Navegar
        if (data.node_type === 'collection' || data.node_type === 'resource') {
            appLocal.loadTreeChildren('storeNode', data.id, { pushHistory: true });
        }
    },

    cleanFormView: function() {
        jsTerian.assignElementValue('ftType', '');
        jsTerian.assignElementValue('ftName', '');
        jsTerian.assignElementValue('cboIsActive', true);
    },

    fillForm: function(data) {
        const mapping = {
            ftType     : data.node_type,
            ftName     : data.name ? data.name : data.description,
            cboIsActive: data.is_active,
        };

        Ext.Object.each(mapping, function(field, value){
            jsTerian.assignElementValue(field, value);
        });
    },

    fillNodeForm: function(form, data) {
        if (!data) return;

        // Limpiar
        var trim = function(v){
            return (v === null || v === undefined) ? '' : String(v).trim();
        };

        // Tipo y estado
        var nodeType = trim(data.node_type); // 'collection' | 'resource' | 'tab'

        // Muestra el tipo en el combo
        try { jsTerian.assignElementValue('cboNodeType', nodeType); } catch(e){}

        // Activo/inactivo
        if (data.is_active !== undefined) {
            try { jsTerian.assignElementValue('cboAdmIsActive', !!data.is_active); } catch(e){}
            try { jsTerian.assignElementValue('cboIsActive', !!data.is_active); } catch(e){}
        }

        // Padre
        if (data.parent_id || data.parentId) {
            try { jsTerian.assignElementValue('ftParentId', trim(data.parent_id || data.parentId)); } catch(e){}
        }

        // Collection
        if (nodeType === 'collection') {
            // Algunos backends usan name/description, otros name/short_description
            jsTerian.assignElementValue('ftColName', trim(data.name));
            jsTerian.assignElementValue('ftColDesc', trim(data.description) || trim(data.short_description) || '');
            return;
        }

        // Rresource
        if (nodeType === 'resource') {
            // Puede venir como code/description o code/name dependiendo tu API
            jsTerian.assignElementValue('ftResCode', trim(data.code));
            jsTerian.assignElementValue('ftResDesc', trim(data.description) || trim(data.name) || '');
            return;
        }

        // Tab
        if (nodeType === 'tab') {
            jsTerian.assignElementValue('ftTabName', trim(data.name));
            jsTerian.assignElementValue('ftTabCode', trim(data.tab_code));
            jsTerian.assignElementValue('ftTabShortDesc', trim(data.short_description));

            // sort_order default 1
            var sort = data.sort_order;
            if (sort === null || sort === undefined || sort === '') sort = 1;
            jsTerian.assignElementValue('ftTabSortOrder', sort);

            // asset_type_code (combo)
            jsTerian.assignElementValue('cboTabAssetType', trim(data.asset_type_code));
            return;
        }

        // debug
        //console.warn('[fillNodeForm] node_type desconocido:', nodeType, data);
    },

    clearNodeForm: function(opts) {
        opts = opts || {};
        const keepType   = (opts.keepType !== false);
        const keepActive = (opts.keepActive !== false);

        try {
            const mapping = {
                // Collection
                ftColName: '',
                ftColDesc: '',

                // Resource
                ftResCode: '',
                ftResDesc: '',

                // Tab
                ftTabName      : '',
                ftTabCode      : '',
                ftTabShortDesc : '',
                ftTabSortOrder : 1,
                cboTabAssetType: null,

                // Estado
                cboAdmIsActive: keepActive ? true : null
            };

            if (!keepType) {
                mapping.cboNodeType = null;
            }

            Ext.Object.each(mapping, function(field, value) {
                try {
                    jsTerian.assignElementValue(field, value);
                } catch (e) {}
            });
        }
        finally {
            console.log('[FORM] clearNodeForm', { keepType, keepActive });
        }

    }

});