/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'modelResource'
    ],
    stores: [
        'storeResource'
    ],
    views: [
        'contMain'
    ],
    name: 'damResource',

    launch: function() {
        Ext.create('damResource.view.contMain', {fullscreen: true});
        appLocal = this.getApplication();
    },

    previewAsset: function(record) {
        var me = this,
            type = record.get('file_type').toLowerCase(),
            url = record.get('url'), // Asegúrate de tener la URL real del archivo
            nombre = record.get('name'),
            contentItem;

        console.log('previewAsset - type',type);

        // 1. Determinar qué componente usar según el tipo
        switch (type) {
            case 'mp4':
            case 'mov':
            case 'video':
                contentItem = {
                    xtype: 'video',
                    url: url,
                    posterUrl: record.get('thumbnail_url'), // Imagen previa
                    autoResume: true
                };
                break;

            case 'jpg':
            case 'png':
            case 'image':
                contentItem = {
                    xtype: 'image',
                    src: url,
                    mode: 'img', // Para que mantenga proporciones
                    style: 'background-size: contain;'
                };
                break;

            case 'pdf':
                // Los PDF se ven mejor en un iframe
                contentItem = {
                    xtype: 'container',
                    html: '<iframe src="' + url + '" width="100%" height="100%" style="border: none;"></iframe>'
                };
                break;

            case 'docx':
            case 'xlsx':
            case 'pptx':
                // Para Office usamos el visor oficial de Microsoft (gratuito para web)
                var officeUrl = 'https://view.officeapps.live.com/op/view.aspx?src=' + encodeURIComponent(url);
                contentItem = {
                    xtype: 'container',
                    html: '<iframe src="' + officeUrl + '" width="100%" height="100%" style="border: none;"></iframe>'
                };
                break;

            default:
                Ext.Msg.alert('Aviso', 'No hay vista previa disponible para este tipo de archivo.');
                return;
        }

        // 2. Crear y mostrar el Diálogo (Modal)
        var dialog = Ext.create('Ext.Dialog', {
            title: nombre,
            closable: true,
            maximizable: true,
            width: '90%',
            height: '90%',
            layout: 'fit', // El contenido ocupará todo el modal
            items: [contentItem]
        });

        dialog.show();
    }

});
