/*
 * File: app/view/contMain.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('basicUser.view.contMain', {
    extend: 'Ext.Container',
    alias: 'widget.contMain',

    mixins: [
        'Ext.mixin.Responsive'
    ],
    requires: [
        'basicUser.view.contMainViewModel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.form.Panel',
        'Ext.Label',
        'Ext.field.ComboBox'
    ],

    config: {
        responsiveConfig: 'responsiveConfig: {\n    \'width < 800\': {\n        layoutMode: \'mobile\' \n    },\n    \'width >= 800\': {\n        layoutMode: \'desktop\'\n    }\n}'
    },

    viewModel: {
        type: 'contmain'
    },
    id: 'contMain',
    itemId: 'contMain',
    fullscreen: true,
    layout: 'hbox',
    defaultListenerScope: true,

    listeners: {
        resize: 'onContMainResize',
        beforeshow: 'onContMainBeforeShow'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            id: 'contPanel',
            itemId: 'contPanel',
            layout: 'hbox',
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    id: 'contUser',
                    itemId: 'contUser',
                    layout: 'card',
                    items: [
                        {
                            xtype: 'toolbar',
                            id: 'toolbarMain',
                            itemId: 'toolbarMain',
                            docked: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {

                                    },
                                    id: 'btnCreate',
                                    itemId: 'btnCreate',
                                    ui: 'confirm',
                                    iconCls: 'fas fa-plus',
                                    text: 'Agregar',
                                    listeners: {
                                        tap: 'onBtnCreateTap'
                                    }
                                },
                                {
                                    xtype: 'spacer'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            id: 'contListUser',
                            itemId: 'contListUser',
                            scrollable: true,
                            items: [
                                {
                                    xtype: 'container',
                                    id: 'contHeaderUser',
                                    itemId: 'contHeaderUser',
                                    html: '<div class="resource-row header-style">         <div class="col-desc">USUARIO</div>    <div class="col-code">CÓDIGO</div>  <div class="col-actions">ACCIONES</div> </div>'
                                },
                                {
                                    xtype: 'dataview',
                                    id: 'dataViewUser',
                                    itemId: 'dataViewUser',
                                    itemTpl: [
                                        '<div class="resource-row {[values.is_active ? \'\' : \'user-inactive\']}">',
                                        '    ',
                                        '    <div class="col-desc">',
                                        '        <div class="main-text text-bold">',
                                        '            <span class=" status-dot {[values.is_active ? \'active\' : \'inactive\']}"></span>',
                                        '            {first_name} {paternal_last_name} {maternal_last_name}',
                                        '        </div>',
                                        '        <div class="sub-text">',
                                        '            <i class="x-fa fas fa-envelope tiny-icon"></i> {email} <br>',
                                        '            <i class="x-fa fas fa-phone tiny-icon"></i> {phone}',
                                        '        </div>',
                                        '    </div>',
                                        '    <div class="col-code">',
                                        '        <div class="text-bold">{cat_role.role_name}</div>',
                                        '        <div class="role-badge">UserId: {id_user}</div>',
                                        '    </div>',
                                        '    ',
                                        '',
                                        '    <div class="col-actions">',
                                        '        <div class="action-btn view" data-action="view" title="Ver Detalles">',
                                        '            <i class="x-fa fas fa-eye"></i>',
                                        '        </div>',
                                        '        ',
                                        '        <div class="action-btn edit" data-action="edit" title="Editar Usuario">',
                                        '            <i class="x-fa fas fa-pen"></i>',
                                        '        </div>',
                                        '',
                                        '        <!--',
                                        '        <div class="action-btn email" data-action="email" title="Enviar Correo">',
                                        '            <i class="x-fa fas fa-envelope"></i>',
                                        '        </div>',
                                        '        -->',
                                        '',
                                        '        <!--',
                                        '        <div class="action-btn whatsapp" data-action="whatsapp" title="Contactar por WhatsApp">',
                                        '            <i class="x-fa fas fa-whatsapp"></i>',
                                        '        </div>',
                                        '        -->',
                                        '        ',
                                        '',
                                        '        <div class="action-btn delete" data-action="delete" title="Desactivar/Borrar">',
                                        '            <i class="x-fa fas fa-trash"></i>',
                                        '        </div>',
                                        '    </div>',
                                        '</div>'
                                    ],
                                    store: 'storeUser',
                                    listeners: {
                                        childtap: 'onDataViewUserChildtap'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'formpanel',
                            isCreate: true,
                            cls: 'user-form',
                            id: 'formUser',
                            itemId: 'formUser',
                            padding: 4,
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'user-form-title',
                                    id: 'lblUserTitle',
                                    itemId: 'lblUserTitle'
                                },
                                {
                                    xtype: 'textfield',
                                    validators: function(value) {
                                        if (!value || !value.trim()) {
                                            return 'El correo es obligatorio';
                                        }

                                        var emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
                                        return emailRegex.test(value) ? true : 'Ingresa un correo válido';
                                    },
                                    id: 'ftUserEmail',
                                    itemId: 'ftUserEmail',
                                    margin: 8,
                                    errorTarget: 'under',
                                    label: 'Email',
                                    required: true,
                                    requiredMessage: 'Campo requerido'
                                },
                                {
                                    xtype: 'textfield',
                                    validators: function(value) {
                                        var form = Ext.getCmp('formUser');
                                        var isCreate = form ? form.isCreate : true;
                                        var v = value === null ? '' : String(value).trim();

                                        if (isCreate && !v) {
                                            return 'La contraseña es obligatoria';
                                        }

                                        if (v && v.length < 6) {
                                            return 'La contraseña debe tener al menos 6 caracteres';
                                        }

                                        return true;
                                    },
                                    id: 'ftUserPassword',
                                    itemId: 'ftUserPassword',
                                    margin: 8,
                                    errorTarget: 'under',
                                    label: 'Password',
                                    required: true,
                                    requiredMessage: 'Campo requerido',
                                    inputType: 'password'
                                },
                                {
                                    xtype: 'component',
                                    cls: 'field-hint',
                                    id: 'cmpPasswordHint',
                                    itemId: 'cmpPasswordHint'
                                },
                                {
                                    xtype: 'combobox',
                                    validators: function(value) {
                                        return value ? true : 'Selecciona un rol';
                                    },
                                    id: 'cboUserRole',
                                    itemId: 'cboUserRole',
                                    margin: 8,
                                    errorTarget: 'under',
                                    label: 'Role',
                                    required: true,
                                    requiredMessage: 'Campo requerido',
                                    editable: false,
                                    displayField: 'name',
                                    store: 'storeRole',
                                    valueField: 'code'
                                },
                                {
                                    xtype: 'textfield',
                                    validators: function(value) {
                                        var v = (value || '').trim();

                                        if (!v) {
                                            return 'Este campo es obligatorio';
                                        }

                                        var regex = /^[A-Za-zÁÉÍÓÚáéíóúÑñÜü' -]+$/;

                                        if (!regex.test(v)) {
                                            return 'Solo se permiten letras, espacios, guiones y apóstrofes';
                                        }

                                        return true;
                                    },
                                    id: 'ftUserFirstName',
                                    itemId: 'ftUserFirstName',
                                    margin: 8,
                                    errorTarget: 'under',
                                    label: 'Nombre',
                                    required: true,
                                    requiredMessage: 'Campo requerido'
                                },
                                {
                                    xtype: 'textfield',
                                    validators: function(value) {
                                        var v = (value || '').trim();

                                        if (!v) {
                                            return 'Este campo es obligatorio';
                                        }

                                        var regex = /^[A-Za-zÁÉÍÓÚáéíóúÑñÜü' -]+$/;

                                        if (!regex.test(v)) {
                                            return 'Solo se permiten letras, espacios, guiones y apóstrofes';
                                        }

                                        return true;
                                    },
                                    id: 'ftUserPLastName',
                                    itemId: 'ftUserPLastName',
                                    margin: 8,
                                    errorTarget: 'under',
                                    label: 'Ape. Paterno',
                                    required: true,
                                    requiredMessage: 'Campo requerido'
                                },
                                {
                                    xtype: 'textfield',
                                    validators: function(value) {
                                        var v = (value || '').trim();

                                        if (!v) {
                                            return 'Este campo es obligatorio';
                                        }

                                        var regex = /^[A-Za-zÁÉÍÓÚáéíóúÑñÜü' -]+$/;

                                        if (!regex.test(v)) {
                                            return 'Solo se permiten letras, espacios, guiones y apóstrofes';
                                        }

                                        return true;
                                    },
                                    id: 'ftUserMLastName',
                                    itemId: 'ftUserMLastName',
                                    margin: 8,
                                    errorTarget: 'under',
                                    label: 'Ape. Materno',
                                    required: true,
                                    requiredMessage: 'Campo requerido'
                                },
                                {
                                    xtype: 'textfield',
                                    validators: function(value) {
                                        if (!value || !value.trim()) {
                                            return 'El teléfono es obligatorio';
                                        }

                                        if (!/^\d{10}$/.test(value.trim())) {
                                        return 'El teléfono debe tener 10 dígitos';
                                    }

                                    return true;
                                    },
                                    id: 'ftUserPhone',
                                    itemId: 'ftUserPhone',
                                    margin: 8,
                                    errorTarget: 'under',
                                    label: 'Telefono',
                                    required: true,
                                    requiredMessage: 'Campo requerido'
                                },
                                {
                                    xtype: 'toolbar',
                                    docked: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnConfirm',
                                            itemId: 'btnConfirm',
                                            ui: 'confirm',
                                            text: 'Confirmar',
                                            listeners: {
                                                tap: 'onBtnConfirmTap'
                                            }
                                        },
                                        {
                                            xtype: 'spacer'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnCancel',
                                            itemId: 'btnCancel',
                                            ui: 'decline',
                                            text: 'Cancelar',
                                            listeners: {
                                                tap: 'onBtnCancelTap'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onContMainResize: function(element, info, eOpts) {
        console.log('>>>resizswse');
        console.log(element);

        console.log('>>>info');
        console.log(info);


        let width = info;

        // 1. Log para depurar
            console.log('El ancho actual es:', width);

            // 2. Lógica condicional
            // Importante: Verifica el layout actual para no forzarlo mil veces si no ha cambiado
            var currentLayout = this.getLayout().type;

            if (width < 1000 /*&& currentLayout !== 'vbox'*/) {
                console.log('-> Cambiando a Modo Móvil');
                this.setLayout('hbox');
            }
            else if (width >= 1000 /*&& currentLayout !== 'hbox'*/) {
                console.log('-> Cambiando a Modo Escritorio');
                this.setLayout('vbox');
            }

    },

    onBtnCreateTap: function(button, e, eOpts) {
        /*
        // Buscas el contenedor padre
        var contUser    = Ext.getCmp('contUser'); // Asegúrate de tener reference='contResource'
        var toolbarMain = Ext.getCmp('toolbarMain');

        // Cambias a la vista del formulario (que es el item 1)
        // La animación 'slide' hará que parezca que entras a una nueva página
        contUser.setActiveItem(1);
        toolbarMain.hide();
        */
        var form = Ext.getCmp("formUser");
        form.isCreate = true;

        this.showForm();
    },

    onDataViewUserChildtap: function(dataview, location, eOpts) {
        // 1. Detectar si el toque fue en un botón de acción
            // Buscamos la clase '.action-btn' en el elemento tocado o sus padres
            var btn = location.event.getTarget('.action-btn');

            if (btn) {
                // 2. Extraer la acción y el registro
                var action = btn.getAttribute('data-action');
                var record = location.record.data;

                // Detenemos la propagación para que no seleccione la fila al tocar el botón
                location.event.stopEvent();

                // 3. Switch Maestro de Acciones
                switch (action) {
                    case 'view':
                        console.warn('Tap: view');
                        var form = Ext.getCmp("formUser");
                        form.isCreate = false;
                        form.userRecord = record;
                        this.showForm();
                        break;

                    case 'edit':
                        console.warn('Tap: view');
                        var form = Ext.getCmp("formUser");
                        form.isCreate = false;
                        form.userRecord = record;
                        this.showForm();
                        break;

                    case 'download':
                        console.warn('Tap: download');
                        this.downloadFile(record);
                        break;

                    case 'email':
                        console.warn('Tap: email');
                        this.sendByEmail(record);
                        break;

                    case 'whatsapp':
                        console.warn('Tap: whatsapp');
                        this.sendToWhatsApp(record);
                        break;

                    case 'attach':
                        console.warn('Tap: attach');
                        this.copyLinkToClipboard(record);
                        break;
                    case 'delete':
                        var idUser = record.id_user;
                        appLocal.deleteUser(record);
                        break;

                    default:
                        console.info('Action not identified');

                }
            }
    },

    onBtnConfirmTap: function(button, e, eOpts) {
        var email = jsTerian.readElementValue("ftUserEmail");
        var contMain = Ext.getCmp('contMain');

        var form = Ext.getCmp('formUser');

        if (!form.validate()) {
            Ext.Msg.alert('Validación', 'Revisa los campos marcados.');
            return;
        }

        var payload = contMain.buildPayload();

        appLocal.createUser(payload);
    },

    onBtnCancelTap: function(button, e, eOpts) {
        var contUser    = Ext.getCmp('contUser');
        var toolbarMain = Ext.getCmp('toolbarMain');

        contUser.setActiveItem(0);
        toolbarMain.show();

        this.cleanForm();
    },

    onContMainBeforeShow: function(component, eOpts) {
        jsTerian.loadStore('storeUser');
        jsTerian.loadStore('storeRole');
    },

    buildPayload: function() {
        var form = Ext.getCmp('formUser');
        var record = form.userRecord;
        var isCreate = form.isCreate;

        var id_user = record ? record.id_user : null;

        let password = jsTerian.readElementValue("ftUserPassword");
        password = password === null ? '' : String(password).trim();

        const payload = {
            id_user            : id_user || null,
            email              : jsTerian.readElementValue("ftUserEmail"),
            role_code          : jsTerian.readElementValue("cboUserRole"),
            first_name         : jsTerian.readElementValue("ftUserFirstName"),
            paternal_last_name : jsTerian.readElementValue("ftUserPLastName"),
            maternal_last_name : jsTerian.readElementValue("ftUserMLastName"),
            phone              : jsTerian.readElementValue("ftUserPhone")
        };

        if (isCreate) {
            payload.password = password;
        } else if (password) {
            payload.password = password;
        }

        return payload;
    },

    showUser: function(record) {
        console.log(record);

        // Suspender los eventos del formulario para traer toda la información
        try {
            // Proceso para mapear los datos
            const mapping = {
                ftUserEmail    : record.email,
                //ftUserPassword : record.id_so_status,
                cboUserRole    : record.role_code,
                ftUserFirstName: record.first_name,
                ftUserPLastName: record.paternal_last_name,
                ftUserMLastName: record.maternal_last_name,
                ftUserPhone    : record.phone,
                //ftSOCreated           : `${d.created_by} - ${dateOnly(d.created_at)}`,
                //ftSOUpdated           : `${d.updated_by || ''} - ${dateOnly(d.updated_at)}`
            };
            Ext.Object.each(mapping, function(field, value){
                jsTerian.assignElementValue(field, value);
            });

            // Punto para cargar el store
        }
        finally {

        }
    },

    showForm: function() {
        var contUser      = Ext.getCmp('contUser');
        var toolbarMain   = Ext.getCmp('toolbarMain');
        var lblUserTitle  = Ext.getCmp('lblUserTitle');
        var ftPassword    = Ext.getCmp('ftUserPassword');
        var cmpPasswordHint = Ext.getCmp('cmpPasswordHint');

        // Obtener el form y la propiedad isCreate
        var form     = Ext.getCmp("formUser");
        var isCreate = form.isCreate;
        var record   = form.userRecord;

        contUser.setActiveItem(1);
        toolbarMain.hide();

        if (ftPassword) {
            ftPassword.setValue('');
            if (ftPassword.setError) ftPassword.setError('');
        }

        if (isCreate) {
            console.log('create');

            if (lblUserTitle) lblUserTitle.setHtml('Crear usuario');

            if (ftPassword) {
                ftPassword.setRequired(true);
                ftPassword.setValue('');
                if (ftPassword.setError) ftPassword.setError('');
            }

            if (cmpPasswordHint) {
                cmpPasswordHint.setHtml('');
            }

        } else {
            console.log('update');

            if (lblUserTitle) lblUserTitle.setHtml('Editar usuario');

            if (ftPassword) {
                ftPassword.setRequired(false);
                ftPassword.setLabel('Contraseña');
                ftPassword.setValue('');
                if (ftPassword.setError) ftPassword.setError('');
            }

            if (cmpPasswordHint) {
                cmpPasswordHint.setHtml('Si se deja este campo vacío, la contraseña actual no será modificada.');
            }

            this.showUser(record);
        }
    },

    showDataView: function() {
        var contUser    = Ext.getCmp('contUser');
        var toolbarMain = Ext.getCmp('toolbarMain');

        contUser.setActiveItem(0);
        toolbarMain.show();
    },

    cleanForm: function() {
        try {
            const mapping = {
                ftUserEmail    : '',
                ftUserPassword : '',
                cboUserRole    : '',
                ftUserFirstName: '',
                ftUserPLastName: '',
                ftUserMLastName: '',
                ftUserPhone    : ''
            };

            Ext.Object.each(mapping, function(field, value) {
                jsTerian.assignElementValue(field, value);

                var cmp = Ext.getCmp(field);
                if (cmp && cmp.setError) {
                    cmp.setError('');
                }
            });
        }
        finally {
            var form = Ext.getCmp("formUser");
            form.isCreate = true;
        }
    }

});