/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'modelMenuTree',
        'modelAsset',
        'modelFeatured',
        'modelContent'
    ],
    stores: [
        'storeMenuTree',
        'storeTreeMenu',
        'storeAsset',
        'storeFeatured',
        'storeContent'
    ],
    views: [
        'contMain'
    ],
    name: 'damWorkspace',

    launch: function() {
        Ext.create('damWorkspace.view.contMain', {fullscreen: true});
        appLocal = this.getApplication();
        document.title = "Utility GO - Digital Assets Management";



        var contMain = Ext.getCmp('contMain');
        var currentWidth = contMain.element.getWidth();
        contMain.fireEvent('resize',contMain,currentWidth);

        var contWorkspace = Ext.getCmp('contWorkspace');
        contWorkspace.removeAll(true, true);
        contWorkspace.addCls('workspace-bg');
        contWorkspace.setHtml('');

        var btnCurrentUser = Ext.getCmp('btnCurrentUser');
        var usuario = jsTerian.getDataObjSS('TMP_SESSION','full_name');
        btnCurrentUser.setText(usuario);


        jsTerian.loadStore('storeTreeMenu');


        setTimeout(function() {
            Ext.getCmp('panelMenu').hide();
            },1000);

        Ext.getCmp('contMain').buildFeaturedView();



        window.addEventListener('beforeunload', function (e) {
            // Aquí puedes verificar si hay procesos activos o cambios sin guardar
            // Nota: Los navegadores modernos ya no permiten poner un mensaje personalizado.
            //e.preventDefault();
            e.returnValue = '';
        });




        history.pushState(null, null, location.href);
        window.onpopstate = function () {
            // Cuando el usuario da clic en "Atrás", lo empujamos de nuevo hacia adelante
            history.go(1);

            // Opcional: Mostrar un mensaje interno de tu app
            var msg = 'Use la aplicación para navegar.';

            jsDam.toast({ type:'warning', title:'Utility GO', message: msg });
        };
    },

    onDataviewAssetChildtap: function(dataview, location, eOpts) {
        console.log('Tapeado');

        console.log('dataview');
        console.log(dataview);

        console.log('location');
        console.log(location);

        console.log('eOpts');
        console.log(eOpts);
    },

    previewAsset: function(record) {
        var me = this,
            type = record.get('mime_type').toLowerCase(),
            url = record.get('url'), // Asegúrate de tener la URL real del archivo
            nombre = record.get('name'),
            contentItem;

        console.log('previewAsset - type',type);

        // 1. Determinar qué componente usar según el tipo
        switch (type) {
            case 'mp4':
            case 'mov':
            case 'video':
                contentItem = {
                    xtype: 'video',
                    url: url,
                    posterUrl: record.get('thumbnail_url'), // Imagen previa
                    autoResume: true
                };
                break;

            case 'jpg':
            case 'png':
            case 'image':
                contentItem = {
                    xtype: 'image',
                    src: url,
                    mode: 'img', // Para que mantenga proporciones
                    style: 'background-size: contain;'
                };
                break;

            case 'pdf':
                // Los PDF se ven mejor en un iframe
                contentItem = {
                    xtype: 'container',
                    html: '<iframe src="' + url + '" width="100%" height="100%" style="border: none;"></iframe>'
                };
                break;

            case 'docx':
            case 'xlsx':
            case 'pptx':
                // Para Office usamos el visor oficial de Microsoft (gratuito para web)
                var officeUrl = 'https://view.officeapps.live.com/op/view.aspx?src=' + encodeURIComponent(url);
                contentItem = {
                    xtype: 'container',
                    html: '<iframe src="' + officeUrl + '" width="100%" height="100%" style="border: none;"></iframe>'
                };
                break;

            default:
                Ext.Msg.alert('Aviso', 'No hay vista previa disponible para este tipo de archivo.');
                return;
        }

        // 2. Crear y mostrar el Diálogo (Modal)
        var dialog = Ext.create('Ext.Dialog', {
            title: nombre,
            closable: true,
            maximizable: true,
            width: '90%',
            height: '90%',
            layout: 'fit', // El contenido ocupará todo el modal
            items: [contentItem]
        });

        dialog.show();
    },

    previewFile: function(id_file) {
        var cfg = cfg || {};
        var url = jsTerian.makeUrl('asset/download', id_file);

        jsTerian.previewFileFromUrl(url, cfg);
    },

    previewFileFromUrl: function(url, cfg, record) {
        jsDam.previewFileFromURL(url,cfg,record);
    },

    downloadFileFromUrl: function(url, cfg) {
        cfg = cfg || {};
        var me = this;

        // Mask opcional (Modern)
        if (cfg.maskCmp && cfg.maskCmp.setMasked) {
            cfg.maskCmp.setMasked({ xtype: 'loadmask', message: cfg.maskText || 'Descargando...' });
        }

        Ext.Ajax.request({
            url   : url,
            method: 'GET',
            binary: true,
            headers: cfg.headers || undefined,

            success: function (resp) {
                if (cfg.maskCmp && cfg.maskCmp.setMasked) cfg.maskCmp.setMasked(false);

                var ct    = resp.getResponseHeader('Content-Type') || 'application/octet-stream';
                var bytes = resp.responseBytes || resp.responseArrayBuffer || null;

                if (!bytes) {
                    (me.toastAlert || Ext.toast).call(me, 'Respuesta binaria no disponible');
                    if (typeof cfg.onFail === 'function') cfg.onFail(resp);
                    return;
                }

                var blob   = new Blob([new Uint8Array(bytes)], { type: ct });
                var objUrl = (window.URL || window.webkitURL).createObjectURL(blob);

                // Intentar nombre desde Content-Disposition
                var cd   = resp.getResponseHeader('Content-Disposition') || '';
                var name = cfg.filename || 'archivo';

                var a = document.createElement('a');
                a.href = objUrl;
                a.download = name;
                document.body.appendChild(a);
                a.click();
                a.remove();

                setTimeout(function () {
                    (window.URL || window.webkitURL).revokeObjectURL(objUrl);
                }, 1500);

                // 3. Quitamos la máscara en cuanto la hoja se muestra
                Ext.Viewport.unmask();

                if (typeof cfg.onDone === 'function') cfg.onDone({ ok: true, filename: name, contentType: ct });
            },

            failure: function (resp) {
                if (cfg.maskCmp && cfg.maskCmp.setMasked) cfg.maskCmp.setMasked(false);

                if (me.toastAlert) me.toastAlert(cfg.failMsg || 'No se pudo descargar el archivo', 'error');
                else Ext.toast(cfg.failMsg || 'No se pudo descargar el archivo');

                if (typeof cfg.onFail === 'function') cfg.onFail(resp);
            }
        });
    }

});
