/*
 * File: app/store/storeTreeMenu.js
 *
 * This file was generated by Sencha Architect version 4.3.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damWorkspace.store.storeTreeMenu', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeTreeMenu',
            defaultRootText: 'root',
            root: {
                id: 'root',
                text: 'ROOT',
                expanded: true
            },
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json',
                    rootProperty: 'children'
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onLoad
                },
                load: {
                    fn: me.onTreeStoreLoad
                }
            }
        }, cfg)]);
    },

    onLoad: function(store, operation, eOpts) {
        if(!operation){
            return;
        }

        // Obtener el nodo
        var node = operation.node;

        // Obtener el id
        var id = node ? node.id : 'root';

        var url = (id === 'root') ? jsTerian.getUrl('tree/root') : jsTerian.getUrl('tree/children') + '/' + encodeURIComponent(id);

        store.getProxy().setUrl(url);
        jsTerian.addAuthorizationHeader(store);
    },

    onTreeStoreLoad: function(treestore, records, successful, operation, node, eOpts) {
        // Solo ejecutamos si la carga fue exitosa
            if (successful) {
                var root = treestore.getRoot();

                if (root) {
                    // OPCIÓN A: Expandir TODO el árbol (recursivo)
                    // Útil si el menú no es gigante.
                    /*
                    root.cascadeBy(function(node) {
                        // expand() marca el nodo como expanded:true y notifica a la vista
                        node.expand();
                    });
                    */

                    // OPCIÓN B: Expandir solo el PRIMER nivel (Hijos directos de la raíz)
                    // Descomenta esto si prefieres la Opción B y comenta la A
                    root.expand(); // Expande la raíz invisible para mostrar los primeros hijos
                    root.eachChild(function(node) {
                        node.expand(); // Expande los hijos de primer nivel
                    });
                }
            }
    }

});