/*
 * File: app/store/storeMenuTree.js
 *
 * This file was generated by Sencha Architect version 4.3.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damWorkspace.store.storeMenuTree', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'damWorkspace.model.modelMenuTree',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeMenuTree',
            autoLoad: true,
            model: 'damWorkspace.model.modelMenuTree',
            root: 'expanded: true',
            proxy: {
                type: 'ajax',
                url: 'resources/data/menu.json',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});