/*
 * File: app/view/contMainViewController.js
 *
 * This file was generated by Sencha Architect version 4.3.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damWorkspace.view.contMainViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.contmain',

    config: {
        inactivityTime: 9000000,
        timer: 0
    },

    constructor: function(cfg) {
        cfg = cfg || {};
        this.callParent(this.processContMainViewController(cfg));
    },

    processContMainViewController: function(config) {
        return config;
    },

    init: function() {
        this.startInactivityMonitor();
        this.startClock();





        console.log('init...');
    },

    startInactivityMonitor: function() {
        var me = this;

        // Obtenemos el elemento DOM del Viewport
        var el = Ext.getBody();

        // Escuchamos eventos que indiquen actividad del usuario
        // 'touchstart' es vital para móviles/tablets en Modern Toolkit
        el.on({
            touchstart: me.resetTimer,
            mousedown: me.resetTimer,
            keydown: me.resetTimer,
            //mousemove: me.resetTimer, // Opcional: puede ser costoso en rendimiento
            scope: me
        });

        // Iniciamos el temporizador por primera vez
        me.resetTimer();
    },

    resetTimer: function() {
        console.info('resetTimer');

        var me = this;

        // Si ya existe un timer pendiente, lo limpiamos
        if (me.getTimer()) {
            clearTimeout(me.getTimer());
        }

        // Creamos un nuevo timer
        var newTimer = setTimeout(function() {
            me.handleSessionTimeout();
            console.log('Corriendo timer');
        }, me.getInactivityTime());


        // Guardamos la referencia
        me.setTimer(newTimer);
    },

    handleSessionTimeout: function() {
        var me = this;

        // 1. Detener listeners para evitar errores o bucles
        var el = Ext.getBody();
        el.un({
            touchstart: me.resetTimer,
            mousedown: me.resetTimer,
            keydown: me.resetTimer,
            mousemove: me.resetTimer,
            scope: me
        });

        // 2. Mostrar mensaje o cerrar sesión directamente
        Ext.Msg.alert(
            'Sesión Expirada',
            'Tu sesión se ha cerrado por inactividad.',
            function() {
                me.doLogout();
            }
        );
    },

    doLogout: function() {
        // Aquí pones tu lógica:
        // - Destruir la vista principal
        // - Limpiar localStorage
        // - Redirigir al Login

        // Ejemplo:
        this.getView().destroy();
        sessionStorage.clear();
        window.location.href = "../basicAccess/index.html";

        console.log('Usuario desconectado por inactividad');
    },

    startClock: function() {
        var me = this;

                // 1. Ejecutamos la actualización una vez inmediatamente para no esperar 1 segundo en blanco
                me.updateClock();

                // 2. Configuramos el setInterval para que se repita cada 1000 milisegundos (1 segundo)
                me.relojInterval = setInterval(function() {
                    me.updateClock();
                }, 500);
    },

    updateClock: function() {
        // Obtenemos la hora actual en formato legible (ej: "21:29:36")
        var horaActual = new Date().toLocaleTimeString();
        var idProspect = jsTerian.getDataObjSS('UTM_PROSPECT','id_prospect');
        var email = jsTerian.getDataObjSS('UTM_PROSPECT','email');

        if(idProspect){
            if(Ext.getCmp('btnProspect').getText() !== email){
                Ext.getCmp('btnHome').fireEvent('tap');
                Ext.getCmp('btnProspect').setText(email);

                Ext.getCmp('contMain').prospectDetail(idProspect);
            }
        }
        else{
            Ext.getCmp('btnProspect').setText('Prospecto');
        }

        var numAssets = jsTerian.getDataObjSS('UTM_PROSPECT','num_assets');

        Ext.getCmp('btnProspect').setBadgeText(numAssets);
    },

    destroy: function() {
        if (this.relojInterval) {
                    clearInterval(this.relojInterval);
                }

                this.callParent(); // Llamada obligatoria a la clase padre en ExtJS
    }

});