/*
 * File: app/view/contMain.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('basicRole.view.contMain', {
    extend: 'Ext.Container',
    alias: 'widget.contMain',

    mixins: [
        'Ext.mixin.Responsive'
    ],
    requires: [
        'basicRole.view.contMainViewModel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.form.Panel',
        'Ext.field.Text'
    ],

    config: {
        responsiveConfig: 'responsiveConfig: {\n    \'width < 800\': {\n        layoutMode: \'mobile\' \n    },\n    \'width >= 800\': {\n        layoutMode: \'desktop\'\n    }\n}'
    },

    viewModel: {
        type: 'contmain'
    },
    id: 'contMain',
    itemId: 'contMain',
    fullscreen: true,
    layout: 'hbox',
    defaultListenerScope: true,

    listeners: {
        resize: 'onContMainResize',
        beforeshow: 'onContMainBeforeShow'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            id: 'contPanel',
            itemId: 'contPanel',
            layout: 'hbox',
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    id: 'contUser',
                    itemId: 'contUser',
                    layout: 'card',
                    items: [
                        {
                            xtype: 'toolbar',
                            id: 'toolbarMain',
                            itemId: 'toolbarMain',
                            docked: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btnCreate',
                                    itemId: 'btnCreate',
                                    ui: 'confirm',
                                    iconCls: 'fas fa-plus',
                                    text: 'Agregar',
                                    listeners: {
                                        tap: 'onBtnCreateTap'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {

                                    },
                                    id: 'btnDelete',
                                    itemId: 'btnDelete',
                                    ui: 'decline',
                                    iconCls: 'fas fa-trash',
                                    text: 'Eliminar'
                                },
                                {
                                    xtype: 'spacer'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnLoad',
                                    itemId: 'btnLoad',
                                    text: 'MyButton1',
                                    listeners: {
                                        tap: 'onBtnLoadTap'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            id: 'contListUser',
                            itemId: 'contListUser',
                            scrollable: true,
                            items: [
                                {
                                    xtype: 'container',
                                    id: 'contHeaderUser',
                                    itemId: 'contHeaderUser',
                                    html: '<div class="resource-row header-style"><div class="col-code">CÓDIGO</div><div class="col-code">NOMBRE</div><div class="col-desc">DESCRIPCIÓN</div><div class="col-actions">ACCIONES</div></div>'
                                },
                                {
                                    xtype: 'dataview',
                                    id: 'dataViewUser',
                                    itemId: 'dataViewUser',
                                    itemTpl: [
                                        '<div class="resource-row {[values.is_active ? \'\' : \'user-inactive\']}">',
                                        '',
                                        '    <div class="col-code">',
                                        '        <div class="text-bold">#{id_role}</div>',
                                        '        <div class="role-badge">{code}</div>',
                                        '    </div>',
                                        '',
                                        '    <div class="col-name">',
                                        '        <div class="role-badge">{name}</div>',
                                        '    </div>',
                                        '',
                                        '    <div class="col-desc">',
                                        '        <div class="main-text">',
                                        '            <span class="status-dot {[values.is_active ? \'active\' : \'inactive\']}"></span>',
                                        '            {description}',
                                        '        </div>',
                                        '    </div>',
                                        '',
                                        '    <div class="col-actions">',
                                        '        <div class="action-btn view" data-action="view" title="Ver Detalles">',
                                        '            <i class="x-fa fas fa-eye"></i>',
                                        '        </div>',
                                        '',
                                        '        <div class="action-btn edit" data-action="edit" title="Editar Usuario">',
                                        '            <i class="x-fa fas fa-pen"></i>',
                                        '        </div>',
                                        '',
                                        '        <!--',
                                        '        <div class="action-btn email" data-action="email" title="Enviar Correo">',
                                        '            <i class="x-fa fas fa-envelope"></i>',
                                        '        </div>',
                                        '        ',
                                        '',
                                        '        <div class="action-btn whatsapp" data-action="whatsapp" title="Contactar por WhatsApp">',
                                        '            <i class="x-fa fab fa-whatsapp"></i>',
                                        '        </div>',
                                        '        -->',
                                        '',
                                        '        <div class="action-btn delete" data-action="delete" title="Desactivar/Borrar">',
                                        '            <i class="x-fa fas fa-ban"></i>',
                                        '        </div>',
                                        '    </div>',
                                        '</div>'
                                    ],
                                    store: 'storeRole',
                                    listeners: {
                                        childtap: 'onDataViewUserChildtap'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'formpanel',
                            isCreate: true,
                            id: 'formRecord',
                            itemId: 'formRecord',
                            title: 'Crear Rol',
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'ftCode',
                                    itemId: 'ftCode',
                                    margin: 8,
                                    label: 'Codigo'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'ftName',
                                    itemId: 'ftName',
                                    margin: 8,
                                    label: 'Nombre'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'ftDescription',
                                    itemId: 'ftDescription',
                                    margin: 8,
                                    label: 'Descripcion'
                                },
                                {
                                    xtype: 'toolbar',
                                    id: 'toolbarRecord',
                                    itemId: 'toolbarRecord',
                                    docked: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnConfirm',
                                            itemId: 'btnConfirm',
                                            ui: 'confirm',
                                            text: 'Confirmar',
                                            listeners: {
                                                tap: 'onBtnConfirmTap'
                                            }
                                        },
                                        {
                                            xtype: 'spacer'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnCancel',
                                            itemId: 'btnCancel',
                                            ui: 'decline',
                                            text: 'Cancelar',
                                            listeners: {
                                                tap: 'onBtnCancelTap'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onContMainResize: function(element, info, eOpts) {
        console.log('>>>resizswse');
        console.log(element);

        console.log('>>>info');
        console.log(info);


        let width = info;

        // 1. Log para depurar
            console.log('El ancho actual es:', width);

            // 2. Lógica condicional
            // Importante: Verifica el layout actual para no forzarlo mil veces si no ha cambiado
            var currentLayout = this.getLayout().type;

            if (width < 1000 /*&& currentLayout !== 'vbox'*/) {
                console.log('-> Cambiando a Modo Móvil');
                this.setLayout('hbox');
            }
            else if (width >= 1000 /*&& currentLayout !== 'hbox'*/) {
                console.log('-> Cambiando a Modo Escritorio');
                this.setLayout('vbox');
            }

    },

    onBtnCreateTap: function(button, e, eOpts) {
        /*
        // Buscas el contenedor padre
        var contUser    = Ext.getCmp('contUser'); // Asegúrate de tener reference='contResource'
        var toolbarMain = Ext.getCmp('toolbarMain');

        // Cambias a la vista del formulario (que es el item 1)
        // La animación 'slide' hará que parezca que entras a una nueva página
        contUser.setActiveItem(1);
        toolbarMain.hide();
        */
        var form = Ext.getCmp('formRecord');

        console.log('form>');
        console.log(form);

        form.isCreate = true;

        this.showForm();
    },

    onBtnLoadTap: function(button, e, eOpts) {
        Ext.getStore('storeUser').load();
    },

    onDataViewUserChildtap: function(dataview, location, eOpts) {
        // 1. Detectar si el toque fue en un botón de acción
            // Buscamos la clase '.action-btn' en el elemento tocado o sus padres
            var btn = location.event.getTarget('.action-btn');

            if (btn) {
                // 2. Extraer la acción y el registro
                var action = btn.getAttribute('data-action');
                var record = location.record.data;

                // Detenemos la propagación para que no seleccione la fila al tocar el botón
                location.event.stopEvent();

                console.log('action >>> ',action);


                // 3. Switch Maestro de Acciones
                switch (action) {
                    case 'view':
                        console.warn('Tap: view');
                        var form = Ext.getCmp("formRecord");
                        form.isCreate = false;
                        form.userRecord = record;
                        this.showForm();
                        break;

                    case 'edit':
                        console.warn('Tap: view');
                        var form = Ext.getCmp("formRecord");
                        form.isCreate = false;
                        form.userRecord = record;
                        this.showForm();
                        break;

                    case 'download':
                        console.warn('Tap: download');
                        this.downloadFile(record);
                        break;

                    case 'email':
                        console.warn('Tap: email');
                        this.sendByEmail(record);
                        break;

                    case 'whatsapp':
                        console.warn('Tap: whatsapp');
                        this.sendToWhatsApp(record);
                        break;

                    case 'attach':
                        console.warn('Tap: attach');
                        this.copyLinkToClipboard(record);
                        break;

                    case 'delete':

                        Ext.Msg.show({
                            title: 'Eliminar Registro',
                            message: '¿Realmente deseas eliminar este registro? Esta acción no se puede deshacer.',
                            width: 300, // Opcional
                            closable: false,
                            icon: Ext.Msg.QUESTION,
                            buttons: [
                                {
                                    text: 'No',
                                    itemId: 'no'
                                },
                                {
                                    text: 'Sí, borrar',
                                    itemId: 'yes',
                                    ui: 'action-decline' // En Modern, esto suele poner el botón en rojo
                                }
                            ],
                            fn: function (buttonId) {
                                if (buttonId === 'yes') {
                                    // Lógica de borrado
                                    var idRole = record.id_role;
                                    appLocal.deleteRole(idRole);

                                    console.log('Registro eliminado');
                                }
                            }
                        });
                        break;

                    default:
                        console.log('Evento no definido');
                }
            }
    },

    onBtnConfirmTap: function(button, e, eOpts) {
        //var email = jsTerian.readElementValue("ftUserEmail");
        var contMain = Ext.getCmp('contMain');

        var payload = contMain.buildPayload();

        appLocal.createRole(payload);
    },

    onBtnCancelTap: function(button, e, eOpts) {
        var contUser    = Ext.getCmp('contUser');
        var toolbarMain = Ext.getCmp('toolbarMain');

        contUser.setActiveItem(0);
        toolbarMain.show();

        this.cleanForm();
    },

    onContMainBeforeShow: function(component, eOpts) {
        jsTerian.loadStore('storeUser');
        jsTerian.loadStore('storeRole');
    },

    buildPayload: function() {
        var id_role;
        var form = Ext.getCmp('formRecord');
        var record = form.dataRecord;

        if (record){
            id_role = record.id_role;
        }

        // Genera un 'diccionario' para enviar los datos del user
        const payload = {
            id_role     : id_role || null,
            code        : jsTerian.readElementValue("ftCode"),
            name        : jsTerian.readElementValue("ftName"),
            description : jsTerian.readElementValue("ftDescription"),
        };

        /*
        if (payload.password === null || String(payload.password).trim() === '') {
            delete payload.password;
        }
        */

        return payload;
    },

    showRecord: function(record) {
        console.log(record);

        // Suspender los eventos del formulario para traer toda la información
        try {
            // Proceso para mapear los datos
            const mapping = {
                ftCode        : record.code,
                ftName        : record.name,
                ftDescription : record.description,
            };
            Ext.Object.each(mapping, function(field, value){
                jsTerian.assignElementValue(field, value);
            });

            // Punto para cargar el store
        }
        finally {

        }
    },

    showForm: function() {
        var contUser    = Ext.getCmp('contUser');
        var toolbarMain = Ext.getCmp('toolbarMain');

        // Obtener el form y la propiedad isCreate
        var form = Ext.getCmp("formRecord");
        var isCreate = form.isCreate;
        var record = form.userRecord;

        contUser.setActiveItem(1);
        toolbarMain.hide();

        if (isCreate) {
            console.log('create');
            //Ext.getCmp('ftUserPassword').setHidden(false);
        } else {
            //Ext.getCmp('ftUserPassword').setHidden(true);
            console.log('update');
            this.showRecord(record);
        }
    },

    showDataView: function() {
        var contUser    = Ext.getCmp('contUser');
        var toolbarMain = Ext.getCmp('toolbarMain');

        contUser.setActiveItem(0);
        toolbarMain.show();
    },

    cleanForm: function() {
        try {
            // Proceso para mapear los datos
            const mapping = {
                ftCode        : '',
                ftName        : '',
                ftDescription : '',
            };
            Ext.Object.each(mapping, function(field, value){
                jsTerian.assignElementValue(field, value);
            });

            // Punto para cargar el store
        }
        finally {
            var form = Ext.getCmp("formRecord");
            form.isCreate = true;
        }
    }

});