/*
 * File: app/view/contMain.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damResource.view.contMain', {
    extend: 'Ext.Container',
    alias: 'widget.contMain',

    mixins: [
        'Ext.mixin.Responsive'
    ],
    requires: [
        'damResource.view.contMainViewModel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.tab.Panel',
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.form.Panel',
        'Ext.field.ComboBox',
        'Ext.field.File',
        'Ext.Spacer'
    ],

    config: {
        responsiveConfig: 'responsiveConfig: {\n    \'width < 800\': {\n        layoutMode: \'mobile\' \n    },\n    \'width >= 800\': {\n        layoutMode: \'desktop\'\n    }\n}'
    },

    viewModel: {
        type: 'contmain'
    },
    id: 'contMain',
    itemId: 'contMain',
    layout: 'hbox',
    defaultListenerScope: true,

    listeners: {
        resize: 'onContMainResize'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            id: 'contPanel',
            itemId: 'contPanel',
            layout: 'hbox',
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    id: 'contResource',
                    itemId: 'contResource',
                    layout: 'card',
                    items: [
                        {
                            xtype: 'toolbar',
                            id: 'toolbarResource',
                            itemId: 'toolbarResource',
                            docked: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btnCreate',
                                    itemId: 'btnCreate',
                                    ui: 'confirm',
                                    iconCls: 'fa-solid fa-plus',
                                    text: 'Agregar',
                                    listeners: {
                                        tap: 'onBtnCreateTap'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnUpdate',
                                    itemId: 'btnUpdate',
                                    iconCls: 'fa-solid fa-pen-to-square',
                                    text: 'Actualizar',
                                    listeners: {
                                        tap: 'onMybuttonTap'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnDelete',
                                    itemId: 'btnDelete',
                                    ui: 'decline',
                                    iconCls: 'fa-solid fa-trash-can',
                                    text: 'Eliminar'
                                }
                            ]
                        },
                        {
                            xtype: 'tabpanel',
                            id: 'tabPanelResource',
                            itemId: 'tabPanelResource',
                            items: [
                                {
                                    xtype: 'container',
                                    title: 'Videos',
                                    id: 'tabVideo',
                                    itemId: 'tabVideo',
                                    scrollable: true,
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'dataview',
                                            cls: 'assets-grid-view',
                                            id: 'dataViewResources',
                                            itemId: 'dataViewResources',
                                            inline: true,
                                            itemTpl: [
                                                '<div class="asset-card">',
                                                '    <div class="card-thumb">',
                                                '        <img src="{thumbnail_url}" onerror="this.src=\'resources/images/placeholder.png\'">',
                                                '        <div class="file-type-badge">{file_type}</div>',
                                                '    </div>',
                                                '',
                                                '    <div class="card-body">',
                                                '        <div class="asset-title">{name}</div>',
                                                '        <div class="asset-date">Subido por: {date_uploaded}</div>',
                                                '    </div>',
                                                '',
                                                '    <div class="card-actions">',
                                                '        <div class="action-btn" data-action="view"><i class="fa-solid fa-eye"></i></div>',
                                                '        <div class="action-btn" data-action="download"><i class="fa-solid fa-download"></i></div>',
                                                '        <div class="action-btn" data-action="email"><i class="fa-solid fa-envelope"></i></div>',
                                                '        ',
                                                '        <tpl if="file_type !== \'mov\'">',
                                                '            <div class="action-btn" data-action="whatsapp"><i class="fa-brands fa-whatsapp"></i></div>',
                                                '        </tpl>',
                                                '        ',
                                                '        <div class="action-btn" data-action="attach"><i class="fa-solid fa-paperclip"></i></div>',
                                                '    </div>',
                                                '</div>'
                                            ],
                                            store: 'storeResource',
                                            listeners: {
                                                childtap: 'onDataViewResourcesChildtap',
                                                added: 'onDataViewResourcesAdded'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    title: 'Imagenes',
                                    id: 'tabImage',
                                    itemId: 'tabImage',
                                    items: [
                                        {
                                            xtype: 'button',
                                            itemId: 'mybutton3',
                                            text: 'MyButton3',
                                            listeners: {
                                                tap: 'onMybutton3Tap'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    title: 'Documentos'
                                }
                            ]
                        },
                        {
                            xtype: 'formpanel',
                            id: 'formResourceRecord',
                            itemId: 'formResourceRecord',
                            padding: 20,
                            title: 'Recurso',
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'tfNombre',
                                    itemId: 'tfNombre',
                                    label: 'Field'
                                },
                                {
                                    xtype: 'combobox',
                                    id: 'cbTipo',
                                    itemId: 'cbTipo',
                                    label: 'Field'
                                },
                                {
                                    xtype: 'textfield',
                                    label: 'Field'
                                },
                                {
                                    xtype: 'filefield',
                                    id: 'ffFileLoad',
                                    itemId: 'ffFileLoad',
                                    label: 'Field'
                                },
                                {
                                    xtype: 'toolbar',
                                    id: 'toolbarResourceRecord',
                                    itemId: 'toolbarResourceRecord',
                                    docked: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnConfirm',
                                            itemId: 'btnConfirm',
                                            ui: 'confirm',
                                            text: 'Confirmar',
                                            listeners: {
                                                tap: 'onBtnConfirmTap'
                                            }
                                        },
                                        {
                                            xtype: 'spacer'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnCancel',
                                            itemId: 'btnCancel',
                                            ui: 'decline',
                                            text: 'Cancelar',
                                            listeners: {
                                                tap: 'onBtnCancelTap'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onContMainResize: function(element, info, eOpts) {
        console.log('>>>resizswse');
        console.log(element);

        console.log('>>>info');
        console.log(info);


        let width = info;

        // 1. Log para depurar
            console.log('El ancho actual es:', width);

            // 2. Lógica condicional
            // Importante: Verifica el layout actual para no forzarlo mil veces si no ha cambiado
            var currentLayout = this.getLayout().type;

            if (width < 1000 /*&& currentLayout !== 'vbox'*/) {
                console.log('-> Cambiando a Modo Móvil');
                this.setLayout('hbox');
            }
            else if (width >= 1000 /*&& currentLayout !== 'hbox'*/) {
                console.log('-> Cambiando a Modo Escritorio');
                this.setLayout('vbox');
            }

    },

    onBtnCreateTap: function(button, e, eOpts) {
        // Buscas el contenedor padre
        var contResource = Ext.getCmp('contResource'); // Asegúrate de tener reference='contResource'
        var toolbarResource = Ext.getCmp('toolbarResource');

        // Cambias a la vista del formulario (que es el item 1)
        // La animación 'slide' hará que parezca que entras a una nueva página
        contResource.setActiveItem(1);
        toolbarResource.hide();

    },

    onMybuttonTap: function(button, e, eOpts) {
        Ext.Msg.alert(releaseActiva(), 'El mensaje que quieres mostrar', function() {
            console.log('El usuario cerró la alerta');
        });
    },

    onDataViewResourcesChildtap: function(dataview, location, eOpts) {
        console.log('Tapeado - dataview');
        console.log(dataview);

        console.log('Tapeado - location');
        console.log(location);

                var record = location.record;




        // 1. Detectar si el clic fue en un elemento con la clase 'action-btn'
            // El método getTarget busca hacia arriba en el DOM desde donde se hizo clic
            var btn = location.event.getTarget('.action-btn');

            if (btn) {
                // 2. Leer el atributo data-action que definimos en el itemTpl
                var action = btn.getAttribute('data-action');



                // 4. Actuar según el botón
                switch (action) {
                    case 'view':
                        console.warn('Abrir Archivo');
                        //this.previewAsset(record);
                        break;
                    case 'download':
                        console.warn('Descargando: ' + record.get('name'));
                        break;
                    case 'whatsapp':
                        //this.sendToWhatsApp(record);
                        console.warn('Whatsappenado');
                        break;
                    case 'email':
                        console.warn('Enviando Emiliio');
                        //this.sendByEmail(record);
                        break;
                    case 'attach':
                        console.warn('Adjuntado Archivo');
                        //this.sendByEmail(record);
                        break;
                    default:
                        console.warn('Acción no definida:', action);
                }
            }

        appLocal.previewAsset(record);
    },

    onDataViewResourcesAdded: function(component, container, index, eOpts) {
        console.log('Asset Added...');
    },

    onMybutton3Tap: function(button, e, eOpts) {
        console.log('Cargando la Aplicacion');
        Ext.getStore('storeResource').load();
    },

    onBtnConfirmTap: function(button, e, eOpts) {

    },

    onBtnCancelTap: function(button, e, eOpts) {
        var contResource = Ext.getCmp('contResource'); // Asegúrate de tener reference='contResource'
        var toolbarResource = Ext.getCmp('toolbarResource');

        contResource.setActiveItem(0);
        toolbarResource.show();

    }

});