/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    views: [
        'contMain'
    ],
    name: 'basicAccess',

    launch: function() {
        Ext.create('basicAccess.view.contMain', {fullscreen: true});
        appLocal = this.getApplication();

        document.title = 'Utility GO';

        /*
        // Sin el listener de 'load', directo al registro
        if ('serviceWorker' in navigator) {
            console.log('Intentando registrar SW...');
            navigator.serviceWorker.register('/sw.js')
                .then(reg => console.log('SW registrado con éxito', reg))
                .catch(err => console.error('Error al registrar el SW', err));
        }
         otra ve*/
    },

    doLogin: function() {
        // Obtener el valor de los campos de texto para usuario y contraseña
        var email    = jsTerian.readElementValue('tfUser');
        var password = jsTerian.readElementValue('tfPassword');

        // Verificar que el valor tanto de user como de password sea no vacío
        if (!email || !password) {
            return jsTerian.msgSystem(
                'error',
                'Información requerida',
                'Debe ingresar usuario y contraseña'
            );
        }


        Ext.Viewport.mask({
            xtype: 'loadmask',
            message: 'Validando credenciales...', // El texto que quieres mostrar
            indicator: true // Muestra el círculo giratorio (spinner)
        });

        // Obtener el url a donde se hará la petición
        var url = jsTerian.getUrl('auth/login');

        // Informacion a enviar
        var jsonData = JSON.stringify({
            'email'   : email,
            'password': password,
        });

        var fnSuccess = function(response){
            console.log('ejecuto perfecto');
            var jsonData = Ext.decode(response.responseText);

            console.log(jsonData);

            if(jsonData.ok === true ){
                var TMP_SESSION        = jsonData.TMP_SESSION;
                var TMP_CFG_ORDER      = jsonData.TMP_CFG_ORDER;
                var TMP_EXCHANGE_RATES = jsonData.TMP_EXCHANGE_RATES;
                var TMP_CFG_PRODUCT    = jsonData.TMP_CFG_PRODUCT;
                var access_token       = jsonData.access_token;
                var user_role          = jsonData.user_role;

                jsTerian.saveDataSS('access_token',access_token);

                // Datos generales de la sesion
                jsTerian.saveDataObjSS('TMP_SESSION', 'full_name' , jsonData.user.full_name);
                jsTerian.saveDataObjSS('TMP_SESSION', 'email'     , jsonData.user.email);
                jsTerian.saveDataObjSS('TMP_SESSION', 'id_user'   , jsonData.user.id_user);
                jsTerian.saveDataObjSS('TMP_SESSION', 'role'      , jsonData.user.role);
                Ext.Viewport.unmask();

                var objMessage = {
                    type: 'confirm',
                    title: 'Usuario Valido',
                    message: 'Bienvenido ' + jsonData.user.full_name
                };
                jsDam.toast(objMessage);

                window.open('../damWorkspace/index.html','_self','toolbar=no');
            }
        };

        var fnFailure = function (response) {
            Ext.Viewport.unmask();

            var status = response.status,
                body   = {};

            // Intentar decodificar JSON para extraer 'error' o 'message'
            try {
                body = Ext.decode(response.responseText);
            } catch (e) {}

            switch (status) {
                case 401:
                    var objMessage = {
                        type: 'error',
                        title: 'Error de Acceso',
                        message: 'Credenciales inválidas. Verifica la información.'
                    };
                    jsDam.toast(objMessage);

                    break;

                case 409:

                    var objMessage = {
                        type: 'error',
                        title: 'Error de Acceso',
                        message: 'Conflicto de datos. Revisa tu información.'
                    };
                    jsDam.toast(objMessage);

                    break;

                default:
                    var objMessage = {
                        type: 'error',
                        title: 'Error de Acceso',
                        message: 'Error inesperado (' + status + ').'
                    };

                    jsDam.toast(objMessage);        }
        };

        jsTerian.makeRequest('POST',url, jsonData, fnSuccess, fnFailure, false);
    }

});
