/*
 * File: app/store/storeResource.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damResource.store.storeResource', {
    extend: 'Ext.data.Store',

    requires: [
        'damResource.model.modelResource',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeResource',
            autoLoad: true,
            model: 'damResource.model.modelResource',
            proxy: {
                type: 'ajax',
                url: 'resources/data/assets.json',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            },
            listeners: {
                load: {
                    fn: me.onJsonstoreLoad
                }
            }
        }, cfg)]);
    },

    onJsonstoreLoad: function(store, records, successful, operation, eOpts) {
        console.log('Store Cargado');
        console.log(store);
    }

});