/*
 * File: app/view/contMain.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damProspect.view.contMain', {
    extend: 'Ext.Container',
    alias: 'widget.contMain',

    mixins: [
        'Ext.mixin.Responsive'
    ],
    requires: [
        'damProspect.view.contMainViewModel',
        'Ext.form.Panel',
        'Ext.Button',
        'Ext.field.TextArea',
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.Spacer'
    ],

    config: {
        responsiveConfig: 'responsiveConfig: {\n    \'width < 800\': {\n        layoutMode: \'mobile\' \n    },\n    \'width >= 800\': {\n        layoutMode: \'desktop\'\n    }\n}'
    },

    viewModel: {
        type: 'contmain'
    },
    id: 'contMain',
    itemId: 'contMain',
    layout: 'vbox',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            flex: 1,
            id: 'contProspect',
            itemId: 'contProspect',
            layout: {
                type: 'card',
                animation: 'slide',
                'animation.duration': 150
            },
            items: [
                {
                    xtype: 'container',
                    sendMailProspect: function() {
                        console.info('sendMailProspect');

                        var dataAssets = Ext.getStore('storeAsset').getData();
                        var idProspect = jsTerian.getDataObjSS('UTM_PROSPECT','id_prospect');
                        var nameProspect = jsTerian.getDataObjSS('UTM_PROSPECT','name');
                        var emailProspect = jsTerian.getDataObjSS('UTM_PROSPECT','email');

                        console.log('dataAssets');
                        console.log(dataAssets);

                        var assetIds = dataAssets.items.map(function(item) {
                            return item.data.id_asset;
                        });


                        console.log('assetIds:',assetIds);

                        var fnSuccess = function(pResponse){
                            console.log('Success: Correo Enviado');

                            var msg;
                            try {
                                msg = Ext.decode(pResponse.responseText);
                            }
                            catch(e){
                                msg = { success:true, message:'Success', data:{} };
                            }

                            console.log('msg: ', msg);

                            // Elige el primero que esta disponible
                            var data = msg.data || {};

                            console.log('data:',data);


                            Ext.Viewport.unmask();

                            var objMessage = {
                                type: 'success',
                                title: 'Enviado',
                                message: 'Se ha enviado el Correo a ' + nameProspect + ' (' + emailProspect + ')',
                                icon: 'fas fa-envelope'
                            };

                            jsDam.toast(objMessage);
                            Ext.getCmp('btnResetProspect').fireEvent('tap');
                        };

                        var fnFailure = function(pResponse){
                            console.log('Failure: User Prospecto fallo la asigancion');
                            Ext.Viewport.unmask();
                        };


                        var endPoint   = 'prospect/' + idProspect + '/send-email';
                        var url        = jsTerian.getUrl(endPoint);

                        // Informacion a enviar
                        var jsonData = JSON.stringify({
                            'asset_ids'     : assetIds
                        });

                        console.info('jsonData:',jsonData);
                        console.info('url:',url);

                        Ext.Viewport.mask({
                            xtype: 'loadmask',
                            indicator: false, // 1. Ocultamos el spinner feo por defecto
                            style: 'background: rgba(0,0,0,0.6);', // 2. Fondo un poco más oscuro
                            // 3. Inyectamos HTML: Icono girando + Texto
                            message: '<div style="text-align:center;">' +
                            '<i class="fas fa-circle-notch fa-spin" style="font-size: 3em; color: white;"></i>' +
                            '<div style="margin-top:15px; font-size: 1.2em; color: white; font-weight:300;">Enviando Mail...</div>' +
                            '</div>'
                        });

                        jsTerian.makeRequest('POST',url, jsonData, fnSuccess, fnFailure, true);
                    },
                    id: 'contProspectData',
                    items: [
                        {
                            xtype: 'formpanel',
                            id: 'formProspect',
                            itemId: 'formProspect',
                            items: [
                                {
                                    xtype: 'container',
                                    id: 'contName',
                                    itemId: 'contName',
                                    layout: 'hbox',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            id: 'tfName',
                                            itemId: 'tfName',
                                            margin: '7 7 0 7',
                                            label: 'Nombre'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnSearch',
                                            itemId: 'btnSearch',
                                            ui: 'action',
                                            margin: '7 7 0 7',
                                            iconCls: 'fas fa-search',
                                            listeners: {
                                                tap: 'onBtnSearchTap'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'tfJobTitle',
                                    itemId: 'tfJobTitle',
                                    margin: '7 7 0 7',
                                    label: 'Cargo'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'tfCompany',
                                    itemId: 'tfCompany',
                                    margin: '7 7 0 7',
                                    label: 'Empresa'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'tfMail',
                                    itemId: 'tfMail',
                                    margin: '7 7 0 7',
                                    label: 'Correo'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'tfTelephone',
                                    itemId: 'tfTelephone',
                                    margin: '7 7 0 7',
                                    label: 'Telefono'
                                },
                                {
                                    xtype: 'textareafield',
                                    id: 'taNote',
                                    itemId: 'taNote',
                                    margin: '7 7 7 7',
                                    label: 'Mensaje'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            deleteAsset: function(record) {
                                var id_prospect = jsTerian.getDataObjSS('UTM_PROSPECT','id_prospect');
                                var id_asset    = record.data.id_asset;

                                var fnSuccess = function(pResponse){
                                    console.log('Success: Prospecto Asignado');

                                    var msg;
                                    try {
                                        msg = Ext.decode(pResponse.responseText);
                                    }
                                    catch(e){
                                        msg = { success:true, message:'Success', data:{} };
                                    }

                                    console.log('msg: ', msg);

                                    // Elige el primero que esta disponible
                                    var data = msg.data || {};

                                    console.log('data:',data);

                                    Ext.getCmp('contMain').prospectDetail(id_prospect);
                                    //Ext.getCmp('contMain').prospectStatus();
                                };

                                var fnFailure = function(pResponse){
                                    console.log('Failure: Prospecto fallo el grado');
                                };


                                var endPoint = 'prospect/'+ id_prospect + '/assets/' + id_asset;
                                var url = jsTerian.getUrl(endPoint);

                                // Informacion a enviar
                                var jsonData = JSON.stringify({
                                    'id_prospect' : id_prospect,
                                    'id_asset'    : id_asset
                                });

                                console.info('jsonData:',jsonData);
                                console.info('url:',url);

                                jsTerian.makeRequest('DELETE',url, jsonData, fnSuccess, fnFailure, true);
                            },
                            id: 'contFiles',
                            itemId: 'contFiles',
                            margin: '7 0 0 0',
                            layout: 'vbox',
                            items: [
                                {
                                    xtype: 'container',
                                    id: 'contFilesHeader',
                                    itemId: 'contFilesHeader',
                                    html: '<div class="resource-row header-style"> <div class="col-asset-name">ARCHIVO</div> <div class="col-asset-data">TIPO</div> <div class="col-actions">ACCIONES</div> </div>'
                                },
                                {
                                    xtype: 'dataview',
                                    flex: 1,
                                    id: 'dataViewAssets',
                                    itemId: 'dataViewAssets',
                                    itemTpl: [
                                        '<div class="resource-row {[values.is_active ? \'\' : \'asset-inactive\']}">',
                                        '',
                                        '    <div class="col-asset-name">',
                                        '        <div class="role-badge">{original_filename}</div>',
                                        '        <div class="col-badge">{file_size}</div>',
                                        '    </div>',
                                        '',
                                        '',
                                        '    ',
                                        '    <div class="col-asset-data">',
                                        '        <div class="role-badge">{file_type}</div>',
                                        '    </div>',
                                        '    ',
                                        '',
                                        '    <div class="col-actions">',
                                        '        <div class="action-btn view" data-action="view" title="Ver Detalles">',
                                        '            <i class="x-fa fas fa-eye"></i>',
                                        '        </div>',
                                        '',
                                        '        <div class="action-btn delete" data-action="delete" title="Desactivar/Borrar">',
                                        '            <i class="x-fa fas fa-trash"></i>',
                                        '        </div>',
                                        '        ',
                                        '        <!--',
                                        '',
                                        '        <div class="action-btn download" data-action="download" title="Descargar">',
                                        '            <i class="x-fa fas fa-download"></i>',
                                        '        </div>',
                                        '',
                                        '',
                                        '        <div class="action-btn edit" data-action="edit" title="Editar Usuario">',
                                        '            <i class="x-fa fas fa-pen"></i>',
                                        '        </div>',
                                        '',
                                        '        <div class="action-btn email" data-action="email" title="Enviar Correo">',
                                        '            <i class="x-fa fas fa-envelope"></i>',
                                        '        </div>',
                                        '',
                                        '        <div class="action-btn whatsapp" data-action="whatsapp" title="Contactar por WhatsApp">',
                                        '            <i class="x-fa fab fa-whatsapp"></i>',
                                        '        </div>',
                                        '',
                                        '        -->',
                                        '',
                                        '    </div>',
                                        '</div>'
                                    ],
                                    store: 'storeAsset',
                                    listeners: {
                                        childtap: 'onDataViewAssetsChildtap'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            id: 'toolbarMain',
                            itemId: 'toolbarMain',
                            docked: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btnSaveProspect',
                                    itemId: 'btnSaveProspect',
                                    ui: 'confirm',
                                    width: 120,
                                    iconCls: 'fas fa-check',
                                    text: 'Confirmar',
                                    textAlign: 'left',
                                    listeners: {
                                        tap: 'onBtnSaveProspectTap'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnResetProspect',
                                    itemId: 'btnResetProspect',
                                    ui: 'decline',
                                    iconCls: 'fas fa-arrows-rotate',
                                    text: 'Reestablecer',
                                    textAlign: 'left',
                                    listeners: {
                                        tap: 'onBtnResetProspectTap'
                                    }
                                },
                                {
                                    xtype: 'spacer'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnSendMail',
                                    itemId: 'btnSendMail',
                                    ui: 'confirm',
                                    width: 120,
                                    iconCls: 'fas fa-envelope',
                                    text: 'Mail',
                                    textAlign: 'left',
                                    listeners: {
                                        tap: 'onBtnSendMailTap'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    deleteProspect: function(record) {
                        console.log('deleteProspect:',record);

                        var id_prospect = record.data.id_prospect;

                        var fnSuccess = function(pResponse){
                            console.log('Success: Prospecto Eliminado');

                            var msg;
                            try {
                                msg = Ext.decode(pResponse.responseText);
                            }
                            catch(e){
                                msg = { success:true, message:'Success', data:{} };
                            }

                            console.log('msg: ', msg);

                            // Elige el primero que esta disponible
                            var data = msg.data || {};

                            console.log('data:',data);

                            jsTerian.loadStore('storeProspect');
                            //Ext.getCmp('contMain').prospectStatus();
                        };

                        var fnFailure = function(pResponse){
                            console.log('Failure: Prospecto fallo el grado');
                        };


                        var endPoint = 'prospect/delete/' + id_prospect;
                        var url = jsTerian.getUrl(endPoint);

                        // Informacion a enviar
                        var jsonData = JSON.stringify({
                            'id_prospect' : id_prospect
                        });

                        console.info('jsonData:',jsonData);
                        console.info('url:',url);

                        jsTerian.makeRequest('DELETE',url, jsonData, fnSuccess, fnFailure, true);
                    },
                    hidden: true,
                    id: 'contProspectSearch',
                    itemId: 'contProspectSearch',
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'container',
                            id: 'contProspectHeader',
                            itemId: 'contProspectHeader',
                            html: '<div class="resource-row header-style"> <div class="col-prospect-name">PROSPECTO</div> <div class="col-prospect-data">CONTACTO</div> <div class="col-actions">ACCION</div></div>'
                        },
                        {
                            xtype: 'dataview',
                            flex: 1,
                            id: 'dataViewProspect',
                            itemId: 'dataViewProspect',
                            itemTpl: [
                                '<div class="resource-row {[values.is_active ? \'\' : \'prospect-inactive\']}">',
                                '',
                                '    <div class="col-prospect-name">',
                                '        <div class="text-bold">{name}</div>',
                                '        <div class="role-badge">{company}</div>',
                                '    </div>',
                                '',
                                '    <div class="col-prospect-data">',
                                '        <div class="text-bold">{email}</div>',
                                '        <div class="role-badge">{telephone}</div>',
                                '    </div>',
                                '',
                                '    <div class="col-actions">',
                                '        <div class="action-btn view" data-action="check" title="Ver Detalles">',
                                '            <i class="x-fa fas fa-check"></i>',
                                '        </div>',
                                '',
                                '        <!--',
                                '        <div class="action-btn email" data-action="email" title="Enviar Correo">',
                                '            <i class="x-fa fas fa-envelope"></i>',
                                '        </div>',
                                '        ',
                                '',
                                '        <div class="action-btn whatsapp" data-action="whatsapp" title="Contactar por WhatsApp">',
                                '            <i class="x-fa fab fa-whatsapp"></i>',
                                '        </div>',
                                '        -->',
                                '',
                                '        <div class="action-btn delete" data-action="delete" title="Desactivar/Borrar">',
                                '            <i class="x-fa fas fa-trash"></i>',
                                '        </div>',
                                '    </div>',
                                '</div>'
                            ],
                            store: 'storeProspect',
                            listeners: {
                                childtap: 'onDataViewProspectChildtap'
                            }
                        },
                        {
                            xtype: 'toolbar',
                            id: 'toolbarSearch',
                            itemId: 'toolbarSearch',
                            docked: 'bottom',
                            items: [
                                {
                                    xtype: 'spacer'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnCloseSearch',
                                    itemId: 'btnCloseSearch',
                                    ui: 'decline',
                                    minWidth: 120,
                                    iconCls: 'fas fa-close',
                                    text: 'Cerrar',
                                    listeners: {
                                        tap: 'onBtnCloseSearchTap'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        resize: 'onContMainResize'
    },

    onBtnSearchTap: function(button, e, eOpts) {
        // 1. Buscamos al contenedor padre (el que tiene el layout card)
        // Usamos .up() que busca hacia arriba en el árbol de componentes
        var contenedorPadre = button.up('#contProspect');

        // 2. Le ordenamos al padre que cambie la "tarjeta" activa al contenedor 2
        contenedorPadre.setActiveItem('#contProspectSearch');
        jsTerian.loadStore('storeProspect');
    },

    onDataViewAssetsChildtap: function(dataview, location, eOpts) {
        // 1. Detectar si el toque fue en un botón de acción
        // Buscamos la clase '.action-btn' en el elemento tocado o sus padres
        var btn = location.event.getTarget('.action-btn');

        if (btn) {
            // 2. Extraer la acción y el registro
            var action = btn.getAttribute('data-action');
            var record = location.record;

            // Detenemos la propagación para que no seleccione la fila al tocar el botón
            location.event.stopEvent();

            // 3. Switch Maestro de Acciones
            switch (action) {
                case 'view':

                    var url = jsTerian.makeUrl('asset/download',record.data.id_asset);
                    var objConfig = {
                        title  : record.data.name};
                    jsDam.previewFileFromURL(
                        url,
                        objConfig
                    );

                    break;

                case 'edit':
                    console.warn('Tap: view');
                    var form = Ext.getCmp("formRecord");
                    form.isCreate = false;
                    form.userRecord = record;
                    this.showForm();
                    break;

                case 'download':
                    console.warn('Tap: download');
                    var url = jsTerian.makeUrl('asset/download',record.data.id_asset);
                    appLocal.downloadFileFromUrl(
                      url + '?download=true',
                      {
                          filename: record.data.original_filename
                      }
                    );

                    break;

                case 'email':
                    console.warn('Tap: email');
                    this.sendByEmail(record);
                    break;

                case 'whatsapp':
                    console.warn('Tap: whatsapp');
                    jsTerian.sendToWhatsApp(record);
                    break;

                case 'attach':
                    console.warn('Tap: attach');
                    jsTerian.copyLinkToClipboard(record);
                    break;

                case 'delete':

                    var information = '¿Realmente deseas eliminar este registro?</br>' +
                                      record.data.original_filename + '</br></br>' +
                                      'Esta acción no se puede deshacer.';

                    Ext.Msg.show({
                        title: 'Eliminar Registro',
                        message: information,
                        width: 300, // Opcional
                        closable: false,
                        icon: Ext.Msg.QUESTION,
                        buttons: [
                            {
                                text: 'No',
                                itemId: 'no'
                            },
                            {
                                text: 'Sí, borrar',
                                itemId: 'yes',
                                ui: 'action-decline' // En Modern, esto suele poner el botón en rojo
                            }
                        ],
                        fn: function (buttonId) {
                            if (buttonId === 'yes') {
                                // Lógica de borrado



                                //var idRole = record.id_role;
                                //appLocal.deleteRole(idRole);

                                Ext.getCmp('contFiles').deleteAsset(record);

                                console.log('Registro eliminado');
                                console.log('record:',record);
                            }
                        }
                    });
                    break;

                default:
                    console.log('Evento no definido');
            }
        }
    },

    onBtnSaveProspectTap: function(button, e, eOpts) {
        Ext.getCmp('contMain').prospectSave();
    },

    onBtnResetProspectTap: function(button, e, eOpts) {
        Ext.getCmp('formProspect').reset();
        sessionStorage.removeItem('UTM_PROSPECT');
        Ext.getStore('storeAsset').setData({});

        var tfName = Ext.getCmp('tfName');

        if (tfName) {
            // Esperamos 50 milisegundos antes de poner el foco
            Ext.defer(function() {
                    console.log('focus');
                tfName.focus();
            }, 50);
        }

        Ext.getCmp('contMain').prospectStatus();
    },

    onBtnSendMailTap: function(button, e, eOpts) {
        Ext.getCmp('contProspectData').sendMailProspect();
    },

    onDataViewProspectChildtap: function(dataview, location, eOpts) {
        // 1. Detectar si el toque fue en un botón de acción
        // Buscamos la clase '.action-btn' en el elemento tocado o sus padres
        var btn = location.event.getTarget('.action-btn');

        if (btn) {
            // 2. Extraer la acción y el registro
            var action = btn.getAttribute('data-action');
            var record = location.record;

            var prospectData = record.data;

            // Detenemos la propagación para que no seleccione la fila al tocar el botón
            location.event.stopEvent();

            console.log('record:',record);

            // 3. Switch Maestro de Acciones
            switch (action) {
                case 'check':
                    console.warn('Tap: check');
                    Ext.getCmp('formProspect').reset();
                    sessionStorage.removeItem('UTM_PROSPECT');

                    Ext.defer(function() {
                        console.log('focus');
                        Ext.getCmp('contMain').prospectSetActive(prospectData);
                        Ext.getCmp('contMain').prospectStatus();
                    }, 50);

                    break;
                case 'delete':
                    Ext.Msg.show({
                        title: 'Eliminar Registro',
                        message: '¿Realmente deseas eliminar este registro? </br><b>' + prospectData.name + ' ' + prospectData.email + '</b></br></br>Esta acción no se puede deshacer.',
                        width: 300, // Opcional
                        closable: false,
                        icon: Ext.Msg.QUESTION,
                        buttons: [
                            {
                                text: 'No',
                                itemId: 'no'
                            },
                            {
                                text: 'Sí, borrar',
                                itemId: 'yes',
                                ui: 'action-decline' // En Modern, esto suele poner el botón en rojo
                            }
                        ],
                        fn: function (buttonId) {
                            if (buttonId === 'yes') {
                                Ext.getCmp('contProspectSearch').deleteProspect(record);
                                console.log('Registro eliminado prospectData..>',prospectData);
                            }
                        }
                    });
                    break;

                default:
                    console.log('Evento no definido');
            }
        }
    },

    onBtnCloseSearchTap: function(button, e, eOpts) {
        var contenedorPadre = button.up('#contProspect');

        // Lo regresamos a la vista de datos
        contenedorPadre.setActiveItem('#contProspectData');
    },

    onContMainResize: function(element, info, eOpts) {
        console.log('>>>resizswse');
        console.log(element);

        console.log('>>>info');
        console.log(info);


        let width = info;

        // 1. Log para depurar
            console.log('El ancho actual es:', width);

            // 2. Lógica condicional
            // Importante: Verifica el layout actual para no forzarlo mil veces si no ha cambiado
            var currentLayout = this.getLayout().type;

            if (width < 1000 /*&& currentLayout !== 'vbox'*/) {
                console.log('-> Cambiando a Modo Móvil');
                this.setLayout('hbox');
            }
            else if (width >= 1000 /*&& currentLayout !== 'hbox'*/) {
                console.log('-> Cambiando a Modo Escritorio');
                this.setLayout('vbox');
            }

    },

    prospectSave: function() {
        var fnSuccess = function(pResponse){
            console.log('Success: Prospecto Asignado');

            var msg;
            try {
                msg = Ext.decode(pResponse.responseText);
            }
            catch(e){
                msg = { success:true, message:'Success', data:{} };
            }

            console.log('msg: ', msg);

            // Elige el primero que esta disponible
            var data = msg.data || {};

            console.log('data:',data);

            Ext.getCmp('contMain').prospectUserSave(jsTerian.getDataObjSS('TMP_SESSION','id_user'),data.id_prospect);
            Ext.getCmp('contMain').prospectSetActive(data);
            Ext.getCmp('contMain').prospectStatus();



        };

        var fnFailure = function(pResponse){
            console.log('Failure: Prospecto fallo el grado');
        };

        var url = jsTerian.getUrl('prospect/create');

        // Informacion a enviar
        var jsonData = JSON.stringify({
            'name'     : jsTerian.readElementValue('tfName'),
            'job_title': jsTerian.readElementValue('tfJobTitle'),
            'company'  : jsTerian.readElementValue('tfCompany'),
            'email'    : jsTerian.readElementValue('tfMail'),
            'telephone': jsTerian.readElementValue('tfTelephone'),
            'notes'    : jsTerian.readElementValue('taNote')
        });

        console.info('jsonData:',jsonData);
        console.info('url:',url);

        jsTerian.makeRequest('POST',url, jsonData, fnSuccess, fnFailure, true);

    },

    prospectUserSave: function(pIdUser, pIdProspect) {
        var fnSuccess = function(pResponse){
            console.log('Success: User Prospecto Asignado');

            var msg;
            try {
                msg = Ext.decode(pResponse.responseText);
            }
            catch(e){
                msg = { success:true, message:'Success', data:{} };
            }

            console.log('msg: ', msg);

            // Elige el primero que esta disponible
            var data = msg.data || {};

            console.log('data:',data);



        };

        var fnFailure = function(pResponse){
            console.log('Failure: User Prospecto fallo la asigancion');
        };

        var endPoint = 'prospect/' + pIdProspect + '/assign-users';
        var url = jsTerian.getUrl(endPoint);

        var userIds = [];
        userIds.push(pIdUser);

        // Informacion a enviar
        var jsonData = JSON.stringify({
            'user_ids'     : userIds
        });

        console.info('jsonData:',jsonData);
        console.info('url:',url);

        jsTerian.makeRequest('POST',url, jsonData, fnSuccess, fnFailure, true);
    },

    prospectDetail: function(pIdProspect) {
        // Función para formatear el tamaño (Bytes a KB, MB, etc.)
        const formatBytes = (bytes, decimals = 2) => {
            if (!bytes || bytes === 0) return '0 Bytes';
            const k = 1024;
            const dm = decimals < 0 ? 0 : decimals;
            const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
            const i = Math.floor(Math.log(bytes) / Math.log(k));
            return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
        };

        // Función para obtener la extensión
        const getExt = (name) => {
            if (!name) return '';
            return name.slice(((name.lastIndexOf(".") - 1) >>> 0) + 2).toUpperCase();
        };


        const getFileTypeCategory = (extension) => {
            // 1. Validar que la extensión exista (que no sea null o indefinida)
            if (!extension) {
                return 'ARCHIVO';
            }

            // 2. Limpiar el texto: minúsculas, sin espacios y sin el punto inicial
            const ext = extension.toLowerCase().trim().replace('.', '');

            // 3. Definir los grupos (puedes agregar más si lo necesitas)
            const images = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'bmp', 'tiff'];
            const videos = ['mp4', 'mov', 'webm', 'avi', 'mkv', 'wmv'];
            const office = ['doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'];

            // 4. Evaluar a qué grupo pertenece
            if (images.includes(ext)) {
                return 'IMAGEN';
            }

            if (videos.includes(ext)) {
                return 'VIDEO';
            }

            if (ext === 'pdf') {
                return 'PDF';
            }

            if (office.includes(ext)) {
                return 'OFFICE';
            }

            // 5. Si no coincide con nada de lo anterior, es un archivo genérico
            return 'ARCHIVO';
        };

        var fnSuccess = function(pResponse){
            console.log('Success: Prospecto Asignado');

            var msg;
            try {
                msg = Ext.decode(pResponse.responseText);
            }
            catch(e){
                msg = { success:true, message:'Success', data:{} };
            }

            console.log('msg: ', msg);

            // Elige el primero que esta disponible
            var dataProspect = msg.prospect || {};

            console.log('dataProspect:',dataProspect);

            jsTerian.assignElementValue('tfName'      ,dataProspect.name);
            jsTerian.assignElementValue('tfJobTitle'  ,dataProspect.job_title);
            jsTerian.assignElementValue('tfCompany'   ,dataProspect.company);
            jsTerian.assignElementValue('tfMail'      ,dataProspect.email);
            jsTerian.assignElementValue('tfTelephone' ,dataProspect.telephone);
            jsTerian.assignElementValue('taNote'      ,dataProspect.notes);


            dataProspect.assets.forEach(record => {
                const filename = record.original_filename; // Extraído de la data
                const bytes = record.size_bytes;           // Extraído de la data


                record.file_extension = getExt(filename);
                record.file_size      = formatBytes(bytes);
                record.file_type      = getFileTypeCategory(record.file_extension);

            });


            jsTerian.saveDataObjSS('UTM_PROSPECT','num_assets',dataProspect.assets.length);
            Ext.getStore('storeAsset').setData(dataProspect.assets);

        };

        var fnFailure = function(pResponse){
            console.log('Failure: Prospecto fallo el grado');
        };

        var endPoint = 'prospect/detail/' + pIdProspect + '?include_users=true&include_assets=true';
        var url = jsTerian.getUrl(endPoint);

        // Informacion a enviar
        var jsonData = JSON.stringify({
            'id_prospect'     : pIdProspect
        });

        console.info('jsonData:',jsonData);
        console.info('url:',url);

        jsTerian.makeRequest('GET',url, jsonData, fnSuccess, fnFailure, true);

    },

    prospectStatus: function() {
        var id_prospect = jsTerian.getDataObjSS('UTM_PROSPECT','id_prospect');

        if(id_prospect){
            Ext.getCmp('contMain').prospectDetail(id_prospect);

            Ext.getCmp('btnSaveProspect').hide();
            Ext.getCmp('btnResetProspect').show();
            Ext.getCmp('btnSendMail').show();
        }
        else{
            Ext.getCmp('btnSaveProspect').show();
            Ext.getCmp('btnResetProspect').hide();
            Ext.getCmp('btnSendMail').hide();

        }
    },

    prospectSetActive: function(pData) {
        jsTerian.saveDataObjSS('UTM_PROSPECT','id_prospect',pData.id_prospect);
        jsTerian.saveDataObjSS('UTM_PROSPECT','name'       ,pData.name);
        jsTerian.saveDataObjSS('UTM_PROSPECT','company'    ,pData.company);
        jsTerian.saveDataObjSS('UTM_PROSPECT','email'      ,pData.email);

        console.log('propsctSetActive:',pData);

    }

});