/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'modelUser',
        'modelRole'
    ],
    stores: [
        'storeUser',
        'storeRole'
    ],
    views: [
        'contMain'
    ],
    name: 'basicRole',

    launch: function() {
        Ext.create('basicRole.view.contMain', {fullscreen: true});
        appLocal = this.getApplication();

        // Carga de stores
        jsTerian.loadStore('storeUser');
        jsTerian.loadStore('storeRole');
        jsTerian.loadStore('storeRoleJson');
    },

    createRole: function(payload, isCreate) {
        var form = Ext.getCmp("formRecord");
        var isCreate = form.isCreate;

        // Crear la URL dependiendo del tipo de solicitud
        var method = isCreate ? 'POST' : 'PUT';
        var url    = isCreate ? jsTerian.makeUrl('role/create')
                              : jsTerian.makeUrl('role/update', payload.id_role);

        // Mostrar máscara para feedback al usuario, solo se ve cuando la solicitud tarda
        //Ext.getBody().mask(isCreate ? 'Creando Usuario...' : 'Actualizando Usuario...');

        //if (payload.id_product === null || payload.id_product === 'null') {
          //  console.log('Aqui es donde se debe guardar el producto');
            //return;
        //}

        console.log(payload);

        // Realizar la solicitud según sea el caso

        jsTerian.makeRequest(
            method,
            url,
            JSON.stringify(payload),

            // Función Success
            function success(resp){
                //Ext.getBody().unmask();

                var msg;
                try { msg = Ext.decode(resp.responseText); }
                catch(e){ msg = { success:true, message:'Success', data:{} }; }

                // Elige el primero que esta disponible
                var d = msg.data || {};
                var display = d.description || (' ' + (d.name || '—'));

                // Creación del mensaje: backend + identificador de la persona
                var text;
                if (msg && msg.message){
                    text = msg.message + ': ' + display;
                } else {
                    //text = (isCreate ? 'Usuario creado: ' : 'Usuario actualizado: ') + display;
                }

                // Lanza la alerta con el mensaje
                jsTerian.toastAlert(text, 'success');

                // Recargar el store
                jsTerian.reloadStore('storeRole');

                var formRecord = Ext.getCmp('formRecord');

                formRecord.cleanForm();

            },

            // Funcion Failure
            function failure(response){
                //Ext.getBody().unmask();

                // Intenta obtener el error
                var parsed = {};
                try { parsed = Ext.decode(response.responseText || '{}'); } catch(e){}

                // Creación del mensaje
                //text = (isCreate ? 'created: ' : 'updated: ');

                // Crea el mensaje de error y lanza la alerta
                let html = Ext.htmlEncode(parsed.message || `Failed to ${text} record`);
                if (parsed.error) html += '<br/><p>' + 'Error, no se pudieron registrar los cambios' + '</p>';

                jsTerian.toastAlert(html, 'error', parsed.error);

            }
        );
    },

    deleteRole: function(id_role) {
        // Url de la solicitud
        var url = jsTerian.makeUrl('role/delete',id_role);

        jsTerian.makeRequest(
            'DELETE',
            url,
            null,

            // Función Success
            function(response) {

                // Intenta obtener el mensaje, en caso contrario lo asigna
                var msg = {};
                try { msg = Ext.decode(response.responseText); } catch(e){}

                // Mostrar mensaje del backend directamente
                var text = msg && msg.message ? msg.message : 'Registro eliminado';
                jsTerian.toastAlert(text, 'success');

                jsTerian.reloadStore('storeRole');
            },

            // Función Failure
            function(response) {

                // Intenta obtener el error
                var parsed = {};
                try { parsed = Ext.decode(response.responseText || '{}'); } catch(e){}

                // Crea el mensaje de error y lanza la alerta
                let html = Ext.htmlEncode(parsed.message || 'Failed to eliminated user');
                if (parsed.error) html += '<br/><p>' + 'Error, no se pudo eliminar el registro' + '</p>';

                jsTerian.toastAlert(html, 'error', parsed.error);
            }
        );
    }

});
