/*
 * File: app/store/storeNode.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damCollection.store.storeNode', {
    extend: 'Ext.data.Store',

    requires: [
        'damCollection.model.modelNode',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeNode',
            model: 'damCollection.model.modelNode',
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json',
                    rootProperty: 'children'
                }
            },
            listeners: {
                onBeforeLoad: {
                    fn: me.onLoad
                }
            }
        }, cfg)]);
    },

    onLoad: function(store, nodeId) {
        // Obtener el nodo
        nodeId = nodeId || "c-1";

        // Obtener la ventana para usar sus funciones
        var contMain = Ext.getCmp('contMain');

        // Armar el url, pasando el id del nodo
        var url = jsTerian.getUrl('tree/children', nodeId);

        const proxy = store.getProxy();
        proxy.url = url;

        // Define los parámetros
        const params = {};
        params.include_data = true;

        // Asigna los parámetros al proxy
        proxy.setExtraParams(params);

        // Añadir el header con la auth
        jsTerian.addAuthorizationHeader(store);

        // Evento para cargar el store
        store.load({
            callback: function(records, operation, success) {

                // Lanza error en caso de que la solicitud falle
                if (!success) {
                    jsTerian.toastAlert("Error al cargar", "error");
                    store.removeAll();
                    return;
                }

                // Si se regresa al inicio se vacía el formView
                if (nodeId === 'c-1'){
                    contMain.cleanFormView();
                    return;
                }

                // Sino es root, se guarda el último nodo en el cache
                const ctx = appLocal.nodeCache && appLocal.nodeCache[nodeId];

                // Si existe un nodo seleccionado, llenar la información
                if (ctx) {
                    //  Obtener la ventana para usar la función de llenado
                    contMain.fillForm(ctx);
                } else {
                    // Si no hay cache, deja el form como esté o límpialo
                    contMain.cleanFormView();
                }
            }

        });
    }

});