/*
 * File: app/store/storeUser.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damCollection.store.storeUser', {
    extend: 'Ext.data.Store',

    requires: [
        'damCollection.model.modelUser',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeUser',
            autoLoad: false,
            model: 'damCollection.model.modelUser',
            proxy: {
                type: 'ajax',
                url: 'resources/data/users.json',
                reader: {
                    type: 'json',
                    rootProperty: 'users'
                }
            },
            listeners: {
                onBeforeLoad: {
                    fn: me.onLoad
                }
            }
        }, cfg)]);
    },

    onLoad: function(jsonstore) {
        // Petición para traer los projectos
        var url = jsTerian.getUrl('user/read');

        // Obtén el proxy del store
        const proxy = jsonstore.getProxy();
        proxy.url = url;

        // Obtener la pageSize y definir el currentPage en la primer página
        var pageSize = jsonstore.pageSize || 10;
        jsonstore.currentPage = 1;

        // Define los parámetros dinámicamente searchIdCustomer searchIdStatus searchIdType searchSerial searchNumber
        const params = {};
        params.per_page = pageSize;

        // Asigna los parámetros al proxy
        proxy.setExtraParams(params);

        // Agrega el encabezado de autorización
        jsTerian.addAuthorizationHeader(jsonstore);

        jsonstore.load({
            callback: function(records, operation, success) {
                if (success) {
                    if (records.length === 0) {
                        console.info('No hay usuarios');
                    }
                } else {
                    const response = operation.getError().response;
                    const status = response.status;

                    if (status >= 500) {
                        let msg = "Error en el servidor (" + status + ")";

                        try {
                            const json = Ext.decode(response.responseText);
                            if (json.error) {
                                msg = json.error;
                            }
                        } catch (e) {
                            console.warn('No se pudo parsear el error');
                        }

                        jsTerian.toastAlert(msg, 'error');
                    }

                    jsonstore.removeAll();
                }
            }
        });
    }

});