/*
 * File: app/store/storeAsset.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damSearch.store.storeAsset', {
    extend: 'Ext.data.Store',

    requires: [
        'damSearch.model.modelAsset',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeAsset',
            model: 'damSearch.model.modelAsset',
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json',
                    rootProperty: 'assets'
                }
            },
            listeners: {
                onBeforeLoad: {
                    fn: me.onLoad
                }
            }
        }, cfg)]);
    },

    onLoad: function(jsonstore) {
        // Función para formatear el tamaño (Bytes a KB, MB, etc.)
        const formatBytes = (bytes, decimals = 2) => {
            if (!bytes || bytes === 0) return '0 Bytes';
            const k = 1024;
            const dm = decimals < 0 ? 0 : decimals;
            const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
            const i = Math.floor(Math.log(bytes) / Math.log(k));
            return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
        };

        // Función para obtener la extensión
        const getExt = (name) => {
            if (!name) return '';
            return name.slice(((name.lastIndexOf(".") - 1) >>> 0) + 2).toUpperCase();
        };

        // Petición para traer los projectos
        var url = jsTerian.getUrl('asset/search');

        console.log('url:',url);

        // Obtén el proxy del store
        const proxy = jsonstore.getProxy();
        proxy.url = url;

        // Obtener la pageSize y definir el currentPage en la primer página
        var pageSize = jsonstore.pageSize || 10;
        jsonstore.currentPage = 1;

        // Define los parámetros dinámicamente searchIdCustomer searchIdStatus searchIdType searchSerial searchNumber
        const params = {};
        params.per_page = pageSize;
        params.q = jsTerian.readElementValue('tfAssetSearch');

        // Asigna los parámetros al proxy
        proxy.setExtraParams(params);

        // Agrega el encabezado de autorización
        jsTerian.addAuthorizationHeader(jsonstore);

        jsonstore.load({
            callback: function(records, operation, success) {
                if (success) {
                    if (records.length === 0) {
                        console.info('No hay Registros');
                    }
                    else{
                        records.forEach(record => {
                            const filename = record.get('original_filename'); // Extraído de la data
                            const bytes = record.get('size_bytes');           // Extraído de la data

                            record.set({
                                file_extension: getExt(filename),
                                file_size: formatBytes(bytes)
                            });
                        });
                    }
                } else {
                    const response = operation.getError().response;
                    const status = response.status;

                    if (status >= 500) {
                        let msg = "Error en el servidor (" + status + ")";

                        try {
                            const json = Ext.decode(response.responseText);
                            if (json.error) {
                                msg = json.error;
                            }
                        } catch (e) {
                            console.warn('No se pudo parsear el error');
                        }

                        jsTerian.toastAlert(msg, 'error');
                    }

                    jsonstore.removeAll();
                }
            }
        });
    }

});