/*
 * File: app/store/storeParam.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('basicConfig.store.storeParam', {
    extend: 'Ext.data.Store',

    requires: [
        'basicConfig.model.modelParam',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeParam',
            model: 'basicConfig.model.modelParam',
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json',
                    rootProperty: 'parameters'
                }
            },
            listeners: {
                onBeforeLoad: {
                    fn: me.onLoad
                }
            }
        }, cfg)]);
    },

    onLoad: function(store, idConfig) {
        // Petición para traer los projectos
        var url = jsTerian.getUrl('parameter/read');

        // Obtén el proxy del store
        const proxy = store.getProxy();
        proxy.url = url;

        // Obtener la pageSize y definir el currentPage en la primer página
        var pageSize = store.pageSize || 10;
        store.currentPage = 1;

        // Define los parámetros dinámicamente searchIdCustomer searchIdStatus searchIdType searchSerial searchNumber
        const params = {};
        params.per_page = pageSize;

        if (idConfig) {
            params.id_configuration = idConfig;
        }

        // Asigna los parámetros al proxy
        proxy.setExtraParams(params);

        // Agrega el encabezado de autorización
        jsTerian.addAuthorizationHeader(store);

        store.load({
            callback: function(records, operation, success) {
                if (success) {
                    if (records.length === 0) {
                        console.info('No hay parametros');
                    }
                } else {
                    const response = operation.getError().response;
                    const status = response.status;

                    if (status >= 500) {
                        let msg = "Error en el servidor (" + status + ")";

                        try {
                            const json = Ext.decode(response.responseText);
                            if (json.error) {
                                msg = json.error;
                            }
                        } catch (e) {
                            console.warn('No se pudo parsear el error');
                        }

                        jsTerian.toastAlert(msg, 'error');
                    }

                    store.removeAll();
                }
            }
        });
    }

});