/*
 * File: app/view/contMain.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('basicAccess.view.contMain', {
    extend: 'Ext.Container',
    alias: 'widget.contMain',

    mixins: [
        'Ext.mixin.Responsive'
    ],
    requires: [
        'basicAccess.view.contMainViewModel',
        'Ext.Container',
        'Ext.Img',
        'Ext.field.Text',
        'Ext.Button',
        'Ext.XTemplate'
    ],

    config: {
        responsiveConfig: 'responsiveConfig: {\n    \'width < 800\': {\n        layoutMode: \'mobile\' \n    },\n    \'width >= 800\': {\n        layoutMode: \'desktop\'\n    }\n}'
    },

    viewModel: {
        type: 'contmain'
    },
    cls: 'colorFormLite',
    id: 'contMain',
    itemId: 'contMain',
    style: 'border: 1px dashed #999;',
    fullscreen: true,
    layout: 'vbox',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            cls: 'imagenAmbiente',
            height: 212,
            id: 'contHeader',
            itemId: 'contHeader'
        },
        {
            xtype: 'container',
            flex: 1,
            id: 'contLogin',
            itemId: 'contLogin',
            layout: 'hbox',
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    id: 'contLogo',
                    itemId: 'contLogo',
                    style: 'border: 0px dashed #fc036b;',
                    margin: '7 0 7 0',
                    layout: {
                        type: 'vbox',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'image',
                            height: 144,
                            id: 'imgLogo',
                            itemId: 'imgLogo',
                            src: '../../../../framework/ambiente/utmLogoDAM.png'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    id: 'contInput',
                    itemId: 'contInput',
                    style: 'border: 0px dashed #999;',
                    margin: '7 0 7 0',
                    layout: {
                        type: 'hbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            id: 'contGroup',
                            itemId: 'contGroup',
                            minWidth: 350,
                            items: [
                                {
                                    xtype: 'container',
                                    id: 'contInputTf',
                                    itemId: 'contInputTf',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'tfUser',
                                            itemId: 'tfUser',
                                            label: 'Usuario'
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'tfPassword',
                                            itemId: 'tfPassword',
                                            label: 'Password',
                                            inputType: 'password'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    id: 'contInputAction',
                                    itemId: 'contInputAction',
                                    style: 'background: transparent; border: none; box-shadow: none;',
                                    padding: 15,
                                    layout: {
                                        type: 'box',
                                        align: 'center',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            height: 48,
                                            id: 'btnAccess',
                                            itemId: 'btnAccess',
                                            ui: 'action',
                                            width: 150,
                                            iconCls: 'fas fa-user-lock',
                                            text: 'Ingresar',
                                            listeners: {
                                                tap: 'onBtnAccessTap'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    id: 'contAction',
                    itemId: 'contAction',
                    width: '25%',
                    layout: 'form'
                }
            ]
        },
        {
            xtype: 'container',
            height: 200,
            id: 'contBottom',
            itemId: 'contBottom',
            data: {
                year: new Date().getFullYear()
            },
            tpl: [
                '<div style="text-align: center; padding: 15px;">',
                '    <div style="margin-bottom: 10px; font-weight: bold; color: #003366;">',
                '        Utility Trailers de Mexico &copy; {year}',
                '    </div>',
                '    <div style="display: flex; justify-content: center; gap: 20px; flex-wrap: wrap;">',
                '        <a href="https://wa.me/525539336340?text=Hola,%20solicito%20una%20consulta" ',
                '           target="_blank" style="text-decoration: none; color: #003366; display: flex; align-items: center;">',
                '            <i class="fab fa-whatsapp" style="font-size: 18px; color: #25D366; margin-right: 8px;"></i>',
                '            <span style="font-weight: 500;">55 3933 6340</span>',
                '        </a>',
                '        <a href="tel:8008845489" style="text-decoration: none; color: #003366; display: flex; align-items: center;">',
                '            <i class="fas fa-phone" style="font-size: 18px; color: #007bff; margin-right: 8px;"></i>',
                '            <span style="font-weight: 500;">800 884 5489</span>',
                '        </a>',
                '    </div>',
                '</div>',
                ''
            ]
        }
    ],
    listeners: {
        resize: 'onContMainResize'
    },

    onBtnAccessTap: function(button, e, eOpts) {
        appLocal.doLogin();
    },

    onContMainResize: function(element, info, eOpts) {
        console.log('resize');
        console.log(element);

        console.log('info');
        console.log(info);

        let contLogin = Ext.getCmp('contLogin');
        let contHeader = Ext.getCmp('contHeader');

        let width = info;

        // 1. Log para depurar
            console.log('El ancho actual es:', width);

            // 2. Lógica condicional
            // Importante: Verifica el layout actual para no forzarlo mil veces si no ha cambiado
            var currentLayout = this.getLayout().type;

            if (width < 1000 /*&& currentLayout !== 'vbox'*/) {
                console.log('-> Cambiando a Modo Móvil');


                contLogin.setLayout('vbox');
                contHeader.setHeight(100);

            }
            else if (width >= 1000 /*&& currentLayout !== 'hbox'*/) {
                console.log('-> Cambiando a Modo Escritorio');
                contLogin.setLayout('hbox');
                contHeader.setHeight(212);
            }


    }

});