/*
 * File: app/model/modelNode.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damCollection.model.modelNode', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],


    fields: [
        {
            name: 'id'
        },
        {
            name: 'node_type'
        },
        {
            name: 'text'
        },
        {
            name: 'is_active'
        },
        {
            name: 'deleted_at'
        },
        {
            name: 'has_children'
        },
        {
            name: 'parent_id'
        },
        {
            name: 'id_collection'
        },
        {
            name: 'name'
        },
        {
            name: 'description'
        },
        {
            name: 'parent_id_collection'
        },
        {
            name: 'is_group'
        },
        {
            name: 'id_resource'
        },
        {
            name: 'field33'
        },
        {
            name: 'code'
        },
        {
            name: 'field35'
        },
        {
            name: 'id_resource_tab'
        },
        {
            name: 'field37'
        },
        {
            name: 'tab_code'
        },
        {
            name: 'short_description'
        },
        {
            name: 'sort_order'
        },
        {
            name: 'id_asset_type'
        },
        {
            name: 'action'
        },
        {
            name: 'app_url'
        }
    ]

});