/*
 * File: app/model/modelUser.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damCollection.model.modelUser', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],


    fields: [
        {
            name: 'id_user'
        },
        {
            name: 'email'
        },
        {
            name: 'password_hash'
        },
        {
            name: 'is_active'
        },
        {
            name: 'id_role'
        },
        {
            name: 'first_name'
        },
        {
            name: 'paternal_last_name'
        },
        {
            name: 'maternal_last_name'
        },
        {
            name: 'phone'
        }
    ]

});