/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'modelRole',
        'modelUser',
        'modelCollection'
    ],
    stores: [
        'storeUser',
        'storeRole',
        'storeCollection'
    ],
    views: [
        'contMain'
    ],
    name: 'basicUserAccess',

    launch: function() {
        Ext.create('basicUserAccess.view.contMain', {fullscreen: true});
        appLocal = this.getApplication();

        // Carga de stores
        jsTerian.loadStore('storeUser');
        jsTerian.loadStore('storeCollection');
    },

    saveUserCollections: function(userId) {
        var contMain = Ext.getCmp('contMain');

        var payload = contMain.buildCollectionsPayload();
        var url = jsTerian.makeUrl('/user/' + userId + '/collections');

        jsTerian.makeRequest(
            'PUT',
            url,
            payload,
            function (response) {
                Ext.Msg.alert('Éxito', 'Colecciones actualizadas correctamente');
            },
            function (response) {
                var parsed = {};
                try {
                    parsed = Ext.decode(response.responseText || '{}');
                } catch (e) {}

                Ext.Msg.alert(
                    'Error',
                    parsed.message || 'No se pudieron actualizar las colecciones'
                );
            }
        );
    },

    getUserCollections: function(idUser) {
        var url = jsTerian.makeUrl('/user/' + idUser + '/collections');

        jsTerian.makeRequest(
            'GET',
            url,
            null,
            function(response) {
                var msg = {};
                try { msg = Ext.decode(response.responseText); } catch (e) {}

                var assignedIds = msg.collection_ids || [];
                var store = Ext.getStore('storeCollection');

                if (!store) {
                    return;
                }

                store.each(function(record) {
                    record.set(
                        'selected',
                        assignedIds.includes(record.get('id_collection'))
                    );
                });
            },
            function(response) {
                var parsed = {};
                try { parsed = Ext.decode(response.responseText || '{}'); } catch (e) {}

                let html = Ext.htmlEncode(parsed.message || 'Failed to read user collections');
                if (parsed.error) {
                    html += '<br/><p>Error, no se pudo obtener la información</p>';
                }

                jsTerian.toastAlert(html, 'error', parsed.error);
            }
        );
    }

});
