/*
 * File: app/view/contMain.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('damFeedback.view.contMain', {
    extend: 'Ext.Container',
    alias: 'widget.contMain',

    mixins: [
        'Ext.mixin.Responsive'
    ],
    requires: [
        'damFeedback.view.contMainViewModel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.form.Panel',
        'Ext.Label',
        'Ext.form.FieldSet',
        'Ext.field.TextArea'
    ],

    config: {
        responsiveConfig: 'responsiveConfig: {\n    \'width < 800\': {\n        layoutMode: \'mobile\' \n    },\n    \'width >= 800\': {\n        layoutMode: \'desktop\'\n    }\n}'
    },

    viewModel: {
        type: 'contmain'
    },
    id: 'contMain',
    itemId: 'contMain',
    layout: 'vbox',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'toolbar',
            cls: 'sap-toolbar',
            id: 'toolbarMain',
            itemId: 'toolbarMain',
            docked: 'bottom',
            items: [
                {
                    xtype: 'button',
                    id: 'btnConfirm',
                    itemId: 'btnConfirm',
                    ui: 'confirm',
                    minWidth: 90,
                    iconCls: 'fas fa-envelope',
                    text: 'Enviar',
                    textAlign: 'left',
                    listeners: {
                        tap: 'onBtnConfirmTap'
                    }
                },
                {
                    xtype: 'button',
                    id: 'btnReset',
                    itemId: 'btnReset',
                    ui: 'decline',
                    minWidth: 90,
                    iconCls: 'fas fa-arrows-rotate',
                    text: 'Reset',
                    textAlign: 'left',
                    listeners: {
                        tap: 'onBtnResetTap'
                    }
                },
                {
                    xtype: 'spacer'
                },
                {
                    xtype: 'button',
                    itemId: 'mybutton1',
                    text: 'MyButton1',
                    listeners: {
                        tap: 'onMybutton1Tap'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            id: 'contFeedback',
            itemId: 'contFeedback',
            layout: 'vbox',
            items: [
                {
                    xtype: 'formpanel',
                    flex: 1,
                    id: 'formFeedback',
                    itemId: 'formFeedback',
                    innerCls: 'sap-form-background',
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'label',
                            id: 'lbInfo',
                            itemId: 'lbInfo',
                            displayed: false,
                            html: '',
                            margin: '7 7 7 7'
                        },
                        {
                            xtype: 'fieldset',
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'tfSubject',
                                    itemId: 'tfSubject',
                                    margin: '0 10 0 10',
                                    padding: '7 7 0 7',
                                    label: 'Asunto'
                                },
                                {
                                    xtype: 'textareafield',
                                    id: 'taComment',
                                    itemId: 'taComment',
                                    margin: '0 10 0 10',
                                    padding: '7 7 0 7',
                                    label: 'Comentario'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        resize: 'onContMainResize'
    },

    onBtnConfirmTap: function(button, e, eOpts) {
        Ext.getCmp('contMain').feedbackSend();
    },

    onBtnResetTap: function(button, e, eOpts) {
        Ext.getCmp('contMain').feedbackReset();
    },

    onMybutton1Tap: function(button, e, eOpts) {

        Ext.Msg.alert(
            'Título del Aviso',
            'La operación se completó con éxito.',
            function() {
                console.log('El usuario cerró el mensaje');
            }
        );


        /*
        Ext.Msg.prompt(
            'Nombre del Archivo',
            'Ingresa el nuevo nombre:',
            function(buttonId, value) {
                if (buttonId === 'ok' && value) {
                    console.log('Nuevo nombre:', value);
                }
            }
        );
        */
    },

    onContMainResize: function(element, info, eOpts) {
        console.log('>>>resizswse');
        console.log(element);

        console.log('>>>info');
        console.log(info);


        let width = info;

        // 1. Log para depurar
            console.log('El ancho actual es:', width);

            // 2. Lógica condicional
            // Importante: Verifica el layout actual para no forzarlo mil veces si no ha cambiado
            var currentLayout = this.getLayout().type;

            if (width < 1000 /*&& currentLayout !== 'vbox'*/) {
                console.log('-> Cambiando a Modo Móvil');
                this.setLayout('hbox');
            }
            else if (width >= 1000 /*&& currentLayout !== 'hbox'*/) {
                console.log('-> Cambiando a Modo Escritorio');
                this.setLayout('vbox');
            }

    },

    feedbackSend: function() {
        var fnSuccess = function(pResponse){
            console.log('Success: Prospecto Asignado');

            var msg;
            try {
                msg = Ext.decode(pResponse.responseText);
            }
            catch(e){
                msg = { success:true, message:'Success', data:{} };
            }

            console.log('msg: ', msg);

            // Elige el primero que esta disponible
            var data = msg.data || {};

            console.log('data:',data);

            Ext.getCmp('contMain').prospectUserSave(jsTerian.getDataObjSS('TMP_SESSION','id_user'),data.id_prospect);



        };

        var fnFailure = function(pResponse){
            console.log('Failure: Prospecto fallo el grado');
        };


        var endPoint = 'feedback/create';
        var httpVerb = 'POST';

        if(jsTerian.readElementValue('tfMail') === jsTerian.getDataObjSS('UTM_PROSPECT','email')){
            var endPoint = 'prospect/update/' + jsTerian.getDataObjSS('UTM_PROSPECT','id_prospect');
            var httpVerb = 'PUT';
        }

        var url = jsTerian.getUrl(endPoint);

        // Informacion a enviar
        var jsonData = JSON.stringify({
            'subject' : jsTerian.readElementValue('tfSubject'),
            'comment' : jsTerian.readElementValue('taComment')
        });

        console.info('prospectDave_jsonData:',jsonData);
        console.info('prospectDave_httpVerb:',httpVerb);
        console.info('prospectDave_url:',url);

        jsTerian.makeRequest(httpVerb,url, jsonData, fnSuccess, fnFailure, true);

    },

    feedbackReset: function() {
        Ext.getCmp('tfSubject').setValue('');
        Ext.getCmp('taComment').setValue('');
    }

});