/*
 * File: app/store/storeRole.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('basicUser.store.storeRole', {
    extend: 'Ext.data.Store',

    requires: [
        'basicUser.model.modelRole',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeRole',
            model: 'basicUser.model.modelRole',
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json',
                    rootProperty: 'roles'
                }
            },
            listeners: {
                onBeforeLoad: {
                    fn: me.onLoad
                }
            }
        }, cfg)]);
    },

    onLoad: function(store) {
        // Petición para traer los projectos
        var url = jsTerian.getUrl('role/read/nopagination');

        // Obtén el proxy del store
        const proxy = store.getProxy();
        proxy.url = url;

        // Obtener la pageSize y definir el currentPage en la primer página
        //var pageSize = jsonstore.pageSize || 10;
        //jsonstore.currentPage = 1;

        // Agrega el encabezado de autorización
        jsTerian.addAuthorizationHeader(store);

        store.load({
            callback: function(records, operation, success) {
                if (success) {
                    console.info("StoreRole");
                    console.info(records);
                    if (records.length === 0) {
                        console.info('No hay usuarios');
                    }
                } else {
                    const response = operation.getError().response;
                    const status = response.status;

                    if (status >= 500) {
                        let msg = "Error en el servidor (" + status + ")";

                        try {
                            const json = Ext.decode(response.responseText);
                            if (json.error) {
                                msg = json.error;
                            }
                        } catch (e) {
                            console.warn('No se pudo parsear el error');
                        }

                        jsTerian.toastAlert(msg, 'error');
                    }

                    jsonstore.removeAll();
                }
            }
        });
    }

});