/*
 * File: app/store/jsonStoreLogAccess.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('basicUserLogAccess.store.jsonStoreLogAccess', {
    extend: 'Ext.data.Store',

    requires: [
        'basicUserLogAccess.model.modelLogAccess',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'jsonStoreLogAccess',
            model: 'basicUserLogAccess.model.modelLogAccess',
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json',
                    rootProperty: 'logs'
                }
            },
            listeners: {
                onBeforeLoad: {
                    fn: me.onLoad
                }
            }
        }, cfg)]);
    },

    onLoad: function(jsonstore) {
        console.log('onLoad...');


        var dtStart = Ext.getCmp('dfDateStart').getValue();
        var dtEnd   = Ext.getCmp('dfDateEnd').getValue();

        dtStart = Ext.Date.format(dtStart, 'Y-m-d');
        dtEnd   = Ext.Date.format(dtEnd, 'Y-m-d');

        console.log('dtStart:',dtStart);
        console.log('dtEnd:',dtEnd);


        var endPoint = 'user/access-logs?' + 'start_date=' + dtStart + '&end_date=' + dtEnd;
        var url = jsTerian.getUrl(endPoint);

        console.log('url: ',url);

        // Obtén el proxy del store
        const proxy = jsonstore.getProxy();
        proxy.url = url;

        // Obtener la pageSize y definir el currentPage en la primer página
        var pageSize = jsonstore.pageSize || 10;
        jsonstore.currentPage = 1;

        // Define los parámetros dinámicamente searchIdCustomer searchIdStatus searchIdType searchSerial searchNumber
        const params = {};
        params.id_user = 25;
        params.per_page = pageSize;


        // Asigna los parámetros al proxy
        proxy.setExtraParams(params);

        // Agrega el encabezado de autorización
        jsTerian.addAuthorizationHeader(jsonstore);

        jsonstore.load({
            callback: function(records, operation, success) {
                if (success) {
                    if (records.length === 0) {
                        console.info('No hay registros');
                    }
                } else {
                    const response = operation.getError().response;
                    const status = response.status;

                    if (status >= 500) {
                        let msg = "Error en el servidor (" + status + ")";

                        try {
                            const json = Ext.decode(response.responseText);
                            if (json.error) {
                                msg = json.error;
                            }
                        } catch (e) {
                            console.warn('No se pudo parsear el error');
                        }

                        jsTerian.toastAlert(msg, 'error');
                    }

                    jsonstore.removeAll();
                }
            }
        });

    }

});