/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'modelLogAccess'
    ],
    stores: [
        'jsonStoreLogAccess'
    ],
    views: [
        'contMain'
    ],
    name: 'basicUserLogAccess',

    launch: function() {
        Ext.create('basicUserLogAccess.view.contMain', {fullscreen: true});
        // Definición manual de meses y días en español
        Ext.Date.monthNames = [
            "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
            "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
        ];

        Ext.Date.dayNames = [
            "Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"
        ];

        // Opcional: Definir el formato de fecha por defecto para que coincida (Día/Mes/Año)
        Ext.Date.defaultFormat = 'd/m/Y';

        Ext.getCmp('dfDateStart').setValue(new Date());
        Ext.getCmp('dfDateEnd').setValue(new Date());

        jsTerian.loadStore('jsonStoreLogAccess');
    }

});
